### ISSUE TITLE
Upload config button doesn't activate after opening a config

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1000]
**Describe the bug**
Upload config button doesn't activate after opening a config

**Steps To Reproduce**
1. Go to `Mobiflight Modules`
2. Select one of your boards
3. Open a config file

![Button](https://user-images.githubusercontent.com/9524118/200143591-ed65fe7f-4f44-44aa-b0e1-6b039dcc7add.gif)

**Expected behavior**
The `Upload config` button activates so you can upload the config.

**Actual behavior**
The `Upload config` button doesn't activate

**Details**
 - MobiFlight Version: 9.6.0

**Additional context**
If you expand the module and select any of the devices that will cause the button to activate.

**Comment by neilenns** [comment]
The code that enables/disables the button is here: https://vscode.dev/github/MobiFlight/MobiFlight-Connector/blob/5e62a246756c16203d9a3c171f2cdab307afafd7/UI/Panels/Settings/MobiFlightPanel.cs#L234-L235

Doesn't look like it ever gets called after the open finishes.

**Comment by neilenns** [comment]
It's easy enough to move that line of code to a method and call it after open succeeds but... why is this just being noticed now? Seems like this woulda been broken for quite a while?

**Comment by tigert** [comment]
For me the button stays active all the time.

Right now I only have one arduino Pro Micro connected, thanks to taking the rest to FSWeekend, and I haven't yet reassembled the sim setup..

**Comment by DocMoebiuz** [comment]
For me too... i cannot reproduce this. 
Did we really have to use issue#1000 for this  :(

**Comment by DocMoebiuz** [comment]
The problem in your screen cast is, that you did not select a board... the blue selection was missing.

**Comment by neilenns** [comment]
> The problem in your screen cast is, that you did not select a board... the blue selection was missing. For some reason, still, I can't find a way to reproduce it.
> 

The module is selected, you can see it in blue in the screen cast before the open config button is clicked.

I was able to reproduce this many times, as could the original person in discord. Looking at the code it can happen, there is nothing to force the button active after opening a config.

**Comment by DocMoebiuz** [comment]
there is nothing in the code that disables the button on opening either so I find the proposed solution feels wrong.

In your screencast it is not selected by the user, but when you click the button- i would guess that "afterselect"-event is not properly triggered in this case.

**Comment by DocMoebiuz** [comment]
How do you navigate to the settings because I really cannot reproduce this behavior at all:

1) I click MF Board Settings from toolbar and the Boards tabs opens and the module is preselected, all buttons active

2) I navigate via the Main menu, the General tab is active, i switch to Boards and nothing is selected - the toolbar is totally deactivated until i select the board - once selected the menu items become active

**Comment by elral** [comment]
I just tested it, for me the upload button is also not active after opening a config file. It also stays inactive if a select the board. After selecting one device the upload button gets active. Same as in the screen cast from Neil.

**Comment by DocMoebiuz** [comment]
possibly related to #925

**Comment by elral** [comment]
Just make an additional test.
For me this happens only if the board has no device configured.
Onse a device is configured, the upload button is active after loading a config file.
