### ISSUE TITLE
Testing outputs directly from the configuration overview

### ISSUE THREAD

**Issue by TheFog8** [MobiFlight/MobiFlight-Connector#1005]
To test a configuration like a LED or a servo you have to open the settings of the configuration, go to the display tab and click on "Test".
You have to do these steps for every configuration you want to test.

It would be nice, if there would be an option in the right click menu of the configuration so that you can just make a right mouse click and say "Test". The resulting test operation should take care of any options (for example % of movement for a servo) that are entered on the display tab of the corresponding configuration.

**Comment by pizman** [comment]
Agree.  Would be usefull and logical.

Whatever.... Most users handle this Test different to your way.   If i build a Config i choose for the Datasource and i choose for the target Device.... That moment i set the device, i still on the Display Tab.   So i use the TEST exactly there one time.
Basically there is no need to make this test once again.
Test it when you create it.  If it work you never need to do it again.

But finally.   This tool would be cool !

**Comment by DocMoebiuz** [comment]
I had wished for this way of testing many times. You have your config, you know it's working but you're working on your panel connecting and disconnecting things and then it's a time saver if you simply can trigger it from the list via the context menu.

I was surprised that i was not able to find this request already in our Github backlog.
