### ISSUE TITLE
Modules dialog shows blank right pane if assigned pin is missing from board.json file

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1013]
**Describe the bug**
Modules dialog shows blank right pane if assigned pin is missing from board.json file

**Steps To Reproduce**
1. Add a button to your board and assign it pin `3`.
2. Edit the .board.json file for the board and remove pin `3` from the list of valid pins
3. Run MobiFlight again
4. Open the modules dialog and click on the module

**Expected behavior**
Right pane shows module info

**Actual behavior**
Empty right pane

<img width="312" alt="image" src="https://user-images.githubusercontent.com/9524118/202291476-44d2b705-10d0-47b6-950b-a2bda17f6bae.png">

**Additional context**
Exception is `syncPanelWithSelectedDevice: Exception: Object reference not set to an instance of an object.`

This is definitely an edge case from hand-editing .board.json files but should probably be handled better.

Found by user Felipe in Discord.

**Comment by felipegl98** [comment]
Many thanks for the support!

**Comment by neilenns** [comment]
I took a look at this tonight and it's more work than I think is worth it considering it's an edge case that shouldn't be hit in normal use. @DocMoebiuz I think this can just be closed.

**Comment by DocMoebiuz** [comment]
What I was actually thinking the other day was, that when I store a board config with my devices, I can load it on a different type of board without any notification. In this circumstance we could also get to the situation, where the config contains pins that are not valid, not compatible or not existing on the currently used board.

So i think I should store the board type with the config, and additionally also provide an error message in case it is no compatible.

**Comment by neilenns** [comment]
I don't understand what you mean by "the config" @DocMoebiuz. Board type is defined by the hardcoded string in the firmware. Users can't really make things be something else by accident, this was just a hand-edited board file with a missing pin.

**Comment by MobiFlight-Admin** [comment]
when a save the board's config with all its devices, I can later load it using the same or a different board. I can even use a different model, like I can perfectly load a config created for a mega onto my Pro Micro.

**Comment by neilenns** [comment]
Ok, but I still maintain we can just close this bug out without fixing it :)

**Comment by DocMoebiuz** [comment]
Not the case anymore. I could not determine which PR fixed this.
