### ISSUE TITLE
Input config ignores caps lock state when entering the first character into the description field

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1018]
**Describe the bug**
This bug was fixed several months ago by Neil, 
[https://github.com/MobiFlight/MobiFlight-Connector/issues/730](https://github.com/MobiFlight/MobiFlight-Connector/issues/730)
but somehow has crept back into Mobiflight.

**Steps To Reproduce**
1. Go to Inputs tab
2. Set Caps Lock key to ON
3. Select an input config (without entering the description field)
4. By default text entered opens the description field
5. Enter text into description
6. Note first character is in lower case, the rest being in upper case.

**Expected behavior**
Text entered should respect Caps Lock state.

**Actual behavior**
First character ignores Caps Lock state.

**Details**
 - MobiFlight Version: 9.6.0
 - FlightSim: irrelevant
 - AddOn: irrelevant

**Additional context**
Only affects input, output config behaves as expected.  Bug does not happen if you enter the description field.

**Comment by neilenns** [comment]
I only fixed it for the output config. Oops.
