### ISSUE TITLE
Pulse or a continuous option for Input on an xplane command

### ISSUE THREAD

**Issue by gordo19** [MobiFlight/MobiFlight-Connector#1025]
The current behaviour is that when an input condition sends a command, it send it once (and is not wrong), however that are cases where the command needs to be constantly written , eg for a test function when a switch is held at test.

my use case example here is:
Spring loaded switch to actuated the engine fire annunciator test function.   Currently the command just sent once, so I just get the function set on quickly rather than belong held on. (The command function can be held on via other means).  what I need it that function to be set on until the switch is released. 

So the request is option for the command to be sent Single or Continuous.

**Comment by DocMoebiuz** [comment]
Please use a workaround of vJoy or LUA script to create a custom Command for the time being. 

Holding is not supported by the UDP Api from xplane that Mobiflight is using. I will need to create a plugin or convince laminar research to add it to their API.

**Comment by gordo19** [comment]
Many Thanks for prompt response.  I was able to keep command on via the data ref tool actuation button, so thought maybe it was an easy win :)  but happy to do workaround.
