### ISSUE TITLE
Support Raspberry Pi Pico boards

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1032]
Sure would be nice to support these amazing boards...

**Comment by neilenns** [comment]
https://forum.micropython.org/viewtopic.php?t=10838 for how to wipe the flash on a board.

No idea how to handle a clean device that has no firmware on it.

**Comment by elral** [comment]
Hmhm, good question. I clean device will show up as USB drive the same way as putting it into booltoader mode.
Only idea would be on startup up to check for USB drives with the special file on it.

**Comment by neilenns** [comment]
> Hmhm, good question. I clean device will show up as USB drive the same way as putting it into booltoader mode. Only idea would be on startup up to check for USB drives with the special file on it.

Yeah. It seems a bit of a hack but I could set the `Port` to "USB-_driveletter_" then use that as a way to skip trying to read the info from it and just proceed straight to flashing with that info.
