### ISSUE TITLE
Exception in preconditions when referenced config is missing

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1040]
Reported by PeterHolt in discord

**Describe the bug**

I've run into some problems with 9.6.0.2. If I click the edit button on one of the hat switch inputs I get the error shown in pic2.  If I click Continue the InputConfigWizard opens and I have the bizarre precondition shown in pic3, the mcc file created in 9.6.0 had no precondition for this event.  

![2](https://user-images.githubusercontent.com/9524118/206858065-9982b1cb-584d-4592-9eab-ab3ba324561d.jpg)
![3](https://user-images.githubusercontent.com/9524118/206858067-eac123f1-376a-46f6-a47e-bd8a0a2db3cb.jpg)

Exception details:

```
************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MobiFlight.UI.Panels.Config.PreconditionPanel.UpdateNodeLabelsAndImages()
   at MobiFlight.UI.Panels.Config.PreconditionPanel.syncFromConfig(IBaseConfigItem config)
   at MobiFlight.UI.Dialogs.InputConfigWizard._syncConfigToForm(InputConfigItem config)
   at MobiFlight.UI.Dialogs.InputConfigWizard.ConfigWizard_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
```

Config file:

[Heli.txt](https://github.com/MobiFlight/MobiFlight-Connector/files/10200239/Heli.txt)

**Comment by neilenns** [comment]
Another user reported this in Discord today. Same exception. .mcc file is attached, the preconditions that have `ref="a18ef589-d13f-48cc-9ddb-8c037be68387"` as the reference don't have a matching output.

The code is explicitly firing the exception when the precondition references something that can't be found but it doesn't look like it gets properly handled anywhere.

[Roman_Design_VRControlBox_Universal_v20_Panel.zip](https://github.com/MobiFlight/MobiFlight-Connector/files/10300699/Roman_Design_VRControlBox_Universal_v20_Panel.zip)

**Comment by DocMoebiuz** [comment]
the problem with the labels is different from the preconditions.
