### ISSUE TITLE
Blink modifier keeps on blinking

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1048]
**Describe the bug**
Blink modifier in mcc file does not stop blinking with active="False"

**Steps To Reproduce**
1. Set blink modifier properly in mcc file with 
`<blink active="True" blinkValue="0" onOffSequence="500,500" />`
2. Check that blink works
3. Set blink to `active="False"`
4. Note blinking continues to work. 

**Expected behavior**
Blink should stop with `active="False"`

**Actual behavior**
LEDs continue to blink even with `active="False"`

**Details**
 - MobiFlight Beta 9.6.0.2
 - FlightSim: irrelevant
 - AddOn: irrelevant

**Additional context**
Workaround was to set `onOffSequence="0"`

**Comment by neilenns** [comment]
Need to add:

```C#
if (!Active) return;
```

here: https://github.dev/MobiFlight/MobiFlight-Connector/blob/64cc17c0ee80e458d2ede81a3b3f6dcb6ebd9840/MobiFlight/Modifier/Blink.cs#L69-L70

**Comment by neilenns** [comment]
A better fix is to test in ExecutionManager.cs so that each individual modifier doesn't have to remember to check this in the Apply() method. It'll protect against this same bug happening again in future modifiers.
