### ISSUE TITLE
manage orphan serials to map a config to a new board often fails to map 7segment displays

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#1060]
When you swap an arduino or recreate a serial, Mobiflight later notices references to a serial number that is no longer present, and asks you to manage them, so it can know which boartd should be replacing the now missing one. 

This seems to fail to map all devices sometimes, often this being an issue for 7segment modules.

**Comment by DocMoebiuz** [comment]
It would be nice to have a series of steps for reproducing this error.

I reviewed the code, and I can say that the serial substitution works and the only thing where you can have a problem is when your 7 segment modules are not having the same name. But that is kind of obvious.

**Comment by DocMoebiuz** [comment]
Can you please provide specific steps to reproduce this?

My test cases was passing:
* Add 7 Segment to board
* Create output config with this 7 segment display
* Use test button > verify that the display config is working
* Go to board settings
* Update the name of the board and upload new config
* Close settings
* Open orphan serials dialog (Extras > Manage Orphaned Serials)
* Assign board to old board name and confirm
* Run Test Mode again

Expected result:
* Display is working as before

Actual result:
* Display is working as before

**Comment by DocMoebiuz** [comment]
Cannot reproduce this. It seems to be related to a problem with the ProMicro which deserves a different issue.
