### ISSUE TITLE
Erroneous formatting of floating point values on 7-segment displays when last digit is zero.

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#1062]
**Describe the bug**
Set value to 123.450 and send it to a display.

Note that this, or any other value, if it is full hundredths (123.450 for example) this gets truncated by MF to 123.45, but if it is having also a significant digit as the third decimal (123.451 for example) it is not truncated.

So the main issue I guess is, MF should not truncate decimals even when there are no significant numbers there - or we would need to have a way to set the number of decimals we want. In many cases this doesnt matter at all. But sometimes it does, like here when the 7segment shows the value as 1234.50.

**Expected behavior**

Should not round values automatically without asking. Keep whatever you have and Round() explicitly if needed.

Though I guess it might not be as simple, it might not be MF that does truncation of zeros, it could be simconnect / xplane too, which makes it hard to define what precision the data should have.

**Details**
 - MobiFlight Version: git as of 2023/01/01

**Comment by DocMoebiuz** [comment]
a float number doesn't have a certain number of decimals. This is not a MobiFlight issue, that is how numbers are handled internally. What you are describing is a formatting issue and here the best way to do it is a "modifier" which allows to format the number eg ###.### or something alike.

The decimal point placement is a second issue in my opinion. But I will have to reproduce this first in the unit test.

**Comment by tigert** [comment]
sorry I must have missed my coffee when writing this.

I agree there needs to be a modifier to format the floats into a string, or manual Transform with Round and math in the current lack of it.

But the actual issue I was going to file is that the 7segment display seems to display those floats inconsistently depoending on whether the last digit is a zero or not. If the last digit is zero, the whole fraction part gets shifted t the right 

![image](https://user-images.githubusercontent.com/2587818/210853739-4ff0b042-48f7-4075-a57d-2086a9d43b6b.png)

This is from Mathias, and I had the same issue, I think the whole fractional part shifts one character to the right, and the decimal point segment display has no digit shown.

Like if you show a radio frequency or other decimal number on the digits, and the third decimal is not a zero, it works correctly:

123.456

But if you have the third decimal being a zero, it gets handled as 123.45 and the segments show the decimal point with an empty digit:

**Comment by tigert** [comment]
Actually the decimal point location seems to vary depending on the value. Like 123.456 makes the decimal point correct, but if you have 123.50, you get 123 .50

**Comment by MobiFlight-Admin** [comment]
Two things:

* I will have to double check why it's not the case for you but the main branch should be able to handle decimal numbers (floats) and correctly set the decimal point so that it doesn't occupy an entire digit but is placed together with a number. (on your pics thats not the case which is weird)

* There is no concept at the moment for an automatic alignment of a number based on its decimal point. apparently the numbers are aligned to the right in your case, so the number of digits after the decimal point affect where the decimal point will be.

At the moment I only consider the first item a bug in case it doesn't work.
Formatting modifiers will address the 2nd option.

**Comment by DocMoebiuz** [comment]
I can reproduce the issus and will fix it. Thanks!
