### ISSUE TITLE
LCD Display autofills unnecessarily (every time row is created) 

### ISSUE THREAD

**Issue by CaptainBobSim** [MobiFlight/MobiFlight-Connector#1072]
**Describe the bug**
When using an LCD module the LCD module auto-fills it as a device.
This is great the first time, but when referencing things the second time it makes a new LCD module display which interferes with it's default 123456 TEST text

**Steps To Reproduce**
1. Make an LCD "Master" Row
2. Make a row the "Master" row references
3. Assign it to a sim variable
4. Notice the Display auto-filled and the LCDs interfere
 
![LCD Default Behavior](https://user-images.githubusercontent.com/76851401/212617829-56cf7289-34e3-48bd-9be4-ad658b4a4430.gif)

**Expected behavior**
The LCD module either doesn't show until called or shows only the first time.
Maybe have the dialog "use type of" box empty by default?
![image](https://user-images.githubusercontent.com/76851401/212618073-5bdda9dd-b325-4730-b52f-8f5b53321616.png)

**Actual behavior**
The LCD module always pops up

**Details**
 - MobiFlight Version: [9.6.0 (not beta)]

**Additional context**
Not annoying unless referencing multiple variables

**Comment by pizman** [comment]
Looks like this is not located to LCD itself....    I expect your board simply just include the LCD Device.....

I do a Test.... With a board that include also a LED Output.
When i create the second Config Line (Without choose for the Device and just set a Variable) then Mobiflight "AutoFill" the used Device by the first available ( A LED in my case)
