### ISSUE TITLE
NullReferenceException in MobiFlight.InputConfig.AnalogInputConfig.ReadXml

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1073]
Reported in Discord, opening the attached .mcc file results in:

```
MobiFlight.InputConfig.AnalogInputConfig.ReadXml(XmlReader reader)
   at MobiFlight.InputConfigItem.ReadXml(XmlReader reader)
```

Open this with the debugger attached to figure out what's causing the crash and then add some try/catch logic.

[dualefis.txt](https://github.com/MobiFlight/MobiFlight-Connector/files/10466959/dualefis.txt)

**Comment by jetraid** [comment]
Fails occurs when add an analog input but don't assign any event, after restart mobiflight the error appears.
