### ISSUE TITLE
9.6.0.5 - startup is hanging after GetInfo call

### ISSUE THREAD

**Issue by DocMoebiuz** [MobiFlight/MobiFlight-Connector#1089]
**Describe the bug**
User is reporting slow start up after trying 9.6.0.5 beta.

**Steps To Reproduce**
1. Update to 9.6.0.5
2. Start MobiFlight

**Expected behavior**
A couple of seconds start up time until ready to be used

**Actual behavior**
Start up time in the minute range.

**Details**
 - MobiFlight Version: 9.6.0.5

**Additional context**

- 9.6.0.3 is working fast
- 9.6.0.4 is not working at all, exception on start 
- 9.6.0.5 is working slow
- internet on > slow, internet off > fast, but not as fast as in 9.6.0.3

**Comment by DocMoebiuz** [comment]
Ok, so after providing the user the builds with one commit AFTER the PICO support and one commit BEFORE the PICO support, the feedback is clear:

BEFORE: board enumeration in no time
AFTER: board enumeration takes 50+ seconds

@neilenns I haven't had the time to check, but maybe a special USB device or so? He doesn't have DVD drive

**Comment by neilenns** [comment]
The logs show it is stuck enumerating devices @DocMoebiuz ?

**Comment by DocMoebiuz** [comment]
here is the log:

```
Debug    01/22/2023 12:04:00    MobiFlightCache.getSupportedPorts(): Checking for compatible module: VID_2341&PID_0042&REV_0001.
Debug    01/22/2023 12:04:00    MobiFlightCache.getSupportedPorts(): Found potentially compatible module (Arduino Mega 2560): VID_2341&PID_0042&REV_0001@COM3.
Debug    01/22/2023 12:04:00    ExecutionManager.AutoConnectStart(): Started auto connect timer.
Warn    01/22/2023 12:04:00    ExecutionManager.mobiFlightCache_OnButtonPressed(): TCA Q-Eng 1&2 => Button 12  => PRESS =>  No config found.
Warn    01/22/2023 12:04:00    ExecutionManager.mobiFlightCache_OnButtonPressed(): TCA Q-Eng 1&2 => Button 16  => PRESS =>  No config found.
Info    01/22/2023 12:04:00    MobiFlightModule.Connect(): MobiflightModule.connect: Connected to Default at COM3 of type MobiFlight Mega (DTR=>True).
Debug    01/22/2023 12:04:01    MobiFlightModule.GetInfo(): Retrieved board: MobiFlight Mega, FCU1, 2.3.1, SN-b59-4d4.
Debug    01/22/2023 12:04:01    MobiFlightModule.Disconnect(): Disconnected FCU1:COM3.
Debug    01/22/2023 12:04:01    <LookupAllConnectedComModulesAsync>d__31.MoveNext(): End looking up connected modules.
Debug    01/22/2023 12:04:01    <connectAsync>d__33.MoveNext(): Clearing modules.
Debug    01/22/2023 12:04:01    MobiFlightCache.RegisterModule(): Registering module Default:COM3.
Info    01/22/2023 12:04:01    MobiFlightModule.Connect(): MobiflightModule.connect: Connected to Default at COM3 of type MobiFlight Mega (DTR=>True).
Debug    01/22/2023 12:04:03    MobiFlightModule.GetInfo(): Retrieved board: MobiFlight Mega, FCU1, 2.3.1, SN-b59-4d4.
Debug    01/22/2023 12:04:24    MobiFlightOutput.Set(): Command: SetPin <2,46,0;>.
```

here it "only" are 18 secs between GetInfo and the first device initialization. But user shared logs where this was even over a minute.

For me these log entries are happening at the same second - barely no delay between it
