### ISSUE TITLE
Run CI on every pull request

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1109]
We should build the app and run tests on every pull request, and attach the build to the PR like we do for the firmware.

**Comment by MobiFlight-Admin** [comment]
build and run tests is done. we only have to store the zip file as artifact

**Comment by DocMoebiuz** [comment]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/86157512/216762008-c1ac7283-2dcc-4e08-be4c-d344be55b297.png">
