### ISSUE TITLE
"Not Implemented" error when trying to use MFG Crosswind pedals

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#1131]
Create new input config line, select MFG Crosswind pedals from Module list.

You get the following dialog and the device list remains empty.

![image](https://user-images.githubusercontent.com/2587818/217329793-d2c7920d-77ef-4b96-b2c7-fa5b4599b8a8.png)

Log shows: Error    02/07/2023 19:49:11    Index was outside the bounds of the array.

**Comment by DocMoebiuz** [comment]
Send me the pedals so that I can test :D

**Comment by DocMoebiuz** [comment]
Problem is located because the Joystick name contains "/" which is used for splitting the serial number from the name
