### ISSUE TITLE
Use "MF Variable" simvar type by default

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#1133]
New config items default to MSFS 2020 Simconnect event type, which then causes a warning and red exclamation mark if the user is not using MSFS2020, or is just testing MF without a simulator - even when there is no configured simulation variable.

It would probably make more sense to default to MF Variable, since it is simulator-agnostic.

**Comment by DocMoebiuz** [comment]
Thanks for reporting.

The biggest user base uses msfs2020 sim variables. I think therefore, the preselection being this type could make more sense.

You are describing a testing scenario. Most users test in context of the sim, where they first start with defining the preset. It is natural to "read" first, then "display". So in this scenario the better preselection could be a sim type variable.

I think I hear you saying, that the red warning symbol bothers you. I agree, this could throw off people. It is used in varios cases, where it is not an error, but more like an info or warning. 
This is a limitation of the DataGridView component. We have a specific issue for this story already. #333 

i will close this issue in favor of #333

**Comment by tigert** [comment]
Good thinking. I think I do agree with you.
