### ISSUE TITLE
Negative Test Values for Stepper Motors

### ISSUE THREAD

**Issue by CaptainBobSim** [MobiFlight/MobiFlight-Connector#1141]
It used to be possible to set a negative test value - to turn the stepper counterclockwise.

I always found this helpful for the Turn Coordinator, as I could check that both left and right operations are working smoothly.

This can also be helpful for heading indicators and other instruments that do not have an absolute zero.

**Describe the solution you'd like**
I'd like no errors to appear when selecting a negative test value.

**Describe alternatives you've considered**
Reverse stepper wiring (not great)
Adjusting my zero and compensating (I'd prefer the zero point to be neutral)

**Additional context**
Latest beta using x27 stepper.
![image](https://user-images.githubusercontent.com/76851401/218342053-2d905395-bb8b-4d4d-a453-8e7599565c4a.png)

**Comment by DocMoebiuz** [comment]
True, i basically reused another check... it is OK to have negative numbers. So the check has to be just checking for "numbers"
