### ISSUE TITLE
"Trying to show config but display type Output not present." when opening an output config

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1145]
**Describe the bug**
When opening an output config I get the error "Trying to show config but display type Output not present." when opening an output config.

This appears to be from the renaming that happened to rename `Output` to `LED / Output` in the dialog.

The line of code where this gets logged is here:: https://github.dev/MobiFlight/MobiFlight-Connector/blob/cea64103ec105ed58a261305315a98122e1494b5/UI/Panels/OutputWizard/DisplayPanel.cs#L131-L134. At that point in the code `config.DisplayType` is `Output` but the combo box has `LED / Output` in it.

**Comment by neilenns** [comment]
I found this when testing my new Joystick string stuff.

**Comment by DocMoebiuz** [comment]
is that only a log entry or are you experiencing an actual problem?

**Comment by DocMoebiuz** [comment]
asking if it requires an immediate fix or not

**Comment by neilenns** [comment]
Just a log entry. Oddly everything still loads fine.
