### ISSUE TITLE
Feature request: upgrade hubhop events after installation

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#1152]
Since HubHop is now an integral part of how MobiFlight works for both MSFS2020 and X-Plane, I wonder if we should just 
 automatically update the latest events from hubhop when you run MobiFlight for the first time after installation / upgrade?

Because there is currently an issue where your events will get replaced with an older copy depending on the age of the snapshot that was included in a new release. And for a new installation of stable MobiFlight this means the data might be weeks or months old, depending on when the latest stable version of MF was released.

What if we just didnt ship the snapshot data at all, but rather just downloaded it on the first run?

**Comment by DocMoebiuz** [comment]
Yes, I like the idea.

**Comment by DocMoebiuz** [comment]
I think presets should be bundled just in case you have some problem with internet connection. It is very unlikely since you just downloaded the copy from the website.

**Comment by DocMoebiuz** [comment]
<img width="278" alt="image" src="https://github.com/MobiFlight/MobiFlight-Connector/assets/86157512/4c278f17-677b-44fb-b9a0-a8e80c1c3b71">

An automated check and reminds every time that your presets are older than 7 days.

**Comment by JaimeLeon2** [comment]
If there is no time stamp on the database, how would it know it is older than 7 days? 
Would it register a time stamp every time the database is updated?

**Comment by DocMoebiuz** [comment]
the first step would be to use the creation date of the file. it would be the day when the release was packaged and then every time you download again from hubhop.
