### ISSUE TITLE
Pico reset board firmware isn't flash_nuke.uf2

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1153]
I'm not sure where the firmware for resetting the Pico came from, but it's not the official "flash_nuke.uf2" file from Raspberry Pi that truly resets the board back to factory default and brings it up in bootsel mode.

We should replace the existing reset firmware with flash_nuke.uf2 from here: https://cdn-learn.adafruit.com/assets/assets/000/099/419/original/flash_nuke.uf2?1613329170

**Comment by elral** [comment]
> I'm not sure where the firmware for resetting the Pico came from

It's coming from https://github.com/elral/Mobiflight-EEPROM-clear/blob/main/platformio.ini
But it's a good idea to use the official reset file. Seems that I can delete the Pico environment in the linked platformio.ini.
