### ISSUE TITLE
IndexOutOfRangeException when opening LED display config panel

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1157]
Reported by a user in Discord, they have a specific config file that when loaded and the LedDisplay output panel is opened causes this crash:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MobiFlight.MobiFlightCache.GetModuleBySerial(String serial)
   at MobiFlight.UI.Panels.OutputWizard.DisplayPanel.displayLedAddressComboBox_SelectedIndexChanged(Object sender, EventArgs e)
```

Looking at the code `GetModuleBySerial()` explicitly throws an `IndexOutOfRangeException` exception when the serial number for the module isn't found in the list of connected modules. `displayLedAddressComboBox_SelectedIndexChanged` doesn't have a try/catch around the call, hence the crash.

Fix is to add a try/catch block here: https://github.dev/MobiFlight/MobiFlight-Connector/blob/cea64103ec105ed58a261305315a98122e1494b5/UI/Panels/OutputWizard/DisplayPanel.cs#L655-L656

**Comment by neilenns** [comment]
There are lots of places in the code that assume this won't throw exceptions. looks like shift registers have the same possible bug too.

**Comment by DocMoebiuz** [comment]
@neilenns thanks for reporting this. If possible, always provide a link to the conversation on Discord. That might help, e.g. reading more about the troubleshooting progress, etc.

**Comment by DocMoebiuz** [comment]
I think we should change this, return `null` and make an explicit check in the code after calling this method.
@neilenns thoughts?
