### ISSUE TITLE
Plus "+" as String in Transform not work.

### ISSUE THREAD

**Issue by pizman** [MobiFlight/MobiFlight-Connector#1166]
**Describe the bug**
A Plus Symbol "+" used in transform as Text not work as expected in case MF see the Result as a Integer (Instead of String)

**Steps To Reproduce**
1. Create a Output Config....  Source Mobiflight Variable
2. Use Transform :  '+123'
3. RUN Mobiflight and check the Output Value collumn

**Expected behavior**
We say show Text "+" and behind the number 15 .... So we like to see :  +15

**Actual behavior**
it show 15 only and remove the "+" Sign  ....   MF see it as a Integer  +15 is mathematical 15

![grafik](https://user-images.githubusercontent.com/26087116/221380969-c27b9d4c-99dd-4599-b848-3e917544a52a.png)

**Details**
 - MobiFlight Version: 9.7.0

**Additional context**
1. If we use a clear String format like 'a+123' it work and show a+123 in case it now see it as string !
2. In Compare Tab it work still fine with '+123'   Here MF understand it have to be a string in all ways.
![grafik](https://user-images.githubusercontent.com/26087116/221381072-a27399c9-b84e-43d2-839b-1e8e329fd601.png)

**Comment by DocMoebiuz** [comment]
This should be possible with the new Modifiers logic. Please test there and if necessary re-open the issue.
