### ISSUE TITLE
Provide Blink Mode

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#119]
[Issue created by DocMoebiuz: 2015-12-24]
[Last updated on bitbucket: 2020-12-20]

[Comment created by DocMoebiuz: 2020-12-20]
Maybe with predefined settings such as slow, medium, fast - or freely with ms.

[Comment created by DocMoebiuz: 2019-09-09]
You can have a blink mode if you are OK with a 1 second or longer blinking interval. This can be done using the offset of current seconds, apply modulo and a compare to it to map it to either 0 or 1 as you desire.

The offset then can be used either in a precondition or in the transform to achieve a blinking output.

**Comment by tigert** [comment]
I think on MSFS2020 (and / or maybe Simconnect in general?) the "simulator time" is actually much more fine grained variable, not just seconds
