### ISSUE TITLE
Difficult to type on Search input for Filter Preset List

### ISSUE THREAD

**Issue by lscarneiro** [MobiFlight/MobiFlight-Connector#1192]
**Describe the bug**
As the "Filter Preset List" logic happens for every keystroke on the Search input, the UI stutters with every key pressed.

Ideally, the UI should wait for the user to finish typing, and only then execute the filter, to avoid unintended typos caused by the user thinking the UI hasn't registered the key typed when it's just a temporary UI freeze happening

**Steps To Reproduce**
1. Go to Outputs (or Inputs)
2. Click on '....' (edit)
3. Select SimConnect (MSFS2020) selected as "Variable Type"
4. Click on "Reset" button (for increased effect)
5. Start typing something that matches lots of presets like: `indicator`, `on` or `_` 

**Expected behavior**
The UI should not freeze on every keystroke because of filtering, this helps with typing, avoiding typos and unnecessary wait or cleaning up with backspace

**Actual behavior**
The UI stutters for every keystroke

**Details**
 - MobiFlight Version: [e.g. 9.7.0]
 - FlightSim: MSFS2020 SimConnect
 - AddOn: [e.g. Default Aircraft]

**Additional context**
In a broader UI context, MobiFlight should (ideally) leverage the background thread in WinForms in an effort to avoid main UI thread freezes (which can be interpreted as problems or "bugs"), but this is not something fixable with a small tweak, though.

Also, while https://github.com/MobiFlight/MobiFlight-Connector/issues/1118 would be a great UI change as well, this would make the issue being reported here even more noticeable, since the user would always interact with the "Search" box first, and only add more filters later (which is a common practice even in e-commerces)

**Comment by DocMoebiuz** [comment]
The problem is the length of the filter... responsiveness is lowest when the length of filter text is short, e.g 1-3 characters.
Waiting for a small stop while typing or when reaching a minimum length are also valid strategies.
