### ISSUE TITLE
MAX7219 module goes to sleep

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1200]
**Describe the bug**
One Max7219 8 digit module connected to a mega 2560 pro (mini) consistently goes to sleep after 15 minutes of inactivity with the Msfs2020 Sim and Mobiflight running,  

**Steps To Reproduce**
1. Start MSFS2020, Mobiflight and load a flight on runway.  
2. Mobiflight in run mode.  
3. Leave unattended for 15 minutes
4. Note led display turns off.

**Expected behavior**
LED display should remain on.

**Actual behavior**
LED display turns off after 15 minutes.  Pressing any button in that panel will awaken the board and the display turns back on.  Pressing buttons in other panels does not awake this display.

**Details**
 - MobiFlight Version: 9.7.1
 - FlightSim: MSFS2020
 - AddOn: irrelevant

**Additional context**
If only happens with one particular mega board in my Transponder panel.  Two other 8-digit displays do not exhibit this behavior connected to a different mega board.

**Comment by DocMoebiuz** [comment]
This must be the energy saving mode. It should be prevented by resetting the timeout continously every 5 mins or so. What other devices do you have connected on the board?

**Comment by JaimeLeon2** [comment]
This particular mega board has about 40 buttons and switches, three leds, one 8-digit 7 segment display module and one dm13A led driver chip.

**Comment by DocMoebiuz** [comment]
And  you see these `Preventing entering EnergySaving mode: KeepAlive!` in your log, right?

**Comment by JaimeLeon2** [comment]
> And  you see these `Preventing entering EnergySaving mode: KeepAlive!` in your log, right?
> 

Yes. It does show that message.

**Comment by DocMoebiuz** [comment]
Do you also see these messages:

Debug	05/27/2023 18:18:50	<AutoConnectTimer_TickAsync>d__107.MoveNext(): No Sim running.
Debug	05/27/2023 18:18:59	MobiFlightModule.KeepAliveNeeded(): Preventing entering EnergySaving mode: KeepAlive!
Debug	05/27/2023 18:18:59	MobiFlightLedModule.Display(): Command: SetModule <1,0,1,000000,16,126;>.
Debug	05/27/2023 18:18:59	MobiFlightLedModule.Display(): Command: SetModule <1,0,0,000000,16,126;>.

**Comment by JaimeLeon2** [comment]
> Do you also see these messages:
> ```
> Debug	05/27/2023 18:18:50	<AutoConnectTimer_TickAsync>d__107.MoveNext(): No Sim running.
> Debug	05/27/2023 18:18:59	MobiFlightModule.KeepAliveNeeded(): Preventing entering EnergySaving mode: KeepAlive!
> Debug	05/27/2023 18:18:59	MobiFlightLedModule.Display(): Command: SetModule <1,0,1,000000,16,126;>.
> Debug	05/27/2023 18:18:59	MobiFlightLedModule.Display(): Command: SetModule <1,0,0,000000,16,126;>.
> ```
> After every Keepalive there should be a command sent to the MobiFlight Board, in this example it was the 7 segment display.

I have seen the messages in the log, but I don't know if they are from the board that has this issue. I will need to test with only the panel that has the offending 7 segment module.

**Comment by DocMoebiuz** [comment]
@JaimeLeon2 did you do the test with the one board only?

**Comment by DocMoebiuz** [comment]
i had this effect the other day too. I was just not able to reproduce it. But i know that I think that it has to do with it when you have more than one max chip daisy chained.
