### ISSUE TITLE
Clone Nano board time out error uploading firmware

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1202]
**Describe the bug**
Clone Nano boards having time out error when uploading firmware

**Steps To Reproduce**
1. Connect new Arduino Nano chinese clone with CH340 chip
2. Board is correctly recognized
3. Upload firmware selecting Nano type
4. Upload process appears to proceed then gets an error before completing
5. Note error is avrdude timed out

**Expected behavior**
Mobiflight uploads firmware normally

**Actual behavior**
Mobiflight reports error and does not complete upload.

**Details**
 - MobiFlight Version: 9.7,1
 - FlightSim: irrelevant
 - AddOn: irrelevant

**Additional context**
Board requires the "old bootloader" method that limits baud rate to 57600.
Mobiflight fails to upload at 115200 baud rate (avrdude gets no response) and times out at 57600.
Testing done showed increasing timeout parameter to 20000 in arduino_nano.board.json file allows enough time to complete the upload at the slower speed.

**Comment by JaimeLeon2** [comment]
Just to comment that updating the Nano bootloader solved this and allows the Nano to communicate at 115200 baud. I am aware reloading the arduino bootloader is outside the expertise of most regular users.

**Comment by neilenns** [comment]
I had no idea you could replace the nano bootloader with the new one!

**Comment by JaimeLeon2** [comment]
> I had no idea you could replace the nano bootloader with the new one!

Ralph gave me the idea and then did a bit of research. It is really not hard to do. Just another arduino to act as programmer and six jumper wires.

**Comment by elral** [comment]
Yes, "just" an ISP programer which gets recognized from the Arduini IDE and within the IDE choose flash bootloader.

**Comment by JaimeLeon2** [comment]
> Yes, "just" an ISP programer which gets recognized from the Arduini IDE and within the IDE choose flash bootloader.

I did this yesterday and after figuring the correct wiring, I was able to load the newer optiboot bootloader to the Nano. 

I did have to edit the boards config file in the arduino IDE to specify that the Nano old bootloader boards use the new bootloader file. This I understand was necessary so the IDE could communicate with the board still having the old bootloader to replace it with the new.

Just doing burn bootloader without editing the boards config file writes the old bootloader again as you need to specify you are connected to an old bootloader board.

**Comment by neilenns** [comment]
I changed the wrong timeout value 🤦‍♂️

**Comment by neilenns** [comment]
Never mind.
