### ISSUE TITLE
Boards are not recognized properly as MobiFlight boards

### ISSUE THREAD

**Issue by DocMoebiuz** [MobiFlight/MobiFlight-Connector#1205]
**Describe the bug**
Users report that during startup their boards are not detected properly and show as Arduino boards without MobiFlight firmware. After a couple of restarts the boards might all show ok.

**Steps To Reproduce**
1. Start MobiFlight

**Expected behavior**
All MobiFlight boards are detected properly

**Actual behavior**
A firmware upload popup appears and proposes to upload the MobiFlight firmware

**Details**
 - MobiFlight Version: 9.6+

**Comment by JaimeLeon2** [comment]
Clone Nano boards are consistently not being recognized by MF 9.7.1.1. The firmware is uploaded OK and the boards work normally with their existing device config in eeprom until you restart Mobiflight and the pattern repeats.

**This does not happen in MF 9.7.1 or 9.7.0.**

**Comment by neilenns** [comment]
Mobiflight connection delay for the mega was increased to 1750 in this PR: https://github.com/MobiFlight/MobiFlight-Connector/issues/1225

Timeout value for the Nano was increased to 20000 in this PR: https://github.com/MobiFlight/MobiFlight-Connector/pull/1211

I believe that was everything required to address this issue with Nanos using genuine CH340s.

**Comment by DocMoebiuz** [comment]
I don't remember if this was only in regard to the Nano or also Mega. In general, we had been seeing more user reports about unstable board detection regardless of the CH340 issue.

I will nevertheless close this now based on the comment by @neilenns

**Comment by Gamma36** [comment]
FYI: Same problem on some UNOs, 9.7.1 ok.
https://discord.com/channels/608690978081210392/1124830581008633969/1127649222523617380
