### ISSUE TITLE
Negative number in "Substring from" makes MobiflightConnector crash

### ISSUE THREAD

**Issue by maltelammel** [MobiFlight/MobiFlight-Connector#1220]
**Describe the bug**
Mobiflight Connect software crashs to desktop, when einterin negative number in "Substring from" - field.

**Steps To Reproduce**
From "Output configs", open the "ConfigWizard" dialog. In "More Options" > "Substing fro", enter -3 and 5. Press "Ok" button, and the software immediatly crashes. This happens also with other negative numbers in the "from" field.

**Expected behavior**
Either a proper error message should aprear, or (the btter solution) negativ numbers in the "from" field are handled as starting position counted right-to-left, from the end of the string.

**Actual behavior**
Message box "Unhandled exception". Mobiflight Connector software is closing.

**Details**
 - MobiFlight Version: 9.7.1
 - FlightSim: MSFS2020
 - AddOn: Fenix A320 Aircraft (perhaps aircraft not relevant)

**Comment by DocMoebiuz** [comment]
This should be fixed with https://github.com/MobiFlight/MobiFlight-Connector/pull/1281

**Comment by maltelammel** [comment]
Thank you. I will test and give Feedback.

 

 

Von: Sebastian M ***@***.***> 
Gesendet: Freitag, 8. September 2023 21:24
An: MobiFlight/MobiFlight-Connector ***@***.***>
Cc: maltelammel ***@***.***>; Author ***@***.***>
Betreff: Re: [MobiFlight/MobiFlight-Connector] Negative number in "Substring from" makes MobiflightConnector crash (Issue #1220)

 

This should be fixed with #1281 <https://github.com/MobiFlight/MobiFlight-Connector/pull/1281>

**Comment by DocMoebiuz** [comment]
It is fixed.
