### ISSUE TITLE
Arduino Nano support missing pins A6 and A7

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1222]
**Describe the bug**
A user recently reported that Nano board support is missing pins A6 and A7.

**Steps To Reproduce**
Open a new Nano board config.  
Try to assing pins A6 or A7.
Note they are not on the list.

**Expected behavior**
All available pins on supported boards should appear on the list of available pins.

**Actual behavior**
Pins A6 and A7 do not appear.

**Details**
 - MobiFlight Version: 9.7.1.1
 - FlightSim: irrelevant
 - AddOn: irrelevant

**Additional context**
Could this be as simple as adding the pins to the nano board json file?

**Comment by neilenns** [comment]
We'd have to change the firmware as well. The firmware has a maximum number of analog pins at 6. If A6 and A7 get added the max would be 8 (A0-A7).

**Comment by JaimeLeon2** [comment]
Pins A6 and A7 can only be used as analog input pins.  Still useful for potentiometers.

**Comment by DocMoebiuz** [comment]
@elral - can you please take a look at this one. I would say with dynamic devices we don't have this limitation on the firmware side anymore, and it's to be fixed now solely on the boards.json side.

**Comment by elral** [comment]
> @elral - can you please take a look at this one. I would say with dynamic devices we don't have this limitation on the firmware side anymore, and it's to be fixed now solely on the boards.json side.

Yes, that's true. The number of devices are now only limited by the board.json file.
This is a good example why we still need the max numbers of devices in the board.json file. OK, not for all devices, but for a couple one. Another limtation could be the processing time. Devices which take longer time for processing should still be limited.

**Comment by DocMoebiuz** [comment]
@neilenns what's the status here? You self-assigned it to you. It should not require a firmware change anymore, and the boards.json already has A6 and A7 listed. Max analog pins is 8.

From my vantage point this can be closed.

**Comment by DocMoebiuz** [comment]
Found it.

Implemented with #1236
