### ISSUE TITLE
Cleanup in Hubhop database requested

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1223]
**Describe the bug**
Event names for the MS ATR aircraft in Hubhop have different "terms" used for annunciators.  This is a request to bulk modify the Hubhop database as detailed below to uniform the event names.

**Steps To Reproduce**
See event names for the ATR aircraft annunciators.  Indicator, Annunciator and Light were all used.  We have agreed to uniform all annunciators with the term "ANNUN"

**Expected behavior**
Event names are more consistent by using the same terms.  See Additional Context below.

**Actual behavior**
Different users created events with different name labels using different terms for the same type of event.

**Details**
 - MobiFlight Version: Hubhop database
 - FlightSim: MSFS2020.
 - AddOn: 

**Additional context**
Requested in the Discord server.
Please bulk modify, for the ATR aircraft, event name label, all Outputs where it says "INDICATOR" to "ANNUN". 
Also, for the ATR aircraft, event name label, all Outputs where it says "ANNUNCIATOR" to "ANNUN"
This should affect about 90 events in the database.

**Comment by DocMoebiuz** [comment]
I can do the renaming, but I have to admit that I dislike these cryptic labels. Why not `annunciator` and why do we always have to use uppercase letters?

A label is a name that is displayed in the UI, it should be easy to read and should have a meaningful name that everyone understands.

**Comment by JaimeLeon2** [comment]
I would suggest issuing a clear standard for event names. Personally, I don't have a problem with abbreviations as long as they are used consistently. I dislike very long names on event names and annunciator is too long a word IMHO. What else could "Annun" mean? I think it is pretty clear.
In this particular case, three persons were working on ATR events and each person used different words for the same button leds.

**Comment by JaimeLeon2** [comment]
@DocMoebiuz Friendly reminder this request was never done.  It was supposed to be very easy, no?
I hope you are not waiting to resolve the naming standard issue.  That could take months, if not years, and what to do with the already 14,000 plus non-compliant event names in the database.

**Comment by DocMoebiuz** [comment]
I don't forget about these things, it was simply lack of time.

**Comment by DocMoebiuz** [comment]
I know you agreed on ANNUN, but I gotta say, it is at the end of the label and ANNUNCIATOR is clear to everyone not only hubhop experts

**Comment by DocMoebiuz** [comment]
In total it were 221 events
