### ISSUE TITLE
Increase analog input support in Pro Micro and Nano

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1228]
**Is your feature request related to a problem? Please describe.**
The Pro Micro and Nano boards have 9 and 8 analog capable pins respectively, but are limited in Mobiflight to only 5 and 6 analog inputs.  I propose to increase the Mobiflight limit to each board's true capacities.  

**Describe the solution you'd like**
Increase the number of analog inputs in Pro Micro to 9.
Increase the number of analog inputs in Nano to 8.

**Describe alternatives you've considered**
Only alternative is to use more boards.  This is not feasible in throttle quadrants where space is typically limited and use of many potentiometers is needed.

**Additional context**
It seems potentiometers are very pin efficient, just requiring one pin to function.  There are ways to use more analog input in rotary switches and groups of buttons, attaching resistors in series.

**Comment by DocMoebiuz** [comment]
@neilenns, @elral - can somebody take this one on?

**Comment by neilenns** [comment]
Not until next weekend at the earliest, sorry :(

**Comment by elral** [comment]
I can do it after I will be back tomorrow.
We have to consider the device buffer usage as AnalogIn has a high memory consumption.

**Comment by DocMoebiuz** [comment]
@neilenns i saw you added analog pins to the Pro Micro, I looked at the sparkfun pinout
![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/86157512/5cc7328b-a9d6-4200-b9cd-ad7ac95311d2)

And I was confused by the labels and the analog pins that they show compared what our JSON file has.

I always tried to name the labels for the pins the same as they are named on the board silkscreen.
Looks like we have a mistake in our json - the analog pins and pin numbers are not the same as on the pinout.
