### ISSUE TITLE
Not consistent data rate via serial to Arduino

### ISSUE THREAD

**Issue by GhencianTimotei** [MobiFlight/MobiFlight-Connector#1229]
**Describe the bug**
When using MobiFlight randomly the Arduino communication drops for some ms (some images from saleae are available bellow). When doing the capture the airplane was set to be climbing at a constant rate, in the UI the data seemed to be updating constantly and ok, but on arduino side, the rate is not consistent. The capture was done using the TX and RX pins from arduino.

In MobiFlight I have configured 4 stepper motors, 1 servo motor and 1 encoder. An external power supply is used for the Arduino Mega. If I use the test feature from Mobiflight and set 1000 steps for eg, the movement is continuous and smooth, clearly indicated that the problem is not on Arduino side

Used Arduino: Mega with CH340G

I used latest mobiflight release, also compiled on my own, same behaviour...
I uploaded the firmware using mobiflight, also compiled and and download on my own, same behaviour...

**Steps To Reproduce**
1. Import Mobiflight configuration for Arduino
2. import Mobiflight configuration
3. Start plane in a continuous and monotonic move
4. Verify serial rate

**Expected behavior**
Data to be sent every 50ms.

**Actual behavior**
When the mobiflight app is continuously sending data to Arduino, the rate is not constant, even if the data from MSFS and Mobiflight is constantly changing. The rate jumps from 1.5ms to 600ms or more.

**Details**
 - MobiFlight Version: 9.7.1/ latest
 - FlightSim: MSFS2020
 - Board: Arduino Mega with CH340G

**Additional context**
<img width="1447" alt="image" src="https://github.com/MobiFlight/MobiFlight-Connector/assets/74396814/0a193744-29ab-4f98-9a0a-2173cb511cf1">
<img width="696" alt="image" src="https://github.com/MobiFlight/MobiFlight-Connector/assets/74396814/5d4118ca-f5fb-48de-ae1f-6a29ca63bd01">
[Saleale Log.zip](https://github.com/MobiFlight/MobiFlight-Connector/files/11568942/Saleale.Log.zip)
![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/74396814/1f49e107-f23e-4be1-99d4-a558b14a19aa)
![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/74396814/46b47eed-6c4e-4f3e-8893-2ab5eac8d9b4)
![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/74396814/8e0404a9-e4bb-4e4f-896a-031d1b2be4d9)
[Configuration.zip](https://github.com/MobiFlight/MobiFlight-Connector/files/11568947/Configuration.zip)

**Comment by DocMoebiuz** [comment]
What driver version are you using?

**Comment by GhencianTimotei** [comment]
v3.8.2023.2

![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/74396814/269c4498-1883-46c3-b80a-7533fe462fa5)

**Comment by GhencianTimotei** [comment]
Seems like the USB Serial driver was the problem here... I used the one listed in Sparkfun's tutorial for CH340 IC and it worked like a charm.

https://learn.sparkfun.com/tutorials/how-to-install-ch340-drivers/all

Thanks @DocMoebiuz for the support!

**Comment by DocMoebiuz** [comment]
It's a known issue at the moment with the new driver. I would expect they provide a fix soon.

@GhencianTimotei - can you post a picture how it looks in salale with the old driver?

@elral - interesting observations by  @GhencianTimotei

**Comment by elral** [comment]
Yes, indeed. This is very interesting, I wouldn't have expected such a behaviour once the driver is running.

**Comment by DocMoebiuz** [comment]
@GhencianTimotei does your board has a CH340 chip on it that is not labeled?
