### ISSUE TITLE
When is the blink function going to be supported by the UI?

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1230]
**Is your feature request related to a problem? Please describe.**
The new "Blink" function was announced nine months ago as being available, but sadly, it remains as an obscure undocumented feature.
Having to manually edit the mcc file to use it just ensures that no one will use it.  Too difficult.

**Describe the solution you'd like**
Provide support for the Blink function in the Mobiflight UI for output configs.

**Describe alternatives you've considered**
Until now creating blink leds can only be done with the simulation time variable.

**Additional context**
Can also be used to create timer variables within Mobiflight.

**Comment by CaptainBobSim** [comment]
I'd love something like Blink(hz)
For example, Blink(1) for once a second Blink(2) for twice a second.

For beginners hz (times per second) is more intuitive than using milliseconds [ie Blink(1000) for every second]

**Comment by JaimeLeon2** [comment]
> I'd love something like Blink(hz)
> For example, Blink(1) for once a second Blink(2) for twice a second.
> 
> For beginners hz (times per second) is more intuitive than using milliseconds [ie Blink(1000) for every second]
> If we use milliseconds other places in mobiflight it would be better to keep it in milliseconds

I think there is a bit more to blinking than just specifying frequency.  We need to be able to specify time on and time off like the current undocumented function does allow. 

Not all blinking has equal time on and off. Best example I can think of is strobe lights that go something like 100 ms on, 200 ms off, 100 ms on, 800 ms off (two quick flashes, then long pause). Kudos to Sebastian for having thought of all this flexibility beforehand.

**Comment by CaptainBobSim** [comment]
That's true!
That'd be really cool to say Blink(500, 200, 100, 800...)

**Comment by JaimeLeon2** [comment]
> That's true! That'd be really cool to say Blink(500, 200, 100, 800...)

You actually can for the past 9 months do just that, but you need to edit the mcc file because there is no UI to that feature.

**Comment by DocMoebiuz** [comment]
I created this feature request issue #1249
