### ISSUE TITLE
Code boxes readability can be improved with use of a monospace font

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1231]
**Is your feature request related to a problem? Please describe.**
Currently Mobiflight displays RPN code in the code boxes using the regular proportionally spaced font.  The code is very hard to clearly read, especially with the spaces being so critical in RPN.

**Describe the solution you'd like**
Use of a monospace font like Courier would improve the readability of the code.

**Describe alternatives you've considered**
There is no way to adjust font type or spacing. 

**Additional context**
In some letter combinations, it is very hard to tell whether there is a space or not in between the characters.

**Comment by davidbuckleyni** [comment]
Am long sited and what I find would greatly enhance is some font sizes that work best like how iphone does it.
Small
Large
Larger
Largest 

Etc that way you keep to a know set that would not hinder the overall ui.
