### ISSUE TITLE
Reading Array Value from X-Plane 11 DataRef 

### ISSUE THREAD

**Issue by DJake-P** [MobiFlight/MobiFlight-Connector#1232]
Hello everyone
 
Is there a way to read an array value from X-Plane DataRef in MobiFlight? For example, the g430_nav_com_sel is an array for both the 530 and 430 in the C172 (i.e. [0,0]). The first value is for COM/NAV1 and the second is for COM/NAV2. Is there a way to transform this array into binary to read from X-Plane. I haven't had any luck with me guessing in the transform box. Thanks in advance!

**Comment by DocMoebiuz** [comment]
it should work by /my/data/ref[1]

I never tried /my/data/ref[1][2]

**Comment by DJake-P** [comment]
@DocMoebiuz, That was it! Thanks. I didn't know I could specify the dataref array.
