### ISSUE TITLE
Use keyboard keys for stepper calibration 

### ISSUE THREAD

**Issue by DocMoebiuz** [MobiFlight/MobiFlight-Connector#1242]
**Is your feature request related to a problem? Please describe.**
When calibrating stepper zero position with Mobiflight you have to use the mouse to move the stepper and select amount of steps.

This requires that you can look at the screen, use the mouse and see the gauge - all at the same time.

**Describe the solution you'd like**
Being able to control the stepper steps and moving the stepper by using the keyboard.

Eg. arrow keys up and down increase/decrease amount of steps slider - and arrow keys left right make the stepper move.

**Additional context**
Brought up on discord: https://discord.com/channels/608690978081210392/1117639821326819369

**Comment by CaptainBobSim** [comment]
Maybe Enter could set it in place?

**Comment by DocMoebiuz** [comment]
Implemented by #1292
