### ISSUE TITLE
New modifier logic available in UI

### ISSUE THREAD

**Issue by DocMoebiuz** [MobiFlight/MobiFlight-Connector#1249]
**Is your feature request related to a problem? Please describe.**
We restructured the way we deal with "transform", "compare" and "interpolation", including a new hidden modifier that allows for "blink"

We now need this new functionality accessible through the UI.

**Describe the solution you'd like**
* Instead of the compare tab we will have a modifiers tab
* Modifiers can be added and removed
* You can add the same modifier multiple times
* Modifiers will be executed in the order that is displayed
* The order of modifiers can be changed
* Modifiers can be inactivated
* Each modifier output is displayed to the user for easy debugging

**Describe alternatives you've considered**
none.

**Additional context**
#909

**Comment by JaimeLeon2** [comment]
It would be very good if you could provide the blink modifier with a soft switch.  In other words, be able to turn blink on and off like a LED in Mobiflight, based on the value of a config reference or MF variable.  I can't remember if you had that already in the blink UI.  Not providing a soft switch would force us to have duplicate configs and control blink with precondition. 
This way, blink can be added to chain of modifiers but turned on, only if the conditions are met for the trigger variable.
