### ISSUE TITLE
Update WASM module to 0.7.1

### ISSUE THREAD

**Issue by Koseng** [MobiFlight/MobiFlight-Connector#1269]
**Is your feature request related to a problem? Please describe.**
New WASM Module version is include with the latest MobiFlight Connector Release

**Describe the solution you'd like**
New WASM Module version is include with the latest MobiFlight Connector Release

**Additional context**
[Version 0.7.1](https://github.com/MobiFlight/MobiFlight-WASM-Module/releases/tag/0.7.1)

**Comment by cpuwolf** [comment]
Good idea
