### ISSUE TITLE
Stepper device config auto-zero input activate box

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1270]
**Is your feature request related to a problem? Please describe.**
I find it odd that the stepper device config has the Auto-Zero Input checkbox for "None", in other words, you have to uncheck to activate the Auto-Zero Input function.  Totally counter intuitive for me.

![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/86563553/86f73d4c-3670-4825-94e3-d63e3f10dab6)

**Describe the solution you'd like**
Please invert the logic and have the checkbox say "Activate" instead with default state unchecked.  So the user checks the box when he wants to use the function.

**Describe alternatives you've considered**
No alternative.  Live with the counter-intuitive UI.

**Additional context**
None

**Comment by DocMoebiuz** [comment]
I will leave this for now.
