### ISSUE TITLE
Info on limits on the number of configurable devices supplied by the module

### ISSUE THREAD

**Issue by GioCC** [MobiFlight/MobiFlight-Connector#1272]
**Is your feature request related to a problem? Please describe.**
The maximum number of configurable devices in the connector, for each device type, is currently stored in the boards' `.json` file.
These limits are only there so the connector knows them and can enforce in the GUI the corresponding hard limits existing in the firmware (where they are determined by available data structures).

It would be definitely an advantage if the Connector could obtain this information directly from the firmware; this way, data would be always automatically correct, and there would be a lesser chance of a mismatch (it would also be easier to maintain the configuration files).

**Describe the solution you'd like**
Add a request message from the connector whereby the firmware would return the number of configurable devices for every managed device type.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by DocMoebiuz** [comment]
With the removal of the limitation on the firmware side, this now is only defined and limited by the boards.json

I will close this issue.
