### ISSUE TITLE
Board configurations can only be uploaded to compatible boards

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#1282]
**Is your feature request related to a problem? Please describe.**
We can save our MobiFlight board configurations. However, at the moment it doesn't contain a hint for what board type it should be used. We can open a config that was created for a Mega, and upload that config to a ProMicro. Since they differ significantly in pins and capabilties, a user should be informed about this incompatibility and an upload should not be possible (without explicit confirmation) 

**Describe the solution you'd like**
The UI informs the user that the loaded config is not compatible with the current board type.
We can store the board type as an additional information in the config easily.

**Describe alternatives you've considered**
https://github.com/MobiFlight/MobiFlight-Connector/issues/1271 - it uses the serial number as an indication for the board type - Rejected, because we have already a proper way to determine what type a board is (when it contains MF firmware)

**Comment by DocMoebiuz** [comment]
implemented by #1530
