### ISSUE TITLE
Pressing "stop" in test mode won't resume sim data in new modifier UI

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#1286]
Testing #1281 and noticed that as the Test button stops the sim data during the test, stopping the test does not resume the sim data flow until you close the ConfigWizard.

**Comment by DocMoebiuz** [comment]
This is actually on purpose. because you might want to fiddle around with it a bit more and adjust the test values.
I thought it would make sense if it was staying in the proper "Off".

Iam open to feedback on this.

**Comment by tigert** [comment]
Yeah, I am actually coming to the same conclusion myself - though it might perhaps be better if this was more obvious as to how it works.

I think we earlier thought that MF should "pause" while you have a configwizard open, so that nothing interferes with the test functions, maybe it still makes sense that you can type in whatever value you want for test, but if you want to see real sim data again, you should close the configwizard?

I wonder if having a `[x] Use simulator data for testing ` would be too crazy just make it even more confusing? :)

**Comment by tigert** [comment]
Then again, it might also be useful to display live sim data as a test case, but I fear it might also become too complicated if we can do everything everywhere.

**Comment by DocMoebiuz** [comment]
not so much as a test case... but maybe simply inside the wizard available all the time... like the raw preset value

**Comment by DocMoebiuz** [comment]
Closing this. If we do it, then the feature would be "seeing the current sim value based on preset"
