### ISSUE TITLE
Test mode "result" column has trouble with long decimals

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#1287]
Testing the #1281 - the "Result" value in Test does not handle long decimal numbers well:

![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/2587818/b838cf76-0552-4466-93b5-a256e4347db6)

**Comment by tigert** [comment]
Also has those quotes, not sure if that is intentional?

![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/2587818/b5bc68d7-eb04-4dab-9cc3-93ac5cce6bb8)

**Comment by DocMoebiuz** [comment]
quotes are on purpose to see spaces

**Comment by DocMoebiuz** [comment]
for long values i can use "ellipsis"

**Comment by tigert** [comment]
Good point on quotes. 

Ellipsis looks nicer, and I guess we could show the whole value in a tooltip in case it needs to be ellipsized, so you can also see it if you need to.

**Comment by tigert** [comment]
I mean it could be a string for a 40x2 lcd that is 40 characters long for example? Like, if you wanted to do a rudder trim display that has a |...:....:....:....v....:....:....:....| - sure it might not be possible right now, but maybe with substrings and references etc you can do that.

Of course test shows it in the actual display too, but maybe the tooltip is a reasonable plan B to provide a way to see a longer value.
