### ISSUE TITLE
New modifier ui writes a file that crashes Connector if you delete all modifiers

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#1289]
So testing #1281 again

The modifier list has a default transform, but if you delete it, and save the file, it ends up writing a single-liner block of modifiers:

`<modifiers />`

however loading this file back crashes the new Connector with the modifier UI, current beta is fine as it likely just ignores the modifiers section in the config.

When you edit the file yourself and convert the above block to

```
        <modifiers>
        </modifiers>
```
it opens without crashing.

**Comment by tigert** [comment]
Ok, I keep getting these a lot.

Looks like if you add a new line, but don't open ConfigWizard, it writes the entry without <modifiers> block at all, and it works.

If you open ConfigWizard, it does write the <modifiers /> on a single line and that causes the unresponsiveness of the app and you need to kill it. 

Editing the XML by hand to change it to

```
  <modifiers>
  </modifiers>
```
avoids the problem. Or if you add at least one modifier in the list before saving the file.

**Comment by simontrhodes** [comment]
Can confirm the bug if you save a new config without going into the modifiers tab.
<modifiers /> is written to the config file.

The program gets stuck in an infinite loop.
There is no exit from a Do While loop at of ModifierList.cs

Entry into ModifierList.cs is from
Line 182 of OutputConfigItem.cs
```c#
if (reader.LocalName == "modifiers")
            {
                Modifiers.ReadXml(reader);
            } 
```

ModifierList.cs Do loop starts at line 78 and completes at line 120
```c#
} while (reader.LocalName != "modifiers");
``` 
Running this code shows a warning.
The name 'reader' does not exist in the current context.

**Comment by DocMoebiuz** [comment]
Thanks!

I have this bug fixed already but not created a PR yet.
