### ISSUE TITLE
Device config for button and led are almost identical

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1290]
**Is your feature request related to a problem? Please describe.**
The UI for the device config of buttons and leds has no way of differentiating one from another.  Only the icon in the device list can tell whether it is a button or a led, and both icons also look too similar.

**Describe the solution you'd like**
Just clearly mark the Button UI as "Button" and Output/LED as "Output"

**Describe alternatives you've considered**
None.

**Additional context**
The two UIs without a distinguishing label or mark are identical.  The icons are too similar.
User in the Discord support forum showed what he did and we couldn't tell if it is an input or an output.
We had to refer to our own MF installation to see more clearly the icons in order to be able to tell an input from an output device config.
This can be confusing even to support people.

**Comment by tigert** [comment]
Yeah, the device name of course defaults to "Button N" and "Output N", but you might still name them similarly and it might make sense to show the device type in the settings area title.

**Comment by DocMoebiuz** [comment]
Hey @tigert, we have #434  - as i said : we should add color coding to it and simplify the shapes of the icons - basically you are using shape and letters.

Maybe you could rework the icons one more time?

I will close this issue in favor of #434
