### ISSUE TITLE
Let's default to Inputs tab open for the very first use of MobiFlight

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#1293]
I would think the first thing a new user would want to do, is to add a switch to do something. 

I noticed when testing a PR (that I think loads blank new settings as its a new version number) that it opens with Outputs active. Maybe we should default to Inputs active by default?

**Comment by DocMoebiuz** [comment]
Hm. I don't know. Once you have watched the Getting Started Tutorial, you should know. 

It is legacy probably, that output tab is default. But it was always the differentiating point to other solutions. Outputs are the strength of MobiFlight.
