### ISSUE TITLE
GitHub CI should make smarter filenames for zips

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#1294]
So I find the automatic zip creation super useful for testing PR's, but there are two things that bug me and / or would be helpful to change slightly.

- The zip file is wrapped inside another zip file, which is a bit strange and tedious to unpack

- The zip contains a folder path with some kind of an ID ("MobiFlightConnector-0.0.0-482" for example) - it would be nicer if that was the pull request number, in case you are testing a few different PR's at the same time. 

This would make it easier to delete old test builds when you can see the pull request number in the folder names.

We likely need to have some kind of an id on the zip and folder name, to differentiate between updated zips in the same pull request in case the PR branch gets more commits, but we could still have the id in the end - like maybe MobiFlightConnector-PR#1242-001 or something like that where the number increments.
 
So ideally we could have something like MobiFlightConnector-PR1234-001.zip that you could just right click -> Extract all, and it would default to:

C:\Downloads\MobiFlight-Testing\MobiFlightConnector-PR1234-001\

.. so you could just replace C:\Downloads\ with D:\ for example and have all test zips unpacked neatly in one folder you can clean up easily when needed.

**Comment by neilenns** [comment]
Notes to myself:

The action should set a github env variable to the pull request number like the firmware build does:

```yaml
env:
  PR_NUMBER: ${{ github.event.number }}
```

The `release.bat` file should update to take another command line parameter which is used to set `VERSION`. If it isn't specified the existing logic to read the version from checked in files should be used.

The pr action should update to pass the pr number as the version to the build script.

The pr action should update to only attach the exact file, not a wildcard path to the file.

**Comment by neilenns** [comment]
Can't auto-increment the revision but can do the hash for the commit that triggered it:

https://github.com/TiagoGouvea/github-actions-test/blob/master/.github/workflows/env-new.yml

**Comment by neilenns** [comment]
This didn't require any changes to the release.bat file. It was already pulling the version from assemblyinfo.cs, and the github action was already writing the version to that file. Just had to update the way the version was constructed.
