### ISSUE TITLE
Add missing VID/PID for Arduino Mega 2560 REV3 [A000067]

### ISSUE THREAD

**Issue by chrisgeorge0911** [MobiFlight/MobiFlight-Connector#1315]
I have a board that is not detected, please add it to MobiFlight with this information

**Provide the VID / PID combination**
Check the device manager for this information
VID: 2341
PID: 0042

or entire ID:
VID....&PID.....

**Provide type of board**
- [X] Arduino Mega 2560
- [ ] Arduino Pro Micro
- [ ] Arduino Uno

Arduino Mega 2560 REV3 [A000067]

**Comment by neilenns** [comment]
@chrisgeorge0911 Have you tested that the board works properly when you manually add that vid/pid combination to the `arduino_mega.board.json` file?

**Comment by chrisgeorge0911** [comment]
Yep, board works fine - I was using it last night

**Comment by neilenns** [comment]
Thanks! I've updated the file and opened a pull request. Until that releases just keep using your locally modified file.

**Comment by DocMoebiuz** [comment]
this vid pid combo is already included in the json file, it has to be some other issue

**Comment by neilenns** [comment]
I should have looked closer 🤦‍♂️ It's been in the file for two years, it was one of the original ones when we switched to board.json files.

**Comment by chrisgeorge0911** [comment]
oh crap, sorry about that, I would have laid money on it not being there, but indeed it is!  Sorry to waste your time.
