### ISSUE TITLE
Errors when using new linked airplane config feature

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1336]
**Describe the bug**
When testing the new linked configuration feature errors consistently occurred:

DataGrid Error
![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/86563553/80beab17-28b4-4a7d-8200-f826b3eba5a7)

Exception Error
![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/86563553/2f1f5bc6-c0df-4051-bbfd-e246861593f8)

Mobiflight main window
![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/86563553/031f4486-78bb-4ad7-884c-b41bc5b685c9)

**Steps To Reproduce**
1. Open Mobiflight beta 9.7.1.3
2. Start flight in MSFS2020
3. Open the aircraft mcc file in Mobiflight
4. Link aircraft loaded to current mcc.
5. Save mcc
6. Restart Mobiflight
7. Error occurs when at the end of loading the linked file.
8. Error continues happening with every restart.

**Expected behavior**
Linked config file is loaded uneventfully and works.

**Actual behavior**
DataGrid, Exception Error and blank Mobiflight screen.  Only course of action is to close Mobiflght.

**Details**
 - MobiFlight Version: BETA 9.7.1.3
 - FlightSim: MSFS2020
 - AddOn: PMDG 737 and ASobo CJ4

**Additional context**
If done early enough while loading, unticking the "Auto-Load linked configuration" option appears to allow Mobiflight to work without using the new feature.  As shown in the screenshots below, after unticking the option, Mobiflight appears to have lost the linked file information.  Note the menu does not show the  Open linked config option.

![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/86563553/0bbee885-3c6e-46df-9c14-ee5bbe94b4d0)

**Comment by DocMoebiuz** [comment]
please add your config file here for testing. Thanks.

**Comment by JaimeLeon2** [comment]
Some more quirks observed today related to this new feature:

Upon first starting Mobiflight, it will apparently not recognize there is a link already made.  In this case, I made a link to the Cessna C172 classic aircraft mcc on the previous run.  I loaded a different mcc file before exiting and restarted Mobiflight.

![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/86563553/21aaec84-38af-42c6-8539-2d85b4b83e6a)

The "Open linked config" option in the menu is not active.

If I then load another mcc file, then Mobiflight loads the new file, but it now remembers that there is a linked config to the airplane in the sim.

![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/86563553/8e695023-8331-4bd0-9991-b1b5ea070552)

**Comment by DocMoebiuz** [comment]
When you are experiencing the problem, MobiFlight was stopped? Or Running? AutoRun is disabled, and it is also stopped. Not sure if that is because of the error.

**Comment by DocMoebiuz** [comment]
The first issue might have been fixed with #1341

**Comment by JaimeLeon2** [comment]
> When you are experiencing the problem, MobiFlight was stopped? Or Running? AutoRun is disabled, and it is also stopped. Not sure if that is because of the error.

Mobiflight is Stopped. I never use Autorun.

**Comment by JaimeLeon2** [comment]
nstalled 9.7.1.4
The errors upon auto loading a linked config are now gone.  Great!!!
However, if Auto-load is not active, and a different mcc file is loaded, on start of Mobiflight, the load linked configuration is not active.  If I then load another mcc file, then the load linked configuration is now active.

this is upon first start of Mobiflight with CJ4 loaded in the sim...

![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/86563553/176537bf-6751-4a6f-b2c4-7f2f4503ec41)

this is after loading another mcc file without exiting Mobiflight...

![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/86563553/a110eee9-0af0-47ab-84d8-f12a528895bd)

The CJ4 has the linked configuration, but this info is ignored upon first starting up Mobiflight.

**Comment by DocMoebiuz** [comment]
ok. Thanks for the feedback, i might have not considered this case correctly.

**Comment by DocMoebiuz** [comment]
Both issues are fixed now by
https://github.com/MobiFlight/MobiFlight-Connector/pull/1341
https://github.com/MobiFlight/MobiFlight-Connector/pull/1347
