### ISSUE TITLE
7 segment displays don't work with beta 9.7.1.3

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1338]
New 7 segment displays defined in the desktop app do not work with the beta 9.7.1.3. Displays configured with prior versions of the desktop app do.

From the Discord discussion:

> looks like the config written in the device by stable MF is : 4.2.4.3.15.1.LedModule:; <- this works
and the latest beta writes it as new type, likely due to the TM segments support: 16.1.2.4.3.15.1.LedModule: <- this does not work

**Comment by elral** [comment]
In the connector `public const string MODEL_TYPE_MAX72xx = "1";`

In the FW `TYPE_MAX72XX = 0,`
