### ISSUE TITLE
Auto load linked config loads mcc without checking for unsaved configs

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1349]
**Describe the bug**
The new auto-load linked config will auto-load the config disregarding if there are unsaved changes in the currently loaded mcc.

**Steps To Reproduce**
1. Create an auto-load linked config with the same aircraft in MSFS2020.
2. Load a different aircraft in the sim
3. Load a different mcc in Mobiflight
4. Insert a new output config in Mobiflight
5. Without saving the file, exit the aircraft in the sim and load the first aircraft for which the linked config exists in Mobiflight.
6. Note Mobiflight loads the linked config and the unsaved config was lost.

**Expected behavior**
If Mobiflight has unsaved changes, it should always ask before exiting or loading a different config.

**Actual behavior**
Load of linked mcc file happens, losing the unsaved configs.

**Details**
 - MobiFlight Version: 9.7.1.4
 - FlightSim: MSFS2020
 - AddOn: used Fenix A320, FBW A320, Cj4, Inibuilds A310
 
**Additional context**
The load linked config option in the dropdown menu will also load the mcc without asking.

**Comment by DocMoebiuz** [comment]
Good point.
