### ISSUE TITLE
Display time stamp for events database

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1363]
**Is your feature request related to a problem? Please describe.**
When Mobiflight updates events, there is no way of telling the events database currently available or how old it is.

**Describe the solution you'd like**
Display a time stamp representing the snapshot time of the database currently installed.  It could be displayed in Extras - Hubhop update option.  I think this will probably require the time stamp to be stored in Hubhop and updated every time a change in the database is accepted.

**Describe alternatives you've considered**
No alternative currently exists, and there is no way of telling how old the current database installed is.

**Additional context**
Not knowing the database age is an issue compounded by the fact that Mobiflight installation installs a very old database file.  I think most users are unaware of this and assume that installing Mobiflight also installs an updated set of events.  The reality is the contrary of that.

**Comment by tigert** [comment]
I think the root of the problem is that the install / upgrade of a new version installs the hubhob events db that can be even older than what you had prior to the upgrade.

I think the simplest solution is like what is done with the WASM module: just prompt to install it when you update MobiFlight. Either by asking the user, or just doing it, because hubhop is such an integrated part of the software now.

**Comment by DocMoebiuz** [comment]
Based on what @JaimeLeon2 is describing, we have the date when the event was last updated. So we could even show it for every preset. We could then also check online if there is a new version of this particular one available.

I think starting with the timestamp of the database (e.g. download time) is a start which might be useful when supporting users. But then again, is it not more valuable to know what version or timestamp the individual preset has?

**Comment by DocMoebiuz** [comment]
linked to #1280 

i just noticed that in my comment before I was more going along with the idea as descirbed in #1280

**Comment by DocMoebiuz** [comment]
<img width="760" alt="image" src="https://github.com/MobiFlight/MobiFlight-Connector/assets/86157512/2547efac-dc7d-46c1-9aca-9c1f718582ab">


<img width="192" alt="image" src="https://github.com/MobiFlight/MobiFlight-Connector/assets/86157512/c4472522-d942-4480-a2cf-c5e17270f524">

**Comment by JaimeLeon2** [comment]
My idea was for Hubhop to manage a "last change time stamp" which is sent with every database update request as a sort of database version number, that could be used to:
1. Show in MF Connector the database "version" installed (not necessarily the download date), which can also indicate how old the version is.
3. In Hubhop, it can be used to decide that there is no need to re-download the database file kept in the browser cache.  In particular, downloading the database with every page refresh, as currently done, seems like a big waste of time and bandwidth, IMO.  Particularly annoying for those of us that are 7000 miles away from the server.

**Comment by DocMoebiuz** [comment]
we can improve that logic later down the road. the local date of your database is currently displayed. It will help us during support and in a first iteration we remind the user to update every 7 days

**Comment by JaimeLeon2** [comment]
Not in Mobiflight, unless you know you want the very latest update that was made, which is often the case when supporting people and making missing events in Hubhop, on request from someone.

When working in Hubhop, you do want to have the very latest database.  Problem is that Hubhop updates the database with or without any changes made.
