### ISSUE TITLE
Support analog input via potentiometers

### ISSUE THREAD

**Issue by Mobiflight** [Mobiflight/MobiFlight-Connector#138]
Confirmations:
- [x] Analog Input can be added as new device type in settings
- [x] Analog Input can be selected in Input Configuration
- [x] Settings for sensitivity and pin are stored correctly on the board
- [x] Analog input value can be used in Input Actions - possible via "@"-reference 
- [x] Documentation added (https://github.com/Mobiflight/MobiFlight-Connector/wiki/Input-and-Output-devices#analog-inputs)

**Comment by ssewell** [comment]
See #406 for recommendations on how to potentially recover your Pro Micro, if you encountered an issue when attempting to update your firmware.

**Comment by Mobiflight** [comment]
A new input type "Analog input" has been added to MobiFlight.
