### ISSUE TITLE
MobiFlightCache.cs has a bunch of code correctness warnings

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1387]
The work in #1364 added a bunch of new code that has code correctness warnings in Visual Studio. None of them affect the functionality but we should clean them up.

**Comment by neilenns** [comment]
A lot of these warnings pre-date the work in #1364 to be fair. But we should clean the stuff up, there's a bunch of unused variables for example.

**Comment by DocMoebiuz** [comment]
Are you considering `warnings` and `messages` he same?

**Comment by neilenns** [comment]
Sorry, I just mean "messages". Not warnings.
