### ISSUE TITLE
Add a warning for counterfeit CH340 chips

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1410]
Right now when people have board connection issues due to counterfeit CH340 chips the only way for us to find out is to ask them to send photos of the boards.

We should log an error when a counterfeit board is detected so we can just have users give us logs instead of photos.

**Comment by jonas-koeritz** [comment]
Sorry to necromance this issue but I believe the check needs some updating. I've just fixed a long standing bug I had that resulted in my Mega2560 boards not working but the warning didn't show up in the logs. I had a quick look at the code and it checks for the USB devices name, which didn't match my boards so the warning didn't show up. Maybe this should borrow the checks from the "FakeCH340DriverFixer" that's also referenced in the MobiFlight docs. No need to do the driver install part, just make the check a little more robust.
In my opinion it doesn't hurt to have a user possibly check for this issue when looking for the source of an error, worst outcome is having to ignore a warning.

**Comment by neilenns** [comment]
> Sorry to necromance this issue but I believe the check needs some updating. I've just fixed a long standing bug I had that resulted in my Mega2560 boards not working but the warning didn't show up in the logs. I had a quick look at the code and it checks for the USB devices name, which didn't match my boards so the warning didn't show up. Maybe this should borrow the checks from the "FakeCH340DriverFixer" that's also referenced in the MobiFlight docs. No need to do the driver install part, just make the check a little more robust. In my opinion it doesn't hurt to have a user possibly check for this issue when looking for the source of an error, worst outcome is having to ignore a warning.

We're using the same check as FakeCH340DriverFixer. Can you start a thread in the #hardware channel in Discord so we can work through what your board was reporting?

**Comment by jonas-koeritz** [comment]
Maybe I just read the logic in the MF code backwards then 🤔, I'll double check.

Just a quick rant: Please don't rely so much on discord for any software projects. It's not archived properly, not searchable without being inside the discord walled garden and excludes people who don't want to use that platform (yes I see the irony of writing this on GitHub).
