### ISSUE TITLE
Crash when customdevices connected but no json present

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#1423]
So I was testing MF from git, and it crashed on me when the GNC255 is connected.

```
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=MFConnector
  StackTrace:
   at MobiFlight.MobiFlightModule.GetConnectedDevicesStatistics() in D:\MSFS-git\MobiFlight-Connector\MobiFlight\MobiFlightModule.cs:line 1086
```

I think it is because on this instance I did not have the GNC255 board and device JSON files under Devices\ and Boards\ 

It should probably just ignore the unknown device if there is no type known. or show it as unknown.

**Comment by neilenns** [comment]
@tigert are you still able to reproduce this? If so, can you make it happen and paste the entire callstack in?

**Comment by neilenns** [comment]
Never mind, I know what the cause is.
