### ISSUE TITLE
BETA: OnHold and OnLongRelease forget settings on InputShifters

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#1445]
**Describe the bug**
When setting events for OnHold or OnLongRelease, the settings work, but if you go back to the configwizard, the events are empty. They work if they are configured on a regular button input 

**Steps To Reproduce**
1. Go to Inputs tab
2. Add a new configuration item and select a device that is part of an input shifter
3. Set sim events for "On Hold" and "On Long Release"
4. Close configwizard dialog
5. Open the config wizard again

**Expected behavior**
Should remember all settings

**Actual behavior**
Seems that the event settings for On Hold and On Long Release are not being saved when closing
the dialog with "OK".

**Details**
 - MobiFlight Version: 9.7.1.10
 - FlightSim: not relevant
 - AddOn: not relevant

**Comment by DocMoebiuz** [comment]
same for inputmultiplexer
