### ISSUE TITLE
Outdated firmware on Pro Micro is only detected on first Pro Micro

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1446]
**Describe the bug**
After updating MF 9.7.1.10, new firmware is offered.  The upload ends in error for the Pro Micro boards.  Mobiflight Modules only shows the yellow warning marker on the first Pro Micro board (there were two). No warning flag on the second Pro Micro even though the firmware was outdated as well.

**Steps To Reproduce**
1. Start Mobiflight with two or more outdated Pro Micros
2. Mobiflight detects the outdated boards and gives option to upload firmware.
3. Press Ok.  Mobiflight proceeds to upload firmware.
4. Note operation ends with error for Pro Micro boards.
5. Go to Mobiflight Modules
6. See yellow warning mark is shown for the first Pro Micro board, but none for the second.
7. Check that both boards have the same outdated firmware.
8. Firmware can be uploaded to both boards individually.

**Expected behavior**
Outdated firmware yellow marker is shown for all affected boards

**Actual behavior**
Yellow marker is only shown on the first board.

**Details**
 - MobiFlight Version: beta 9.7.1.10
 - FlightSim: irrelevant
 - AddOn: irrelevant

**Additional context**
none

**Comment by DocMoebiuz** [comment]
linked with #1149

**Comment by DocMoebiuz** [comment]
I will close this as being part of #1149 - the parallel update confuses the UI at the moment. It will be gone, once we have solved 1149.
