### ISSUE TITLE
Unable to save changes to 7 segment display output config

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1481]
**Describe the bug**
Certain output configs are unable to save after editing 7 segment display config.

**Steps To Reproduce**
1. Open the attached .mmc file
2. Edit the `OH DC Amps` output 
3. Set the module to one you have connected that has 7 segment displays on it
4. Change the number of digits from 3 to 8
5. Hit ok

**Expected behavior**
Dialog closes and changes are applied

**Actual behavior**
Nothing happens. Dialog doesn't close.

**Details**
 - MobiFlight Version: 10.0

**Additional context**
In the output window of the debugger you see this:

```
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
Exception thrown: 'MobiFlight.ArcazeCommandExecutionException' in MFConnector.exe
```

[Found via Discord](https://discord.com/channels/608690978081210392/1183487663324528661)

[flightsim1.zip](https://github.com/MobiFlight/MobiFlight-Connector/files/13629513/flightsim1.zip)

**Comment by neilenns** [comment]
I was able to reproduce this locally with the attached .mcc file but don't understand this part of the code well enough to figure out what's going on. The user reports the same issue happens with `OH DC Volts` and `OH DC AMPS`, but they were able to save other LED outputs so it's not a general issue. It's something specific about those three.

**Comment by neilenns** [comment]
Update: The user deleted those three lines and re-created them and the error went away. Very strange. What is it about the three lines in the attached file that doesn't work!?

**Comment by DocMoebiuz** [comment]
This serial is interesting 
<img width="295" alt="image" src="https://github.com/MobiFlight/MobiFlight-Connector/assets/86157512/a6f2ace4-4354-42d4-a9a9-13db4ffecc11">

**Comment by DocMoebiuz** [comment]
<img width="500" alt="image" src="https://github.com/MobiFlight/MobiFlight-Connector/assets/86157512/14cf84c9-1686-403b-8b33-42e4e5e608e8">

This is the reason. The interpolation apparently supported floats in the past.

The interpolation settings are strange though.

**Comment by elral** [comment]
> This serial is interesting 
> 
> ![image](https://private-user-images.githubusercontent.com/86157512/290602513-a6f2ace4-4354-42d4-a9a9-13db4ffecc11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzcxMzksIm5iZiI6MTcwMjU3NjgzOSwicGF0aCI6Ii84NjE1NzUxMi8yOTA2MDI1MTMtYTZmMmFjZTQtNDM1NC00MmQ0LWE5YTktMTNkYjRmZmVjYzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE4MDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNDg4NzI2MmE1MmY1NWE4YmZmZGI0YTFiYWM2MjZiYWYwZDNkYjU4OTk3Yjc3MDBlMGM3Njg4ZDEyMDIzYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mwySB61ZiEX9iVclsGX7Yaxnoqk4i9tYNe09PjYGMFI)

It's twice interesting.

First the special characters after `754-` and second the attached board name, espacially that the board name is **before** the serial number stored in the EEPROM.
