### ISSUE TITLE
when closing the program it ask me to save then happen the error can t save no acces to file ???

### ISSUE THREAD

**Issue by freeslider2012** [MobiFlight/MobiFlight-Connector#1482]
**Describe the bug**

**Steps To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what you actually happens.

**Details**
 - MobiFlight Version: [e.g. 8.2.0]
 - FlightSim: [e.g. MSFS2020]
 - AddOn: [e.g. Default Aircraft]

**Additional context**

**Comment by neilenns** [comment]
@freeslider2012 This bug report doesn't contain any actionable information. Please provide all the information requested in the issue template, or start a thread in Discord for assistance.

**Comment by DocMoebiuz** [comment]
No more feedback from user. Closing this.
