### ISSUE TITLE
Unknown custom device ui polish

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#1504]
**Is your feature request related to a problem? Please describe.**
When you have a custom device that is not known to MobiFLight, the settings under MobiFlight Modules
is just a blank panel. This could be a bit nicer.

**Describe the solution you'd like**
Explain why this is not showing anything to configure, and point the user towards a solution to fix the issue.

**Describe alternatives you've considered**
Alternatively we could have something like a config store where each custom device has an ID and MobiFlight can pull the files for the device automatically when a new yet-unknown device is seen.

Obviously this is a bit more involved alternative :-)

**Additional context**
It could look like this:

![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/2587818/1bb54e78-2970-40dc-869c-8f64c43f9eeb)

**Comment by elral** [comment]
How did you get a custom device into a FW which is not supporting such a custom device?
If using only the connector for flashing the firmware and uploading the config this should not be possible.
The only way I can think about is flashing a custom firmware, uploading a custom device and then uploading another firmware outside of the connector (e.g. PlatformIO).

**Comment by tigert** [comment]
Excellent point. I guess there are two scenarios.

- Either you received a pre-configured Arduino from someone who built a panel for you
- Or you accidentally uploaded a .mfmc file that has a custom device, into an arduino
  that has default MobiFlight firmware.

**Comment by tigert** [comment]
After discussing with @neilenns and thinking, maybe do this if it starts to be a problem in support channels, once more custom devices appear, until then it is very edge case.
