### ISSUE TITLE
Need a Hubhop database fix for Honda Jet

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1515]
**Describe the bug**
There are two sets of events for the Honda Jet under two different labels in Hubhop.  Please integrate all under one label.

**Steps To Reproduce**
Search Hubhop for aircraft
Note there is one label "HA420" and another label "HJET HA420"

**Expected behavior**
All events for Honda Jet are under the label "HJET HA420"

**Actual behavior**
Database contains two labels for the same aircraft.

**Details**
 - MobiFlight Version: [e.g. 8.2.0]
 - FlightSim: [e.g. MSFS2020]
 - AddOn: [e.g. Default Aircraft]

**Additional context**
Database operation on aircraft field, where it says "HA420" , change to "HJET HA420"
It should affect some 80 events.

**Comment by DocMoebiuz** [comment]
@JaimeLeon2 we have a property called "label" which is displayed in the drop-down for the preset.
We have a property "aircraft" which is the name for the aircraft.

I think you are referring to updating the "aircraft" property and not the label.

**Comment by DocMoebiuz** [comment]
```
db.getCollection("presets").updateMany(
    {"aircraft" : "HA420" },
    { "$set" : { 
        "aircraft" : "HondaJet HA420"
    }}
)
```

**Comment by DocMoebiuz** [comment]
it will take some time to show on HubHop, or try a private window, or delete your local session storage.

**Comment by JaimeLeon2** [comment]
OK, no objection to "Honda Jet". HJET is the acronym used in the Sim.
Wouldn't the same operation be required for the events with HJET HA420 as their aircraft category?

**Comment by DocMoebiuz** [comment]
i did the renaming for the other names too
