### ISSUE TITLE
Add settings to disable joystick and midi support

### ISSUE THREAD

**Issue by Koseng** [MobiFlight/MobiFlight-Connector#1516]
**Is your feature request related to a problem? Please describe.**
- If midi devices are used by other applications, and not mobiflight, it is a good idea to deactivate midi support completely. Current situation in windows is, only one application can have an open communication channel to a midi device.
- If for whatever reasons a problem in context with joystick or midi support appears, there should be the possibility to completely deactivate joystick or midi support until a fix can be provided.

**Describe the solution you'd like**
Have a setting in settings dialog to deactivate joystick support and another one to deactivate midi support.

**Comment by neilenns** [comment]
Do we really need a setting to disable joysticks? Has there ever been a user situation where we've needed that?

**Comment by DocMoebiuz** [comment]
Great question! I think: Yes we do. Especially, for individual joysticks it makes sense. They might clutter the UI.

**Comment by neilenns** [comment]
Another user posted in Discord about the MIDI conflict: https://discord.com/channels/608690978081210392/1187840556819304551. Further justification for getting this feature done :)

**Comment by Koseng** [comment]
Great support Neil! 
And in a galaxy far away maybe we will reach the point that multiple applications can access midi devices at the same time. Microsoft already redid the MIDI api once with UWP and failed. Buggy and not very usable.

Now there is the new MIDI 2.0 standard and Microsoft is working again on a new midi implementation which will support MIDI 2.0 as well. Also they promised multi app access.

We will see... And which windows versions will support it....

**Comment by flyingpaul1980** [comment]
I have the same problem. I installed Mobiflight to use my new miniFCU with the Fenix A320 and so far it's working great.
Nevertheless, I have a problem: Once i plug in my X-Touch mini Midi Device (which i normally use via AAO), i get pop-up hints about the Midi Board of my external Soundcard and my X-touch mini EVERY SECOND. Mobiflight just spams my taskbar full and the only way to stop it is to quit mobiflight via the Task Manager.

I ONLY wanna use mobiflight for the MiniFCU now, it's highly problematic for me that it suddenly requires exclusive access to all midi devices or it will bombard me with error messages :/

![2023-12-23 23_10_37-_Fenix + miniFCU + MobiFlight _ Support_ _ MiniCockpit Community - Discord](https://github.com/MobiFlight/MobiFlight-Connector/assets/76615610/812f5d79-2c77-4c70-acf5-e824aef2ceb2)

**Comment by neilenns** [comment]
> I have the same problem. I installed Mobiflight to use my new miniFCU with the Fenix A320 and so far it's working great. Nevertheless, I have a problem: Once i plug in my X-Touch mini Midi Device (which i normally use via AAO), i get pop-up hints about the Midi Board of my external Soundcard and my X-touch mini EVERY SECOND. Mobiflight just spams my taskbar full and the only way to stop it is to quit mobiflight via the Task Manager.
> 
> I ONLY wanna use mobiflight for the MiniFCU now, it's highly problematic for me that it suddenly requires exclusive access to all midi devices or it will bombard me with error messages :/

I've opened a new issue to track this: https://github.com/MobiFlight/MobiFlight-Connector/issues/1526

**Comment by Koseng** [comment]
> I have the same problem. I installed Mobiflight to use my new miniFCU with the Fenix A320 and so far it's working great. Nevertheless, I have a problem: Once i plug in my X-Touch mini Midi Device (which i normally use via AAO), i get pop-up hints about the Midi Board of my external Soundcard and my X-touch mini EVERY SECOND. Mobiflight just spams my taskbar full and the only way to stop it is to quit mobiflight via the Task Manager.
> 
> I ONLY wanna use mobiflight for the MiniFCU now, it's highly problematic for me that it suddenly requires exclusive access to all midi devices or it will bombard me with error messages :/
> 
> ![2023-12-23 23_10_37-Fenix + miniFCU + MobiFlight _ Support _ MiniCockpit Community - Discord](https://private-user-images.githubusercontent.com/76615610/292646904-812f5d79-2c77-4c70-acf5-e824aef2ceb2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MDY0ODIsIm5iZiI6MTcwMzQwNjE4MiwicGF0aCI6Ii83NjYxNTYxMC8yOTI2NDY5MDQtODEyZjVkNzktMmM3Ny00YzcwLWFjZjUtZTgyNGFlZjJjZWIyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDA4MjMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZjA3YjE1ZWUxZGUyMmYyY2JlM2VkNGRkNzAzYjUyN2YyYzU1ODBiZjRiYzJmZWIzNGMwYjg1Y2NjNTE0ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dOCZv-NtgZG7KUoi9ntF_6oOghFeuTcxfqbxPWIgdo0)

Hi, intended behavior is to only have 1 warning at startup. On my system if I occupy the MIDI device with another application and start mobiflight afterwards, the warning shows up once.

Can you describe how to reproduce the issue of several popups? How to start what in which order? Thanks!

**Comment by Koseng** [comment]
Ok, I suppose I know how that behavior can be reproduced.

1) Start MobiFlight, with a first MIDI device already being attached.
2) Start another applications which likes to get MIDI devices - AAO
3) While both applications are running, attach second MIDI device (X-Touch mini) and other application AAO is faster in occupying the device than MobiFlight.
4) Now MobiFlights detects a new MIDI device, fails to access it, and detection runs in a loop.

Probably another way to reproduce:
- Start MobiFlight with 2 MIDI devices being attached and 1 already being occupied.

**Comment by Koseng** [comment]
@flyingpaul1980 until a new beta version is released, you also can try to use the dev build version in the PR:

Be aware that is a dev version. But there you have the Peripherals UI.
[MobiFlightConnector.zip](https://github.com/MobiFlight/MobiFlight-Connector/suites/19277029806/artifacts/1131846361)
- To download you need to be logged in to Github
- Extract the zip in the zip to a new folder. No installation process necessary.
- Start MFConnector.exe in the new folder.

**Comment by flyingpaul1980** [comment]
Wow, support on christmas, impressive, thanks! I guess I fall into the "2nd way to reproduce" category, even though the 2nd device - external soundcard midi-in - is not in use. At least i can trigger the error messages without even starting AAO, i just need to plug in the other device, in this case, the x-touch mini.

Thanks for the link to the beta, i'll try it asap and give you feedback.

until then, have a nice xmas time!

**Comment by JaimeLeon2** [comment]
what happens when a user has two MIDI devices and wants to use one in AAO and the other in Mobiflight?  Does he have to activate MIDI support in Mobiflight and the constant spamming that there is another MIDI device there that is not being used?

**Comment by neilenns** [comment]
> what happens when a user has two MIDI devices and wants to use one in AAO and the other in Mobiflight? Does he have to activate MIDI support in Mobiflight and endure the constant spamming that there is another MIDI device there that is not being used?

We have a separate bug open about the dialog popping up repeatedly.
