### ISSUE TITLE
Build process blindly copies everything in the Community folder, even if it isn't part of the project

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1519]
To reproduce:

1. Use Visual Studio's UI to include some custom board files under the Community folder of the MobiFlightConnector project
2. Do not set the `Copy to Output Directory` property
3. Build

Result: The files you added are copied to the output folder
Expected result: They shouldn't be copied since they were not set to copy to output

This happens because there's a wildcard ItemGroup in the project file:

```XML
  <ItemGroup>
    <Content Include="Community\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

I lost a good half an hour of my day trying to figure out why files were getting copied to the build folder when I wasn't expecting them to.

There's UI in Visual Studio specifically for managing files, we should be using that instead of magically blanket including the files via an ItemGroup that can only be managed by editing the .csproj file directly.

**Comment by neilenns** [comment]
Blanket including files is just dangerous. It's a way to get in trouble down the road where a file accidentally gets included in the build when you didn't expect it. A very very very long time ago I wrote a blog post about this for msbuild :) Be explicit in what you want included in your project for build purposes, don't rely on wildcards.

**Comment by DocMoebiuz** [comment]
i did this on purpose @neilenns i am tired of updating the files all the time - the files are all under version control, so its not blindly copied over. I want to do the same for the firmware files. it's a pain in the but to update this files in the visual studio solution every time

**Comment by neilenns** [comment]
Copying my comment over from the PR:

I know you did it on purpose but it's wrong. I lost so much time today because it was automatically copying files when I was trying to debug problems in a specific file without the others showing up.

Back when I worked on msbuild we never, ever, advocated customers use wildcards like this because of the future grief it will cause. The short term pain of having to use the VS UI is well worth it compared to the future anguish we will have.

**Comment by DocMoebiuz** [comment]
Very much disagree, then we have to find a different approach. I am totally sick of changing this on every update especially now with more custom boards.

Just keep your local folder clean if it bothers you.
