### ISSUE TITLE
"Auto Zero" Pin Increments when checking and unchecking the zero box

### ISSUE THREAD

**Issue by CaptainBobSim** [MobiFlight/MobiFlight-Connector#1525]
**Describe the bug**
"Auto Zero" Pin Increments when checking and unchecking the zero "none" box

**Steps To Reproduce**
1. Create a stepper
2. Uncheck the none box
3. check the none box
4. see the pins fade away, as if Thanos himself has snapped them
5. repeat 2-3 like a psychopath

**Expected behavior**
Pins would still be accessible, and the pin would not increment

**Actual behavior**
Pins are "reserved" and not able to be used.

![Animation](https://github.com/MobiFlight/MobiFlight-Connector/assets/76851401/865335b1-6108-460a-8692-58a39471def2)

**Details**
 - MobiFlight Version: 10.0.2
 - ARDUINO UNO (Could be a Uno specific issue as I remember they aren't as epic as the MEGAs?)

**Additional context**
Happens both when stepper is not flashed yet and when stepper is flashed and editing.

**Comment by DocMoebiuz** [comment]
@CaptainBobSim - can you check with an older version whether that was like this before too? e.g. with 9.7.1 - that would be very helpful

**Comment by DocMoebiuz** [comment]
I checked with 9.7.1 and this was not the case

**Comment by DocMoebiuz** [comment]
@CaptainBobSim please try https://github.com/MobiFlight/MobiFlight-Connector/pull/1529 and confirm there that it is working

**Comment by CaptainBobSim** [comment]
That fixed it, thank you @DocMoebiuz !!
