### ISSUE TITLE
In-use MIDI devices shouldn't warn the user every second

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1526]
From a comment in #1516 by a user:

> I have the same problem. I installed Mobiflight to use my new miniFCU with the Fenix A320 and so far it's working great.
Nevertheless, I have a problem: Once i plug in my X-Touch mini Midi Device (which i normally use via AAO), i get pop-up hints about the Midi Board of my external Soundcard and my X-touch mini EVERY SECOND. Mobiflight just spams my taskbar full and the only way to stop it is to quit mobiflight via the Task Manager.

> I ONLY wanna use mobiflight for the MiniFCU now, it's highly problematic for me that it suddenly requires exclusive access to all midi devices or it will bombard me with error messages :/

We should warn once, maybe, and then never again?

**Comment by Koseng** [comment]
Ok, I suppose I know how that behavior can be reproduced. You need at least 2 MIDI devices and 1 one of those being occupied by another application.

Start MobiFlight, with a first MIDI device already being attached and not being occupied.
Start another applications which likes to get MIDI devices - AAO
While both applications are running, attach second MIDI device (X-Touch mini) and other application AAO is faster in occupying the device than MobiFlight.
Now MobiFlights detects a new MIDI device, fails to access it, and detection runs in a loop.
Probably another way to reproduce:

Start MobiFlight with 2 MIDI devices being attached and 1 already being occupied.

**Comment by JaimeLeon2** [comment]
I think in this case, AAO being faster than Mobiflight to grab the MIDI device is irrelevant, because the user wants to use the MIDI device with AAO, not Mobiflight.

**Comment by DocMoebiuz** [comment]
You can now deactivate support for midi devices, see #1516
