### ISSUE TITLE
Remember grid view column widths across app launches

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1533]
**Is your feature request related to a problem? Please describe.**
It's possible to resize the column widths on the Outputs and Inputs tab, but those widths aren't persisted across app launch. When you get them sized the way you like you'll lose it when you quit Mobiflight then re-launch.

**Describe the solution you'd like**
Remember the column widths across app launch.

**Additional context**
[Requested by Glenn in Discord](https://discord.com/channels/608690978081210392/745361245808492584/1189360726964437062)

I asked ChatGPT and this is totally possible to do without too much effort.

**Comment by DocMoebiuz** [comment]
What's the motivation behind this?

What information is not displayed correctly and how does the resizing make it better?

How does the resizing work across different config? Will it require adjustment for specific configs or is it really working well once adjusted?

**Comment by neilenns** [comment]
> What's the motivation behind this?
> What information is not displayed correctly and how does the resizing make it better?

Here's an example from my Outputs tab:

<img width="261" alt="image" src="https://github.com/MobiFlight/MobiFlight-Connector/assets/9524118/69d8615c-60cd-4a16-b4c6-2a6c3558ea76">

With the default widths I can't see all the output information even though there's plenty of overall width in the app.

Here's examples from my Input tab, same issue:

<img width="210" alt="image" src="https://github.com/MobiFlight/MobiFlight-Connector/assets/9524118/bee0f3e3-b392-4b86-9fca-7a8b28aeebeb">

> How does the resizing work across different config? Will it require adjustment for specific configs or is it really working well once adjusted?

I was thinking the column widths could get stored in the config file directly, so each file maintains its own widths and just sets the columns correctly when opened. Maybe?
