### ISSUE TITLE
Mobi replaces the "@" symbol with "1" Possible Bug- Please Help!

### ISSUE THREAD

**Issue by myflightdeck1** [MobiFlight/MobiFlight-Connector#1534]
Jamie Leon asked me to post this bug:

I've been using Mobi since its inception and have closely followed its evolution with each new release. However, the latest update has presented an issue for me.

Here's my setup: I employ an analog potentiometer for controlling my flaps and utilize the CRJ700 from Aerosoft.

To accurately position the flaps along the motion spectrum, I have Mobi reading the analog signal and setting the value to a Lua script. In the Mobi config wizard, under the Display tab, I specify the "@" symbol to link it to the Lua script. I configure it as an Input Action > On Change > FSUIPC Lua Macro. I include the macro name and then add the "@" symbol to designate the value. However, upon saving this configuration, Mobi replaces the "@" symbol with "1". As a result, I'm unable to accurately capture the value required to set the interpolation for the flap motion range (e.g., 1-25 for Dent 1, 25-50 for Dent 2, and so forth).

Could you please verify on your end if the "@" symbol is indeed being saved in the config wizard when using the "On Change" input action for writing to a Lua script?

I hope this explanation is clear enough and not too confusing. Thank you for your assistance!

Best regards,
Aaron Werner (Myflightdeck)

**Comment by DocMoebiuz** [comment]
Thanks! It is fixed in #1535 and will be release soon.

**Comment by DocMoebiuz** [comment]
@myflightdeck1 try the linked PR and the zip file from there. Let me know if it works now.
