### ISSUE TITLE
Using letters yields odd results when using multiple compares referencing a string output

### ISSUE THREAD

**Issue by CaptainBobSim** [MobiFlight/MobiFlight-Connector#1545]
**Describe the bug**
Using letters yields odd results when using multiple compares

**Steps To Reproduce**
1. Create multiple compare rows, each showing a config reference
2. Create some config references with symbols (%,!, @ etc)
3. Create some with letters (F, V, C etc)
4. See string is read incorrectly - note if config row is not string value shows up correctly.
5. ![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/76851401/ab5b0702-e594-4ee5-90f0-0034682f0be8)

**Expected behavior**
Should yield "28V" as in the config reference but shows "282828V"

**Details**
 - MobiFlight Version: [BETA 1532.734]
 - FlightSim: [e.g. MSFS2020]
 - AddOn: [e.g. Default C172]

**Additional context**

**Comment by DocMoebiuz** [comment]
Please try with this PR https://github.com/MobiFlight/MobiFlight-Connector/pull/1539

**Comment by CaptainBobSim** [comment]
Unfortunately v1539.740 did not fix the issue

**Comment by DocMoebiuz** [comment]
You cannot use a placeholder that is part of the value, if you run it through multiple modifiers, the 'V' will get replaced accordingly.

**Comment by CaptainBobSim** [comment]
That makes sense - thank you for your help!!
