### ISSUE TITLE
A2A Cessna FSUIPC Offsets not working for ADF

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#160]
http://www.mobiflight.de/forum/message/3176.html

[Issue created by DocMoebiuz: 2016-12-13]
[Last updated on bitbucket: 2021-05-28]

[Comment created by DocMoebiuz: 2019-10-01]
These values are not available via FSUIPC.

**Comment by DocMoebiuz** [comment]
This can be solved via LUA Macro which requires a FSUIPC license.

It is not a MobiFlight limitation. I will close it. If we ever add native SimConnect Support for P3D then this might be doable without FSUIPC.
