### ISSUE TITLE
Loupedeck (Live) MIDI Encoders not working properly

### ISSUE THREAD

**Issue by marknl** [MobiFlight/MobiFlight-Connector#1611]
**Describe the bug**
The encoder(s) on a (as MIDI device configured) Loupedeck (Live) give inconsistent results in Mobiflight when rotating the dial.

**Steps To Reproduce**
1. Configure your Loupedeck (Live) as MIDI device and configure one of the encoders as a "MIDI Dial Adjustment", I used:

> 1 - Modulation Wheel or Lever / CC Set 
> Value: 0
> Channel: 1
> 

2. Open MobiFlight and make sure the MIDI Device "Loupedeck Live" is checked.
3. Enable Debug logging in MobiFlight.

**Expected behavior**
When I turn the dial clockwise I see a PRESS event. When I turn the dial counter clockwise, I see a RELEASE event.

**Actual behavior**
This happens when I do 1 clicks clockwise and 1 clicks counter clockwise:
```
Warn	01/18/2024 15:09:15	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => PRESS =>  No config found.
Warn	01/18/2024 15:09:16	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => RELEASE =>  No config found.
```

This happens when I do 2 clicks clockwise and 2 clicks counter clockwise:
```
Warn	01/18/2024 15:09:41	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => PRESS =>  No config found.
Warn	01/18/2024 15:09:41	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => PRESS =>  No config found.
Warn	01/18/2024 15:09:42	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => PRESS =>  No config found.
Warn	01/18/2024 15:09:42	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => RELEASE =>  No config found.
```
This happens when I do 5 clicks clockwise and 5 clicks counter clockwise:
```
Warn	01/18/2024 15:10:05	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => PRESS =>  No config found.
Warn	01/18/2024 15:10:05	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => PRESS =>  No config found.
Warn	01/18/2024 15:10:06	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => PRESS =>  No config found.
Warn	01/18/2024 15:10:06	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => PRESS =>  No config found.
Warn	01/18/2024 15:10:07	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => PRESS =>  No config found.
Warn	01/18/2024 15:10:07	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => PRESS =>  No config found.
Warn	01/18/2024 15:10:08	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => PRESS =>  No config found.
Warn	01/18/2024 15:10:08	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => PRESS =>  No config found.
Warn	01/18/2024 15:10:09	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => PRESS =>  No config found.
Warn	01/18/2024 15:10:09	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => RELEASE =>  No config found.
```
You can see where this is going.

This happens when I do 2 clicks **counter** clockwise and 2 clicks clockwise:
```
Warn	01/18/2024 15:10:56	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => RELEASE =>  No config found.
Warn	01/18/2024 15:10:56	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => RELEASE =>  No config found.
Warn	01/18/2024 15:10:57	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => PRESS =>  No config found.
Warn	01/18/2024 15:10:57	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => CC 1_1  => PRESS =>  No config found.
```

**Details**
 - MobiFlight Version: 10.1.0
 - FlightSim: MSFS2020
 - AddOn: -

**Additional context**
It looks like some internal counter is being used for clockwise clicks and Mobiflight only detects a "release" event after the same amount of "press" events have been "reverted" with a "release" event (counter clockwise) for it to actually occur.
I also don't know if it is a Loupedeck issue or MobiFlight. What I do know, is that the same configuration in the Loupedeck software works fine with Spad.next.

**Comment by Koseng** [comment]
Did you read the wiki page?
https://github.com/MobiFlight/MobiFlight-Connector/wiki/Midi-Boards

**Comment by marknl** [comment]
Since the Loupedeck works fine, except for the encoders, I figured it was already supported but might've been a bug.
I'll dive into that custom configuration, thanks.

**Comment by marknl** [comment]
1. Empty Loupedeck profile, one encoder configured: Channel 1, CC 1
2. MIDI Monitor shows:
```
Device Name: Loupedeck Live
CC: 1, Channel: 1 Value: 1
CC: 1, Channel: 1 Value: 2
CC: 1, Channel: 1 Value: 3
CC: 1, Channel: 1 Value: 2
CC: 1, Channel: 1 Value: 1
CC: 1, Channel: 1 Value: 0
```
4. I created a config file "loupedecklive.midiboard.json". It contains:
```
{
    "$schema": "./mfmidiboard.schema.json",
    "InstanceName": "Loupedeck Live",
    "EncoderNeutralPosition": 0,
    "Inputs": [
      {
        "Label": "Dial %",
        "LabelIds": [ "1" ],
        "InputType": "EndlessKnob",
        "MessageType": "CC",
        "MessageChannel": 1,
        "MessageIds": [ 1 ]
      }
    ],
    "Outputs": [ ]
  }
```
6. Doing the same 3 right, 3 left clicks on the dial in MobiFlight shows:
```
Warn	01/19/2024 12:32:50	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => Dial 1  => RIGHT =>  No config found.
Warn	01/19/2024 12:32:51	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => Dial 1  => RIGHT =>  No config found.
Warn	01/19/2024 12:32:51	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => Dial 1  => RIGHT_FAST =>  No config found.
Warn	01/19/2024 12:32:53	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => Dial 1  => RIGHT =>  No config found.
Warn	01/19/2024 12:32:53	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => Dial 1  => RIGHT =>  No config found.
Warn	01/19/2024 12:32:54	ExecutionManager.mobiFlightCache_OnButtonPressed(): Loupedeck Live => Dial 1  => LEFT =>  No config found.
```

**Comment by Koseng** [comment]
hi,
ok know it depends on, wether you can configure the knob/encoder to an endless mode in the loopdeck configuration. To check and monitor the output of the current configured mode in loopdeck you can use the midimonitor https://github.com/Koseng/SimpleMidiLib/releases.

For endless mode you configure the neutral position. On turning right the device must output a value greater than neutral, on turning left a value smaller than neutral.

Example Neutral 63.
- 64 (right) 
- 64 (right)
- 64 (right)
- 62 (left)
- 62 (left)
- 62 (left)

Example Neutral 0. (Since there are no negative values, 0-1 = 127)
- 1 (right) 
- 1 (right)
- 1 (right)
- 127 (left)
- 127 (left)
- 127 (left)

Your device needs to support such a mode for endless Knob.
If your device is also able to output values turning 0, 1, 2, 3....127, you can only use LimitedKnob.

**Comment by Koseng** [comment]
And in your standard setup at the moment, what does midi monitor show if you continue to turn left, what does happen after 0?
And when you continue to turn right, what does happen after 127?

**Comment by jph1ll1ps** [comment]
I can see how to use touch buttons on the Loupdeck to control actions and input configs.. BUT is there a way to also trigger the output config to change the effect on a touch button, like red to green? and pointers, reference materials?

**Comment by marknl** [comment]
Oh damn I never seem to have replied on Koseng. @Koseng It's been a while and I cannot remember if I tried your solution. I think it didn't work and got fed up with it. Eventually I sent the Loopdeck back and got a refund. Thanks for the provided information and possible solutions. Maybe this will still be of help for others running into this problem.
