### ISSUE TITLE
Support for ATC_MENU_OPEN / ATC_MENU_CLOSE

### ISSUE THREAD

**Issue by stelek77pl** [MobiFlight/MobiFlight-Connector#1673]
I'd like to be able to open and close the ATC window in MSFS using my custom buttons.
I found the events ATC_MENU_OPEN / ATC_MENU_CLOSE in the Microsoft documentation.
However I do no think those are supported by MobiFlight.
They do not show up in the Mobiflight UI.

Could we have them added, please?

https://docs.flightsimulator.com/html/Programming_Tools/Event_IDs/Aircraft_Instrumentation_Events.htm
![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/159721053/436a28bf-a0d2-4757-9efd-886f699cb793)

**Comment by tigert** [comment]
This is not related to MobiFlight connector itself, the simulator event presets are handled by [HubHop.mobiflight.com](https://hubhop.mobiflight.com/).

The presets do exist there though:
https://hubhop.mobiflight.com/

If you have more questions about this, please be welcomed to our Discord server (click the Discord link on the MobiFlight Connector toolbar) and post your question / issue to the MSFS2020 support channel there, we'll be happy to help you!

**Comment by stelek77pl** [comment]
Thank you for your reply. I'm not familiar with your code, but the values are clearly visible in one file and not in the other.
![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/159721053/a4357422-d9e2-415c-ab39-800ef2bfd76e)
If we added them to "Presets/msfs2020_eventids.cip", would they appear in the UI?

**Comment by tigert** [comment]
This is still not a mobiflight connector issue, but the problem actually seems to be that those key events do not appear to work in MSFS2020 at all.

The events do not seem to do anything when assigned to a button like other similar events that do work.
