### ISSUE TITLE
VKB Controller LED and Encoder support

### ISSUE THREAD

**Issue by cbrauers** [MobiFlight/MobiFlight-Connector#1789]
**Is your feature request related to a problem? Please describe.**
As discussed on Discord, a number of users would like to control the LEDs on their VKB devices with Mobiflight. Since VKB's LED API is more complex than the generic LED API introduced for Honeycomb devices, this requires a special implementation. A VKB-specific implementation also allows interfacing directly with rotary encoders, since DirectInput modes tend to slow down the encoders a lot.

**Describe the solution you'd like**
Introduce handling of VKB LEDs and encoders into MobiFlight.

**Describe alternatives you've considered**
I have written a C++ tool to interface with MSFS and VKB devices before, but with HIDSharp already a part of MobiFlight, it is more effective to implement the communication from scratch with the experiences gained during its development.

**Additional context**
I have been working on [an implementation](https://github.com/cbrauers/MobiFlight-Connector) over the past few weeks, currently doing some final polishing before creating a pull request. You can find [my branch](https://github.com/cbrauers/MobiFlight-Connector) (along with two [companion](https://github.com/cbrauers/VKB-Mobiflight-Definer) [tools](https://github.com/cbrauers/EncoderVisualizer)) on my GitHub profile.
With the modularity and customizability of VKB devices, it is not sufficient to include a handful of pre-made definitions. With just module combinations sold on the store or featured in official guides, we are already in the ballpark of about 40 different definitions, and user customization can increase that arbitrarily. I have therefore written a [tool](https://github.com/cbrauers/VKB-Mobiflight-Definer) to quickly create own definitions. Currently just essentially copying and pasting blocks together without in-depth JSON awareness, but it works for combinations that are not too heavily manipulated. The second [tool](https://github.com/cbrauers/EncoderVisualizer) is a testing tool for the encoder interface.
Protocol documentation from VKB is a bit sparse, but I have provided the most relevant pieces here:
[LEDs Protocol](https://github.com/user-attachments/files/15859047/LEDs_Protocol.pdf)
[Encoder capabilities](http://forum.vkb-sim.pro/viewtopic.php?f=28&t=7843#p61557)

**Comment by Koseng** [comment]
Implemented with #1792

**Comment by Wibbbs** [comment]
Sorry to revive a closed issue, but I would LOVE to be able to use the LEDs on my VKB joystick as outputs from mobiflight. Is there any documentation on how to set this up?

**Comment by cbrauers** [comment]
There is this wiki page: https://github.com/MobiFlight/MobiFlight-Connector/wiki/Using-VKB-controllers-with-MobiFlight
If you need any further helps, I am available on the MobiFlight and VKB Discord servers, as well as the VKB forum at http://forum.vkb-sim.pro/ and the /r/hotas subreddit.

**Comment by Wibbbs** [comment]
Fantastic, thanks for the reply. I will try this out in the next couple of days and find you in discord if any issues. I am already in the VkB discord as well.
