### ISSUE TITLE
Can not find source code

### ISSUE THREAD

**Issue by merspieler** [MobiFlight/MobiFlight-Connector#1850]
Hello,

I'm looking for the source code of https://github.com/MobiFlight/MobiFlight-Connector/blob/main/lib/MobiFlightWwFcu.dll
But can not find it anywhere.
Can you please point me to the source of it?
MobiFlight doesn't support my simulator but I would like to get the FCU working for it too and I need some pointers to figure out how it works

**Comment by neilenns** [comment]
The code is not available in GitHub. You can join the MobiFlight discord and ask for assistance in #development

**Comment by neilenns** [comment]
> I don't have discord cause I don't consent to their terms of service and piracy policy Is there a reason the code for the open source project isn't public (aka open)?

That specific DLL is a separate project and not currently open source.

**Comment by neilenns** [comment]
For information about the dll please start a thread in the #development channel in the official MobiFlight discord.
