### ISSUE TITLE
An encoder when spun fast then paused will hold on to it's next input.

### ISSUE THREAD

**Issue by hollowhemlock** [MobiFlight/MobiFlight-Connector#1854]
### Describe the bug
An encoder, when spun fast but not slow, will hold onto the next (Fast) increment. The (Fast) can be assigned or not. It's kind of intermittent.

_Note: I tried this without the mobiflight variable and directly updated MSFS. The behavior was the same. After turning the encoder fast in direction1, the first encoder turn in direction2 will produce a step in direction1 then begin direction2._

### Steps To Reproduce
Spin encoder fast. Rest described In expected behavior. Setup is in additional context.

### Expected behavior
Input: Turn Encoder Right Fast
Output: 100 105 110 115 120
Input: Turn Encoder Left Fast
Output: **115** 110 105 100 95
Input: Turn Encoder Right
Output: **100** 105 110 115 120

### Actual behavior
Input: Turn Encoder Right Fast
Output: 100 105 110 115 120
Input: Turn Encoder Left Fast
Output: **125** 120 115 110 105
Input: Turn Encoder Right
Output: **100** 105 110 115 120

### Details
 - MobiFlight Version: 10.4.0
 - FlightSim: most likely not applicable but MSFS 2020
 - AddOn: [e.g. Default Aircraft]
 - Arduino Uno

### Additional context
[MobiFlightSimpleEncoderInput.mcc.txt](https://github.com/user-attachments/files/17724778/MobiFlightSimpleEncoderInput.mcc.txt)

#### Input On Left
![image](https://github.com/user-attachments/assets/9112bcff-b9b9-4087-8128-b63cc888e82d)
#### Input On Right
![image](https://github.com/user-attachments/assets/c3eec45f-71d0-4587-84e9-bded4a65fb61)
#### Variable
![image](https://github.com/user-attachments/assets/3081fc2d-7b1b-4a84-8f62-11de22f78f51)

**Comment by elral** [comment]
It looks like you have configured the wrong encoder type. For one and two detents there two types which can be defined. Please change it to the other type (by keeping the detents) and test it again. It should work now like expected.

Please report your result.
