### ISSUE TITLE
VIDs/PIDs configure in external config-file (std-config included in installiation)

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#189]
User can add new Boards by itself.
CH340 Chip UNOs can set as UNO and not as MEGA by the user.

[Issue created by drome1800: 2017-04-04]
[Last updated on bitbucket: 2020-09-16]

[Comment created by DocMoebiuz: 2020-09-16]
I guess we are working on it right now… REBOOT!

[Comment created by ryucz: 2020-09-16]
@{557058:1c646c6b-f7d7-4548-b231-938050d2203a}  This should not be MINOR, this should  be MAJOR. Major above all. In next buid. In next hour. I just bought Arduino MEGA `VID_0403&PID_6001` it is mentioned many times in forums, even added in **MobiFlightModuleInfo.cs** @ 113, but i have tried 7.9 and 7.10 and none of them is looking for my board.

**Comment by MobiFlight-Admin** [comment]
@neilenns - very old story here :D 2017-04-04

**Comment by neilenns** [comment]
Well... I have a fix for this now 😂

**Comment by neilenns** [comment]
Well... I have a fix for this now 😂

**Comment by neilenns** [comment]
Discussion for how to address this is here: https://github.com/MobiFlight/MobiFlight-Connector/discussions/553

**Comment by MobiFlight-Admin** [comment]
@neilenns the i2c and PWM settings are swapped for the Mega
