### ISSUE TITLE
Request preset for Jeehell FMGS

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#197]
Presets with the Jeehell FMGS offsets will be welcomed as it would make implementing assignments on the flight deck more of a 'click and play' process.

http://www.jeehell.org/Offsets.pdf

Thank you,

Ben 
www.soarbywire.com

[Issue created by Soarbywire: 2018-05-30]
[Last updated on bitbucket: 2019-09-09]

[Comment created by DocMoebiuz: 2019-08-12]
same is true for other aircrafts like PMDG etc.

the mechanism is already built in. We only need somebody who creates the configs and stores it as mfc file which I can then add to the presets

**Comment by DocMoebiuz** [comment]
nobody volunteered to create the presets in the last 5 years.

I will close this.
