### ISSUE TITLE
Wrong Signed/Unsigned format in Jeehell Datapipe

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#198]
A user report a problem in Data Pipe  ( details here [LINK](https://www.mobiflight.com/forum/message/8787.html)

After research we find out that Indication Offset ( That is used to define $ for Datapipe) is wrong format.    Data of VS Speed can be PLUS and MINUS ... So it normaly must be SIGNED ... BUT Mobiflight read it Unsigned... So a value of -1 is shown in MF as 255 .
So finaly the OUTPUT Offset 73C7 AND the Datapipe function is "wrong" and need a additional IF Condition to recalculate the Signed value ... Like "if$>127 THEN"

***
I´m a bit confused here....  In Other cases we normaly get the problem that Mobiflight read a Value SIGNED ... Whatever in FSUIPC it´s Unsigned.
For example in Heading all over 180° is a negative Value in MF ...  Or Altitude of PMDG goes just to 32700 ft and all above is Negativ in MF.

Now it´s inverted.... Here the Raw value i think is Signed....  But Mobiflight now read it Unsigned ... WHY ??

[Issue created by Pizman: 2018-06-06]
[Last updated on bitbucket: 2019-12-01]

[Comment created by DocMoebiuz: 2019-12-01]
@{5b5d56f3c564683b7b904dba} Can we still reproduce this error or can we close this issue?

[Comment created by DocMoebiuz: 2019-10-01]
@{557058:823ea815-4ae8-47ab-835c-28328fd5562c} I reviewed the code and the offsets are read with signed integers as always. I don’t know why it is behaving so strange.

**Comment by DocMoebiuz** [comment]
Since a workaround for this, I will close this story!
