### ISSUE TITLE
Add a new tutorial Section for "Call LUA Macros"

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#203]
## Problem summary ##
Request for a Short Tutorial ( in kind of the other ones ... with Screenshots) for LUA PlugIn
Located in the Tutorial Subsection of Homepage

## Steps to reproduce ##
I recommend to just include the follow basic information of this Topic
[LINK  Mobiflight](https://www.mobiflight.com/forum/message/10232.html)

Not make a guide to script in LUA .... Not explane the function of all Lua Commands.
Just explane the Syntax,  Location of Files and maby the usage of start/Stop commands like /LUA and /LUAKill

## Expected result ##
Less Help requests in Forum :-)

Thanks !

[Issue created by Pizman: 2018-09-20]
[Last updated on bitbucket: 2020-08-18]

**Comment by DocMoebiuz** [comment]
This is not very relevant anymore
