### ISSUE TITLE
Different export Logic for 7Segment and LCD Values

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#206]
## Problem summary ##
Looks like Mobiflight got 2 "inverted" Logics when i use a 7Seg Output via MAX7219 -OR- a Output to a LCD Display 16x2
Details below...

## MF Version ##
7.5.2

## Steps to reproduce ##
* Create a Config that read a INT Value  For example Simply the COM1 Active Frequency Preset.
The Value Number is 5 characters Long ( For exampe 12345 for 123,45 mhz) 
* Define as Device a 7 Segment Display that is set on your Arduino.
* Use only FOUR Diggits in the Display Tab
* Create also a Config for a LCD   Device a LCD Display set on this Arduino
* Use as Placeholder 1 for example % and take the first Config you read Com1 Act.
* In Display GUI you define again only FOUR Characters like "TEST: %%%%" 

## Actual result ##
The 7 Segment Display try to show the 12345 but have 1 diggit less.
Result is a Number of 1234 on the Display ... The "5" is missing in case of missing space.
Looks like it will work from LEFT to RIGHT

The  LCD Display work inverted.
Here you will see 2345 (Here the leading 1 is missing in Case of missing space)
Looks like the LCD work from RIGHT to LEFT

*******
I think this is basicly no issue. Whatever it is strange cause we need here different workflows.
In Case we can use this "Bug" for some usefull things i will say this should not be reworked.

So... See this just as notification !
But maby this was not planed by yourself.... so you now be informed !

[Issue created by Pizman82: 2019-03-18]
[Last updated on bitbucket: 2019-10-07]

[Comment created by Pizman82: 2019-10-07]
UPDATE:

New Spot where this problem occures ….. [LINK](https://www.mobiflight.com/forum/message/14872.html) 

Same Situation…..   Placeholder with for example 6 Positions like “%%%%%%” is used….   Raw Value is 333 …..  In Sim Display it show “333\_ \_ \_” on LCD it show “\_ \_ \_333” 

Here the $\+100000 hint will not work….. Cause we need here no ZEROS to the Left….  We would need Spaces.

But finaly the older argument is the same….   This is just a optical problem…. NOT a functional.

‌

[Comment created by DocMoebiuz: 2019-09-08]
Hm. Good finding. I am not sure if I did this on purpose. I might have thought it would be more logical for the LCD that way. But we can change it. Probably not many people would be affected by the change.

**Comment by DocMoebiuz** [comment]
This can be addressed with the new padding modifier.
