### ISSUE TITLE
Left Padding Function in LCD Configs

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#207]
## Problem summary ##
Instead of 7 Segment Devices we have no "Left Padding " - Option in a LCD Config 

## MF Version ##
7.5.2

## Steps to reproduce ##
* Create a Output Config and use Preset "DATE- Seconds Local Time"
* Create a Outptu Config for a LCD Display.
* Use as Placeholder1 the First "Data Config" above... For example Symbol %
* Define in Display Field for Example " TEST: %%"

## Expected result ##
Seconds shown on Real Clocks like 00...01...02...03...04 

## Actual result ##
Without the Left Padding it is shown as 0...1....2....3...4.  ( Looks not good)

## Further details ##
Same Problem in Lots of other situations.
A Course of 87 Degrees is shown on Real Displays as 087 ...   Speeds also shown like 065 kt.
Left Padding is needed here in same situations like its used on 7 Seg Displays.
(Whatever we need no Left Padding-Space Option.... This is already included automaticly.)

## Improvisional Solution ##
As i reported in a other Issue #206 we can use a trick here.
A Value of 4 Characters length like 1234 is on LCD shown with only 3 Placeholders like %%% finaly as 234  ( The Leading Number(s) is/are terminated)

In this Situation a simple ADD Transform Helps.
In Example of SECONDS we Add 100 to the Value $+100
Now Raw Value is 0-59 ....   Calculated Value = 100-159
With only 2 Placeholders the Left "hundret Part" is not shown.... But Now a Number like 5 seconds is technical 105 ....  And Without "1"  the Display show correctly "01" 

This work for all Values....  You just need to ADD a Value so the Number increase by 1 Diggit.
For example Course got 3 Diggits...  So Add 1000 result in 1000-1359
ALT have 5 Diggits ... So Add 100.000 result in 100.000 - 145.000 for example.

## Summary ##
Maby you agree with me that the "improvisional Solution" is Still the final workflow.
But Maby you think already about a GUI Integration.

Here we will need a "Left Padding" Option for every Placeholder.
Maby a Checkbox Right of the "Choose Placeholder" Tab where we can already set Config, Symbol and so on.

Just think about, please !

[Issue created by Pizman82: 2019-03-18]
[Last updated on bitbucket: 2019-09-08]

**Comment by DocMoebiuz** [comment]
This can be done now with the new modifiers UI. See #1249
