### ISSUE TITLE
Let MobiFlight start even if there is a syntax issue with the config that gets automatically loaded during startup.

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#250]
Reported problem is that in some cases automatic loading of the config during start up fails and then MobiFlight doesn’t start either but quits. This lets the user get into a state where there is no way to fix it other than removing/renaming the config file.

‌

Steps to reproduce:

* Steps are currently unclear.

‌

[Issue created by DocMoebiuz: 2020-08-09]
[Last updated on bitbucket: 2020-08-15]

**Comment by DocMoebiuz** [comment]
@neilenns i believe you fixed this by adding a generic try catch last year.

**Comment by DocMoebiuz** [comment]
Should be fixed by https://github.com/MobiFlight/MobiFlight-Connector/commit/cf7556f3fbf6d27c71d137fda382ec0053f93f12
