### ISSUE TITLE
MobiFlight > Help > Open help in web does not link to correct page

### ISSUE THREAD

**Issue by Mobiflight** [Mobiflight/MobiFlight-Connector#281]
Currently the link from the menu takes you to an old website URL that doesn’t exist anymore.

It should link to the english documentation: [https://www.mobiflight.com/en/documentation/software.html](https://www.mobiflight.com/en/documentation/software.html)  
or German: [https://www.mobiflight.com/de/dokumentation/software.html](https://www.mobiflight.com/de/dokumentation/software.html)

**Comment by storeilly** [comment]
https://www.mobiflight.com/en/documentation/software.html appears to be broken also now.
