### ISSUE TITLE
Allow 69 devices with 16 characters each

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#287]
Currently the Mega2560 EEPROM limit does not allow to save a config where devices have 16 characters each and all 69 pins are used for devices.

[Issue created by DocMoebiuz: 2020-12-20]
[Last updated on bitbucket: 2021-02-13]

[Comment created by DocMoebiuz: 2021-02-13]
didnt work, reopened

[Comment created by DocMoebiuz: 2021-01-17]
fixed #287 - increased EEPROM area by 2 for storing longer configs. Adjusted max message size for micro to 32.

→ <<cset eb98ffbba3b4>>

[Comment created by DocMoebiuz: 2020-12-27]
currently the Mega2560 EEPROM limit does not allow to save a config where devices have 16 characters each and all 69 pins are used for devices.

**Comment by MobiFlight-Admin** [comment]
@elral if i roughly calculate 20 bytes per button / led and we have 69 pins, the it would require roundabout 1380 bytes of EEPROM, after your improvement of not duplicating the buffer, this can now be easily done for the Mega. Maybe even 1500 bytes.

**Comment by MobiFlight-Admin** [comment]
If I do the math for all boards

Bytes per Pin = type + "." + pin "." + name + ":" = 1 Byte + 1 Byte + 2 Bytes + 1 Byte + 16 Bytes + 1 Byte = 22

| Module | Max Pins | EEPROM | Required Length | Current Length |
| Mega | 68 | 4,096 | 1,496 | 1,024 | 
| Micro | 20 | 1,024 | 440 | 256 |
| Uno | 13 | 1024 | 286 | 256 |

**Comment by elral** [comment]
For the Mega we don not have any problem for now, doubling the max. config length should work.
But whatever we do, the promicro is short of memory, espacially thinking about naming additional devices. I will test if an increase of max. config length to 512 will work.

**Comment by GioCC** [comment]
Why not store shortened data?

type ->1 byte (might also leave some free bits for custom markers)
-> no separator
pin -> 1 byte
-> no separator
name -> 16 bytes
-> no separator

would easily yield 16-byte fixed-length records.
Pin number could even be left off (the record position would correspond to the pin no).

Possible improvements:
- if names are shorter, use variable-length records with a reserved value as record separator (eg 0xFF). (Pin no. would need to remain; access is slower; 1 byte overhead diminishes gain)
- If my proposal in discussion #577 is accepted (but even if it isn't, somehow the same requirement would probably arise anyway), two other bytes could be added for MPX channel and block pin.

**Comment by MobiFlight-Admin** [comment]
if we keep the separators it is straight forward in terms of handling messages that come through the cmdMessenger as well as the data that is kept in the EEPROM.

**Comment by GioCC** [comment]
True, but the messages would be unaltered, while the data in EEPROM are hardly ever seen except during debug and only handles by the read/write functions (and being fixed-length they would be fairly readable anyway).

**Comment by MobiFlight-Admin** [comment]
On every start, the board restores the configuration from the EEPROM and loads it with the exact same routine as when the config messages are coming from the Connector App.
I don't see a benefit of optimizing this when we have to sacrifice simplicity and consistency instead.

**Comment by GioCC** [comment]
@MobiFlight-Admin The benefit would be a non marginal gain in storage space.

The configuration upload procedure would not even be really affected; I don't really see a sacrifice either in simplicity or consistency.

With reference to the confguration processing steps I listed in discussion #594, __the encoding/decoding would be transparently embedded in steps 7, 2 and 4__; I see no complication or potential side effects in that. Even encoding and decoding would not be particularly complicated or demanding.
