### ISSUE TITLE
Arcaze Brightness Settings lost

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#290]
\## Problem summary ##

Brightness of LED Devices on a Arcaze LED-DRIVER 3 get lost after Save and Restart 

\## MF Version ##

7\.10.0   \( Not confirmed\)

\## Steps to reproduce ##

* Create a simple LED Device and change Brightness from MAX into a lower level

* Save.   Close MF and Restart

\## Expected result ##

LED Setting should be the same like set by the user.

\## Actual result ##

Brightness is back at FULL.    Whatever in the MCC file the correct “dimmed” Value is saved.

\## Further details ##

* Looks like simmular to the “missing Placeholder” “missing Interpolation Checkmark” and other Problems
* User confirmed in MCC file Settings are fine…. But MF LOAD them not correctly.

More detailed description about the issue

https://www.mobiflight.com/forum/message/21450.html

[Issue created by Pizman: 2020-12-28]
[Last updated on bitbucket: 2020-12-31]

**Comment by DocMoebiuz** [comment]
Closed due to inactivity.
