### ISSUE TITLE
Add Video Tutorial - Show how to configure "Landing Gear Indicator"

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#291]
It is a typical scenario.

Explain how to create the required configs and compare settings to achieve this.

[Issue created by DocMoebiuz: 2021-01-01]
[Last updated on bitbucket: 2021-02-23]

**Comment by DocMoebiuz** [comment]
https://www.youtube.com/watch?v=98sx64YF4h0&t=1s
