### ISSUE TITLE
GUI  Input Area of a LCD Config is to small for bigger Displays

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#302]
\## Problem summary ##

GUI Area for LCD Diplays is to small for a 40x4 Display

\## MF Version ##

7\.10.xx

\## Steps to reproduce ##

* Create a LCD Display as Device.   \( USer said up to 40x2 is possible in the Library and also in the MF alowed Settings

* Create a Config and check the INPUT Area we can insert the LCD Data….. Its not wide enough to show all 40 Positions   

\## Expected result ##

The GUI should support the upper limitation of the Firmware.

\## Further details ##

I would say a enlarge \(whatever imporvisional\)  should be done a.s.a.p. within the next hotfix/release.   Not care about good optics.  We can perfectly solve this with the planed GUI rework in the future.

Alternate:  If its not possible \( or not in your opinion\) then we should limit the LCD Size in Firmware a little smaller to fit the GUI current Maximum.

[Related Forum Topic](https://www.mobiflight.com/forum/message/21913.html)

[Issue created by Pizman: 2021-01-27]

**Comment by DocMoebiuz** [comment]
we don't support 40x4... LCDs can only have max 80 characters
