### ISSUE TITLE
Would be nice when updating multiple boards to not have to press "ok" between each board updating

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#312]
When there are multiple boards connected the update process requires that the user clicks OK after every successful (or not successful) update.

- [x] Multiple boards update process is initiated by user during start up
- [x] Multiple boards are update in one row without any user interaction
- [x] After a successful update a message is displayed 
- [x] After an unsuccessful update a message is displayed indicating which board had a problem
- [x] A single board can be updated from the Board Settings Menu
- [x] Localization if needed

**Comment by DocMoebiuz** [comment]
we noticed that a timeout can still occur when avrdude is not terminating and then the upload process would get stuck.
