### ISSUE TITLE
Placeholders can only be used in compare fields if the field also contains a $

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#318]
Right now the code checks for a $ and only then executes replacement of the value and runs it through the expression engine.

If we use placeholders other than $ nothing happens.

[Issue created by DocMoebiuz: 2021-02-26]
[Last updated on bitbucket: 2021-04-06]

**Comment by pizman** [comment]
PUSH.
This should be checked once again.
While my "Chrono Project" this bad element blocks me a lot of build the configs.
