### ISSUE TITLE
Parameters for MSFS2020 events possible?

### ISSUE THREAD

**Issue by Mobiflight** [Mobiflight/MobiFlight-Connector#326]
I wonder if it would be possible to add value as a parameter for the new \_INC and \_DEC msfs2020 events? So that you could have your heading bug increment with 10 degrees steps when you twist the rotary fast, for example?

[Issue created by tigert: 2021-03-14]
[Last updated on bitbucket: 2021-05-03]

[Comment created by tigert: 2021-04-04]
Yeah. But I mean, mobiflight has the fast modes for encoders that can have another event specified \(or a parameter\)

We did figure this out with the code notation of events though, as you can create separate events for “fast” inc and dec and then put the parameter in the event variables definition. Not super ideal but works.

[Comment created by DocMoebiuz: 2021-04-04]
In FSX the flight sim itself would take care of that… when many events come in a short amount of time, it would accelerate the turning of the knob.

**Comment by Mobiflight** [comment]
You can achieve this now with MSFS2020 - Custom Inputs, this was released in Version 9.0 https://github.com/Mobiflight/MobiFlight-Connector/issues/424

**Comment by MobiFlight-Admin** [comment]
@tigert - I closed this and I created a short explanation in the Wiki.

**Comment by MobiFlight-Admin** [comment]
https://github.com/MobiFlight/MobiFlight-Connector/wiki/MSFS2020-Using-the-Custom-Input-Code-Box
