### ISSUE TITLE
Create uninstall video

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#332]
[Issue created by DocMoebiuz: 2021-04-09]

**Comment by kkr0kk** [comment]
done, WIKI page

**Comment by kkr0kk** [comment]
I have ADD modules reset to factory default

**Comment by DocMoebiuz** [comment]
We have now also added an uninstaller. No video needed anymore.
https://github.com/MobiFlight/MobiFlight-Connector/wiki/MobiFlight-Connector-Uninstall
