### ISSUE TITLE
Config References don't get updated for inputActions until they get updated the next time

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#341]
[Issue created by DocMoebiuz: 2021-04-18]

**Comment by pizman** [comment]
UPDATE:
I think we can test this with you file from the "Tutorial Video for the XPDR"
Baldy you never show the situation in the Vid while your in the INPUT Tab,
If possible we can simply confirm this via Shared Screen
