### ISSUE TITLE
Support Joystick Buttons & Axis as MobiFlight Button

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#349]
MobiFlight provides a lot of flexibility for the inputs with preconditions, transformations and others. It would be useful to also be able to assign MobiFlight configurations to standard HID devices such as Joysticks and LeoBodnar Boards.

Confirmations:
- [x] Joysticks are listed as Devices in Input Configurations
- [x] Available Joystick buttons can be used like standard MobiFlight Buttons
- [x] Available Joystick axis can be used like standard MobiFlight Analog Inputs
- [x] Configuration is stored and loaded correctly
- [x] Joystick can be disconnected without MobiFlight crashing
- [x] Attached Joysticks are checked and compared with references in config when config is loaded and a warning message is displayed if they are not connected but used in the config (similar to the orphaned devices dialog)
- [x] Documentation is available - https://github.com/MobiFlight/MobiFlight-Connector/wiki/Joystick-Support
- [x] Automated tests are implemented  - there are no new test for config because we reuse everything
- [x] Add device type to feedback program

**Comment by Disorientator** [comment]
X52 Pro is not detected. HOTAS working fine otherwise/elsewhere. (shows up in control panel/devices and perfectly usable in MSFS)

Also tried running MobiFlight as admin, in case it had something to do with the library used/Windows permissions to read devices, but it did not solve the issue.

**Comment by rofl-er** [comment]
I second the issue. My X56 Stick is recognized but not the throttle.
