### ISSUE TITLE
Have a direct access to MobiFlight Board Settings

### ISSUE THREAD

**Issue by Mobiflight** [Mobiflight/MobiFlight-Connector#358]
## Problem summary

Settings menu is currently under Extras.  I suggest it would be very good to promote this menu to the first level because “Mobiflight Modules” is under Setting, is probably the most visited option and is buried under two levels of menus.

## MF Version

8\.1.4

## Steps to reproduce

1. Click Extras
2. Click Settings
3. Click Mobiflight Modules… It gets tiring after a while.

## Expected result

1. Click Settings
2. Click Mobiflight Modules :slight_smile: 

‌

[Issue created by jaime709: 2021-05-08]

**Comment by Mobiflight** [comment]
Instead of adding more menu items to the Main Menu, I decided to add a toolbar which is even faster than the original proposal.

feedback welcome.

**Comment by JaimeLeon2** [comment]
I agree your solution is better than my proposal. Thank you.
