### ISSUE TITLE
Include a new FAQ Entry "CH340 Boards Troubleshooting"

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#360]
Problem summary

Give the USer in the FAQ some informations to handle the CH340 Arduino Clones

‌

Expected result

If possible support a LINK to download the Drivers.  
Also inform the Users that these Boards not automaticly detected by Windows if you “just” install the Arduino IDE

‌

[Issue created by Pizman: 2021-05-09]
[Last updated on bitbucket: 2021-05-10]

[Comment created by kr0k: 2021-05-10]
my POV is manufacturer  need to distrib the driver, Mobiflight can’t detect if you have a specific board or not if the driver is not installed.

**Comment by kkr0kk** [comment]
Informations add to WIKI

**Comment by MobiFlight-Admin** [comment]
@kkr0kk - can you provide a link to the information that you added? I was able to find this link: https://github.com/MobiFlight/MobiFlight-Connector/wiki/FAQ - but the page was empty, so I added a link to the FAQ on the website.

**Comment by kkr0kk** [comment]
https://github.com/MobiFlight/MobiFlight-Connector/wiki/Modules

**Comment by MobiFlight-Admin** [comment]
Ah ok. I had also reworked the official documentation in the meantime. It contains also information for the FTDI based boards.

I will try and bring the website information back into the community wiki, but not sure what the best way is to keep it in sync. Next time I will think of it right away
