### ISSUE TITLE
Missing VID/PID for Sparkfun Pro Micro

### ISSUE THREAD

**Issue by pizman** [Mobiflight/MobiFlight-Connector#388]
[https://www.mobiflight.com/forum/topic/6659.html](url)

Please include VID/PID 
" VID 1B4F ; PID 9204"

Currently used for ProMicro.....
` public static readonly String[] VIDPID_MICRO = {
            "VID_1B4F&PID_9206",
            "VID_2341&PID_8036",  // Arduino Pro Micro
            "VID_2341&PID_8037"   // https://bitbucket.org/mobiflight/mobiflightfc/issues/324/add-new-micro-pro-vid_2341-pid_8037`

**Comment by Mobiflight** [comment]
We won't add the PID/VID because it is the 3.3V / 8MHz version.
