### ISSUE TITLE
Mobiflight cannot send new input events, unless restart is done

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#396]
**Describe the bug**
When testing a new wasm input event, the sim does not receive the event from MF, until a restart on MF is done.

**Steps To Reproduce**
1. Create a new non-existing event name in events.user.txt
2. Put event name in msfs2020_eventids_user_cip
3. Create input config using new event name
4. Run "touch" batch file to cause msfs to reload the wasm module.
5. After sim returns from reload of wasm, press Stop and Run in MF
6. Try new event

**Expected behavior**
Sim should execute the script.

**Actual behavior**
Nothing happens in the sim.
Sim dev console does not report receiving the code of the new event from MF.

**Details**
 - MobiFlight Version: 8.2.0.1
 - FlightSim: MSFS2020 latest
 - AddOn: WT CJ4

**Additional context**
The only workaround is to shutdown MF and restart.  
After restart, immediately the console reports receiving the new event code.
Only happens with new event names not previously used.  Stop / Run does not solve this.

**Comment by MobiFlight-Admin** [comment]
The SimConnect Client loads the defintions only on Connecting for the first time. If you add definitions to your user files then they will get picked up by the Config Wizard but unfortunately if a SimConnect connection was alread established then it won't update.

This is only the explanation why it is behaving like this at the moment.

We could definitely change the behavior of the SimConnect Client so that we reload the defintions every time you Run MF (run button).

**Comment by MobiFlight-Admin** [comment]
Again, I feel like this is really depending on #474 - but hey, maybe I can add the same logic to the WASM module too. Every time we Start the WASM module we reload. Because we have to clear the Dynamic Inputs too. i will double check.

**Comment by MobiFlight-Admin** [comment]
Nope... both ideas don't work. i cannot simply redefine the events on the SimConnect client side.

**Comment by MobiFlight-Admin** [comment]
I would have to probably dispose my current SimConnect connection and create a new one to be able to re-register the events on the MF Connector side. And the same would be true for the WASM module side. Start over completely with the SimConnect connection.

**Comment by MobiFlight-Admin** [comment]
I will put this back on the backlog. I feel that with the custom code, the priority has lowered for this one.

**Comment by DocMoebiuz** [comment]
I will close this because with the Custom Inputs that are now exclusively used by MobiFlight this is not an issue anymore.
