### ISSUE TITLE
Add YouTube button in Main Menu

### ISSUE THREAD

**Issue by Mobiflight** [Mobiflight/MobiFlight-Connector#399]
**Is your feature request related to a problem? Please describe.**
As a convenience feature we offer a YouTube link to the MobiFlight Channel in the Toolbar and the Menu.

**Describe the solution you'd like**
Click on button opens YouTube Channel of MobiFlight

**Comment by tigert** [comment]
Maybe have a dropdown for "Mobiflight Community" and there add menus for Discord / Youtube / Twitch etc?
