### ISSUE TITLE
7-segment brightness could be adjustable on runtime

### ISSUE THREAD

**Issue by tigert** [Mobiflight/MobiFlight-Connector#403]
**Is your feature request related to a problem? Please describe.** - No

**Describe the solution you'd like**
It would be nice to have a way to adjust the brightness of 7-segment displays based on simulator variables (ie, panel backlight dimmer)

**Describe alternatives you've considered**
I don't have a great idea yet - but since it is possible to adjust this when defining the 7-segment display, it would be good if we could do that somehow on runtime. 

Maybe we could automatically add an output for brightness? Like if you define "transponder code" 7-segment output device, Mobiflight could also create a matching virtual output "transponder code brightness"  tied to the same name and pins for the brightness that could accept a range between 0 and 255?

I am not sure how to do this the best way in the user interface yet, need to think. But the functionality would be useful, it just needs thought to make it understandable.

**Comment by Mobiflight** [comment]
This is already possible with MobiFlight 8.2

**Comment by tigert** [comment]
Closing this then. Sweet!
