### ISSUE TITLE
Mobiflight Modules settings Cancel button cannot be cancelled

### ISSUE THREAD

**Issue by JaimeLeon2** [Mobiflight/MobiFlight-Connector#408]
**Describe the bug**
In Mobiflight Modules settings, pressing Cancel gives a warning that there are unsaved changes. However, pressing Cancel in this dialog does not go back to previous window to give the user a chance to save.  Both buttons: OK and Cancel take you back to the Main Window.  Any changes are then lost.

**Steps To Reproduce**
1. Enter Settings > Mobiflight Modules
2. Select a module and create a new device
3. Press Cancel instead of OK
4. MF gives you a warning that there are unsaved changes
5. Press Cancel

![image](https://user-images.githubusercontent.com/86563553/125650224-b00542fa-8efe-4043-b085-dfa3de7c8acc.png)

**Expected behavior**
Pressing Cancel should take you back to the Mobiflight Modules window, so the user can save.  Only pressing OK should exit to the Main Window.

**Actual behavior**
Pressing any of the buttons: OK or Cancel takes you to the MF Main Window and all changes are lost.  

**Details**
 - MobiFlight Version: 8.2.0.3 beta
 - FlightSim: not relevant
 - AddOn: not relevant

**Additional context**
There is no point in warning the user that there are unsaved changes, if he cannot go back to save.
You might also want to correct the mispelled word "loose" in this dialog to "lose".

**Comment by Mobiflight** [comment]
This is fixed. I had to set the dialogResult for the Settings Dialog explicitly to 
```DialogResult = DialogResult.None```
