### ISSUE TITLE
Minor careless mistake in notification window after firmware update

### ISSUE THREAD

**Issue by komp1821** [Mobiflight/MobiFlight-Connector#410]
**Describe the bug**
After firmware update, a message pops up that indicates "Firmware was successful"

**Steps To Reproduce**
1. Update any Mobiflight board.

**Expected behavior**
"The firmware **upload** was successful"

**Actual behavior**
"The firmware was successful"

**Details**
 - MobiFlight Beta 8.2.0.4
![Screenshot 2021-07-15 211845](https://user-images.githubusercontent.com/71044068/125845172-453334e5-341b-4a7e-b76f-110f0700b404.png)

**Comment by Mobiflight** [comment]
fixed
