### ISSUE TITLE
Add UI to specify a delay for 7-segment LED displays

### ISSUE THREAD

**Issue by danecreekphotography** [Mobiflight/MobiFlight-Connector#427]
**Is your feature request related to a problem? Please describe.**

I'm not sure if it's something specific to how my PCB is built or if it's a general possible issue when using many 7-segment LEDs on a board, but as-is my displays flash and flicker. It appears to be timing-related.

**Describe the solution you'd like**

Adding a brief (10ms) delay into the code via a sleep statement solves my issue and all my displays look great. Unfortunately it means I have to keep remembering to add that line of code in every time I pull a new version. It'd be great if I could specify the 10ms delay via UI in the app.

**Describe alternatives you've considered**

Re-do my PCB? 😂 Not sure though if it's a PCB issue though.

**Comment by danecreekphotography** [comment]
I'm happy to add the code for this, but I'm not sure where the right place for the UI is. Should it be on the output config? Or on the 7-segment LED config for the Arduino? I'm leaning towards on the Arduino since it applies at the low level to all connected displays. Thoughts?

**Comment by kkr0kk** [comment]
I'm not sure is "software" problem, you try to hide a hardware problem. I have 7 screen 7 segments, no one flicker, i have a FPS counter and he was very fast refresh without any problems. Did you use MAX7219 ? Are you sure you don't set the output value twice in same loop ?

**Comment by danecreekphotography** [comment]
I'm not sure it's a software problem either to be honest, but it is a software fix? 😂

I have 8 connected and I'm using MAX7219s. I'm sure I'm not setting the output value twice, I only have one output row for each MAX display.

**Comment by StephanHo** [comment]
Are the 8 MAX-boards in a daisy chain or separated to one mega module?

**Comment by danecreekphotography** [comment]
It's a custom PCB, I'm not using tubes off Amazon. It's 8 MAX chips in series:

![image](https://user-images.githubusercontent.com/9524118/126908296-f5e49d34-47ce-4490-b491-e3b11df31d69.png)

![image](https://user-images.githubusercontent.com/9524118/126908311-da1dafd4-0928-4574-ad41-40f49d09d915.png)

**Comment by danecreekphotography** [comment]
This is resolved by changing the "FSUIPC7" polling (a.k.a. refresh) rate.
