### ISSUE TITLE
Provide auto-suggest and list of defined MobiFlight variables

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#433]
**Is your feature request related to a problem? Please describe.**
As a user I have a list of defined MobiFlight variables to prevent mistakes by typos.

**Describe the solution you'd like**
I have a drop down list of existing variables from other configs, e.g. when I create one in inputs action and then I want use the same variable in an output action.
While I type, I get an auto-suggestion with variable names that match my typed characters

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by pizman** [comment]
PUSH
After a test seasson yesterday i come to the same point.
Auto-Suggestion or like in the Past (Placeholder e.g.) a Dropdown that include all currently used Variable Names (Growing bigger as more Variables exist.
