### ISSUE TITLE
Rework the device icons

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#434]
**Is your feature request related to a problem? Please describe.**
It  is time to re-work the device icons in the settings UI.

**Describe the solution you'd like**
They should be bigger.
All devices should have their own distinct icon.
Icons should relate to their device.

**Describe alternatives you've considered**
Leave it as it is.

**Additional context**
Nothing.

**Comment by tigert** [comment]
Äre these PNG or is it easy to render SVG?

**Comment by MobiFlight-Admin** [comment]
At the moment they have to be png... but I would create them with a Vector based program like Inkscape and then export them as PNG files.

**Comment by tigert** [comment]
I can work on these. Will do them in SVG but align to pixel grid so they look crisp. What size does the list widget expect them in if you specify a larger size?

**Comment by tigert** [comment]
Some ideas for feedback.

Button: 
![image](https://user-images.githubusercontent.com/2587818/148363839-7b529a82-a11b-44e3-be80-4c1be2f4ffad.png)

LED:
![image](https://user-images.githubusercontent.com/2587818/148363958-1e547214-a06b-4044-819e-e63208d704ae.png)

I'm thinking of color coding inputs and outputs so that inputs are blue for example, and outputs are red, so it is easier to tell them apart at a glance.

**Comment by tigert** [comment]
Potentiometer:
![image](https://user-images.githubusercontent.com/2587818/148369754-d592ab79-be8f-47f9-8e9e-406c4719dbed.png)

Encoder:
![image](https://user-images.githubusercontent.com/2587818/148369848-8d402a9b-c148-4b5f-b32a-91d184516a73.png)

**Comment by tigert** [comment]
New approachj, wtih 16x16 icons.

Also trying to have distinct visual silhouettes for icons.

![image](https://user-images.githubusercontent.com/2587818/149683929-86fadf0d-a966-48a4-b153-f2e86e5e1259.png)

**Comment by DocMoebiuz** [comment]
i like them! i think color coding would help on top of the shape. the led stands out in style with the gradient. Maybe we can find a representation that is more like the other ones?

**Comment by DocMoebiuz** [comment]
I adding these nice board images made by @tigert, originally mentioned in #756 

Uno:
![board-uno](https://user-images.githubusercontent.com/2587818/161902658-959229cf-09b7-4fbb-babb-bfccd42c2c2f.svg)

Mega:
![board-mega](https://user-images.githubusercontent.com/2587818/161902661-ca3f5906-731a-4782-9729-47c04e041441.svg)

Mega Mini (we can still show it in a list even though it is just a "mega" technically)
![board-mega-mini](https://user-images.githubusercontent.com/2587818/161902664-3c07d7fc-51a1-468e-a47a-121b6883fe18.svg)

Pro Micro:
![board-pro-micro](https://user-images.githubusercontent.com/2587818/161902665-6f8fa341-26ac-4fc2-bafd-4a387896b091.svg)

**Comment by tigert** [comment]
Adding the icons here. 

![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/2587818/31bc2e31-4286-44e2-9a6e-d84921cacfb9)

### Outputs
Led/output: 
![mobiflight_icon_out_led](https://github.com/MobiFlight/MobiFlight-Connector/assets/2587818/5fe48451-1d50-4305-aee0-6b6c1d86348c)

Led/7segment:
![mobiflight_icon_out_7segment](https://github.com/MobiFlight/MobiFlight-Connector/assets/2587818/3dbf80e8-e71e-445c-95c7-9f01e5177032)

Servo:
![mobiflight_icon_out_servo](https://github.com/MobiFlight/MobiFlight-Connector/assets/2587818/3ff15475-46bd-4e6f-83eb-4dedf499207d)

Stepper:
![mobiflight_icon_out_stepper](https://github.com/MobiFlight/MobiFlight-Connector/assets/2587818/b751e9e1-8140-463a-bcf2-74c7b9ef60a4)

LCD Display:
![mobiflight_icon_out_lcd](https://github.com/MobiFlight/MobiFlight-Connector/assets/2587818/85f60982-4217-4272-9a47-f3ddc5f89daf)

Output shift register:
![mobiflight_icon_out_shifter](https://github.com/MobiFlight/MobiFlight-Connector/assets/2587818/e70b2f67-e5c0-4c98-922b-a09e322d12f4)

### Inputs
Encoder:
![mobiflight_icon_in_encoder](https://github.com/MobiFlight/MobiFlight-Connector/assets/2587818/fbf6e477-4b2c-4755-9b2c-d0101812b29d)

Button:
![mobiflight_icon_in_button](https://github.com/MobiFlight/MobiFlight-Connector/assets/2587818/907476e0-ada4-4bf5-bfd9-2dc9d7f9d5ff)

Analog input:
![mobiflight_icon_in_analog](https://github.com/MobiFlight/MobiFlight-Connector/assets/2587818/a7c6bec6-b203-4bac-883a-d70cbf940f75)

Input shift register:
![mobiflight_icon_in_shifter](https://github.com/MobiFlight/MobiFlight-Connector/assets/2587818/85130d9a-1c9e-4c71-946f-b14d820c45d4)

Input multiplexer:
![mobiflight_icon_in_multiplexer](https://github.com/MobiFlight/MobiFlight-Connector/assets/2587818/4e6c8ca4-b378-46f1-8a12-039fc24165e4)

**Comment by tigert** [comment]
This zip contains the svg files too.
[mobiflight-icons-2023-11-11.zip](https://github.com/MobiFlight/MobiFlight-Connector/files/13326207/mobiflight-icons-2023-11-11.zip)

**Comment by tigert** [comment]
updated the analog input icon and the zip
