### ISSUE TITLE
Add documentation for Shift Registers in Wiki

### ISSUE THREAD

**Issue by Mobiflight** [Mobiflight/MobiFlight-Connector#435]
**Is your feature request related to a problem? Please describe.**
As a user I have a documentation for shift registers

**Describe the solution you'd like**
I want to understand how they work.
I want to understand how to configure them.
I want to understand which devices are supported.
Documentation is in the Wiki.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by danecreekphotography** [comment]
First draft written: https://github.com/Mobiflight/MobiFlight-Connector/wiki/Controlling-LEDs-with-a-shift-register

**Comment by danecreekphotography** [comment]
This is now done and linked to the various places on the wiki.

**Comment by Mobiflight** [comment]
@danecreekphotography Thank You so much - that's awesome! Great job!!!
