### ISSUE TITLE
Analog Input expressions not working correctly 

### ISSUE THREAD

**Issue by Jay737** [MobiFlight/MobiFlight-Connector#438]
- [x] disable ncalc parsing for Custom Inputs

**Describe the bug**
adding formulas to "set value" line, breaks things up

**Steps To Reproduce**
1. add device/analog input
2. in the input config use FSUIPC offset 0C4E, enter @ into "set value" line  
3. observe that NAV1 OBS works with potentiometer now however with the ratio of 1 : 2.84
4. to correct that, insert expression @*359/1023 into "set value" line
5. NAV1 OBS is no longer responding or just randomly jumps about

**Expected behavior**
The formula above should correct the physical pot and compass card in the sim to 1:1 ratio.
 
**Actual behavior**
A clear and concise description of what actually happens.
Entering any expressions breaks things up.

**Details**
 - MobiFlight Version: [9.0.0]
 - FlightSim: [X-Plane, MSFS2020]
 - AddOn: [Default Aircraft]

**Additional context**

**Comment by Mobiflight** [comment]
this is fixed in the code and will be provided as beta soon.

**Comment by MobiFlight-Admin** [comment]
- [ ] disable ncalc parsing for Custom Inputs

**Comment by MobiFlight-Admin** [comment]
Release Note: 

The conversion from double to the INT uses the Math.Floor function as we are doing in MobiFlight normally.
