### ISSUE TITLE
Save button activates with no changes made to MF

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#443]
**Describe the bug**
MF Connector Save button is activated with no changes made in any config

**Steps To Reproduce**
1. Start MF normally.  The last mcc file is automatically loaded and the Save button is deactivated.
2. Click on any Input or Output config line

**Expected behavior**
The Save button should only be activated when a change is made to any configuration.

**Actual behavior**
Just clicking on any config without even opening the config wizard activates the Save button and consequently the dialog box reminding the user that there are unsaved changes when exiting MF (when there are none).

**Details**
 - MobiFlight Version: 9.0.0
 - FlightSim: irrelevant 
 - AddOn: irrelevant

**Additional context**
This is the opposite situation of what happened before, where MF would not activate the Save button after having made changes.

**Comment by MobiFlight-Admin** [comment]
@JaimeLeon2 I have started to work on this because there is another issue which is kind of related to this. It is quite some effort to do this nicely, that's why I had not done it first :D but yeah - it is probably time to do it the right away.

**Comment by MobiFlight-Admin** [comment]
I think I have this resolved. OMG = that was a lot of work. :D

**Comment by MobiFlight-Admin** [comment]
I forgot to add this for the Input Grid.

**Comment by JaimeLeon2** [comment]
Yeah, I updated to 9.0.0.1 tonight and noticed the save button still is activated by merely clicking on any line.

**Comment by MobiFlight-Admin** [comment]
Can you test with the latest main branch version? I indeed overlooked something that i fixed after publishing.

**Comment by JaimeLeon2** [comment]
Tested with MF 9.0.0.2 and the problem is solved. Thanks.
