### ISSUE TITLE
Behaviour of changing On Release action in a duplicate row

### ISSUE THREAD

**Issue by omrygin** [MobiFlight/MobiFlight-Connector#444]
**Describe the bug**
When duplicating an input row with a button, changing the input device **after** changing the resulting On Release action reverts the action back to the action of the duplicated row. I have not tested other actions

**Steps To Reproduce**
1. Create an input row with a button, and choose an On Release action
2. ~~Duplicate the newly created row in (1)~~ this step is not needed
3. Change the action before changing the input device
4. Change the input device to another button
5. The input action reverts back to the original action

**Expected behavior**
I would expect the newly chosen action to remain, regardless of the order of changing the input device and action

**Actual behavior**
The action changes back to the original one.

**Details**
 - MobiFlight Version: 9.0.0
 - FlightSim: irrelevant
 - AddOn: irrelevant

**Additional context**

**Comment by Mobiflight** [comment]
Ok. Now I understand what you are saying. It doesn't have to do anything with cloning - that threw me off.

What's happening is, that on changing the device it re-loads the current active config which is still the config that was loaded when you opened the dialog. So any time you change the device the configs gets restored even though you have made a change.

**Comment by MobiFlight-Admin** [comment]
I discovered that this is actually a bigger story where any change on the forms has to trigger a sync with the current config and to make sure that if the users cancels, the old config gets restored. I will park this for now, this can be solved at a later point.

**Comment by DocMoebiuz** [comment]
This behavior is still in version 9.3.2

**Comment by DocMoebiuz** [comment]
you can copy the action first and then paste it again. I think the default logic is fine the way it is.
