### ISSUE TITLE
Led test on pwm-enabled led should have a brightness slider for testing

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#445]
Currently "test" button on output config page turns led on and stop turns it off.

If your led has pwm enabled, it might be useful to have a brightness slider for the test function, so you can test also different brightness values.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pizman** [comment]
Short help until this is not live ( or will not come live finally)

Simply use the Transform field for that.
If you enter e.g. "100" in transform then the Output Value is 100 all time.....   Works with every value for sure.

So  To test brigthness of that PWM LED .....     Create a new Config Line....    Use the LED as device.  Enable PWM.
Then use in transform e.g. "10" and RUN.
You see the Brightness if Value is 10/255 ......       To test another Value us for example "200" in transform.
Then you see more broght 200/255 setting.

I know not a slider..... But testing a LED can be done within 3 Mins by create a testing Config like this already !

**Comment by DocMoebiuz** [comment]
It could make sense to have a "test" value for all devices in the panel where the "test" button is. The only device where the test string is a bit more complicated is the LCD device. 

by that way we could add the test value override once and use it across all kinds of devices.

**Comment by DocMoebiuz** [comment]
This is now supported with the new Test function that came with the Modifier UI, see: #1249
