### ISSUE TITLE
Add "Minimize on startup" setting.

### ISSUE THREAD

**Issue by skiz** [Mobiflight/MobiFlight-Connector#447]
In order to automate simulator startup sequence, I would like the option to minimize MFConnector on startup.

**Comment by Mobiflight** [comment]
Please try the "AutoRun" feature which is pretty much exactly what you are looking for. It will start MF automatically with the last used config and minimize to the tray.

**Comment by skiz** [comment]
I can't believe I missed that. Thanks!
