### ISSUE TITLE
Ignore listed COM ports for non-mobiflight Arduinos, add additional options.

### ISSUE THREAD

**Issue by skiz** [MobiFlight/MobiFlight-Connector#448]
I have 2 G1000s that do not use mobiflight, and are also compatible Arduinos.
mobiflight requests that I flash these when I start it for the first time. (Another separate UX issue)

In order to remove these devices from showing up in mobiflight both as available devices,
there should be a list of available com ports in settings to ignore. This should also speed up initialization dramatically.

Only showing configured devices in the mobiflight modules page is also a good option.

Upon finalizing my configuration I would also like the option to skip scanning for new hardware on startup, which should assume devices and ports are set up the same way as previously used.

**Comment by MobiFlight-Admin** [comment]
@skiz I am reviewing this issue and there is actually an option already built into MobiFlight to not scan for compatible boards. It is under Settings > MobiFlight Boards > Firmware Settings > The Checkbox. 

The checkbox label right now is misleading (and i changed it for 9.2) but it is what you are looking for.
https://github.com/MobiFlight/MobiFlight-Connector/commit/e3e82e5d1e22d13f8d6415463ef0617dd9d5da0a

I will merge the other idea for de-selecting COM port with https://github.com/MobiFlight/MobiFlight-Connector/issues/551
