### ISSUE TITLE
FSUIPC Connection Sim Status Indicator in offline mode

### ISSUE THREAD

**Issue by CaptainBobSim** [MobiFlight/MobiFlight-Connector#452]
Bug: Offline mode lets Sim Status show a checkmark upon re-open.

**Steps To Reproduce**
1. Create a configuration using an FSUIPC or XPUIPC Switch event
2. Activate Offline mode
3. Close MobiFlight
4. Reopen MobiFlight
5. Trigger the event by pressing a switch
6. See error

When you turn offline mode on, Sim Status shows a warning.
![image](https://user-images.githubusercontent.com/76851401/130335672-e48cf2ca-eff8-4374-aa94-e9a1bd466801.png)

When you close and reopen MF, sim status shows a checkmark.
![image](https://user-images.githubusercontent.com/76851401/130335675-a4b3fcf1-d4f5-4b31-88fd-6dcc8f0e7f98.png)

After reopening, pressing any XPUIPC button shows this error and Sim Status goes back to a warning:
![image](https://user-images.githubusercontent.com/76851401/130335686-ad88f52b-b3c0-404a-8455-d75cf0633125.png)

![image](https://user-images.githubusercontent.com/76851401/130335693-d0868b76-d1a9-48e1-96c5-985c4698b34d.png)

Same error happens in FSX
![image](https://user-images.githubusercontent.com/76851401/130335849-8b6d24db-28a5-456e-a677-43293fd01b22.png)

**Expected behavior**
Expected to see sim status as a warning upon reopen.
When you use the dropdown menu (or hover?) for the warning sign, an "Offline mode activated" indicator could show.

**Actual behavior**
Sim Status showed a check mark upon reopen.

**Details**
 - MobiFlight Version: 9.0.0
 - FlightSim: Initially X-Plane 11.55, then FSX
 - AddOn: Default Aircraft C172, then FSX Default 172

**Additional context**
For me, the Offline mode indicator blended in, and I didn't realize it was on for a while.

**Comment by MobiFlight-Admin** [comment]
@CaptainBobSim thanks for reporting this! I noticed some glitches with the status indication too. I will check this out as soon and definitely assign it to the next update.

**Comment by MobiFlight-Admin** [comment]
I think i fixed it. It will be in the next beta, so please let me know if you can still reproduce it.

Here is what I fixed:
- There is no action executed unless the FSUIPC connection is established.
- There are no connect events and disconnect events fired when not connected.
- The status bar icons for FSUIPC and MSFS2020 are initialized with a exclamation mark item.

**Comment by CaptainBobSim** [comment]
Woah! It works like magic! That's so amazing Sebastian!
