### ISSUE TITLE
Add AS3X Touch events (for X Cub and VL-3)

### ISSUE THREAD

**Issue by davidlav** [MobiFlight/MobiFlight-Connector#459]
**Is your feature request related to a problem? Please describe.**
Events are missing for the `AS3X_Touch` displays present in the X Cub and VL-3 (to my knowledge they seem completely unrelated to the [AS3X events for the 330](https://github.com/Mobiflight/MobiFlight-Connector/blob/main/MSFS2020-module/mobiflight-event-module/modules/events.txt#L203) which are prefix with `AS3X_1`, while what I'm asking for is prefixed with `AS3X_Touch_1`.)

**Describe the solution you'd like**
Adding this list of events for the AS3X_Touch:

https://forums.flightsimulator.com/t/as3x-touch-simconnect-events/438406

**Comment by danecreekphotography** [comment]
All the included events are now pulled from hubhop, which is a site where community members can contribute. Head on over to https://hubhop.mobiflight.com/ and add the missing events (if they aren't already there), and they'll flow automatically into MobiFlight in future updates.

**Comment by davidlav** [comment]
Thanks, will do.

**Comment by danecreekphotography** [comment]
You can also join the Discord server where there's a pretty vibrant conversation around events, in the #hubhop and #msfs2020-wasm-module channels. https://discord.com/invite/U28QeEJpBV

**Comment by davidlav** [comment]
Appreciated, I'll check those out.

**Comment by MobiFlight-Admin** [comment]
@davidlav Thanks for contributing, please let me know if you need support or if you were able to add the events. Once added, we should close this issue.

THANKS!!!

**Comment by davidlav** [comment]
Yep, all added.  Thanks for the help!
