### ISSUE TITLE
Run button is activated after enabling/disabling logging mode

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#465]
**Describe the bug**
When logging mode is enabled or disabled, the Run button is activated, but MF is already in Run mode and is running.  Pressing the Run button, actually Stops MF, and another press of Run is necessary to reestablish the Run mode.

**Steps To Reproduce**
1. MF should be running normally with the sim.
2. Go to Settings and check Enable logging mode.
2. Exit Settings
3. Note Run button is activated, also note MF is running normally with the sim.
4. Press Run button... note MF stops.
5. Press Run button again... note MF now runs normally
6. Same happens when disabling logging mode

**Expected behavior**
After enabling or disabling logging mode, if MF was running already, Run button should stay deactivated.

**Actual behavior**
Run button is activated even though MF is already running normally.

**Details**
 - MobiFlight Version: 9.0.0
 - FlightSim: MSFS2020
 - AddOn: Irrelevant

**Additional context**
None

**Comment by danecreekphotography** [comment]
This reproduces simply by opening and closing the settings dialog, no need to make a change to the logging setting.

1. Open dialog
2. Hit ok

**Comment by danecreekphotography** [comment]
I think I figured this out. Opened a little fix for Seb to look at. It works, but he might have a suggestion for a better way to handle it.
