### ISSUE TITLE
FSUIPC EventID Value field throws exception when using placeholder

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#467]
**Describe the bug**

**Steps To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what you actually happens.

**Details**
 - MobiFlight Version: [e.g. 8.2.0]
 - FlightSim: [e.g. MSFS2020]
 - AddOn: [e.g. Default Aircraft]

**Additional context**

**Comment by danecreekphotography** [comment]
For completeness the steps to reproduce are:

1. Create a new input config
2. Select `FSUIPC - EventID` for the action type
3. Select any preset and hit `Use`
4. Change the `Para` field to `@`
5. Hit `OK`.
