### ISSUE TITLE
Unable to view input/output configuration of shared .mcc files

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#468]
It is not possible to see the configuration of an input item unless it is assigned to an Arduino pin.

It would be useful to study .mcc files made by others to learn or adapt it to your own panels. But currently it is not possible to see what is assigned to each input pin without assigning them to arduino inputs first, because the configuration area on the InputConfigWizard will be hidden unless the item is assigned to a pin.

It would be useful to be able to handle this somehow differently that enabled one to see what is configured - like disabling the "OK" button until you have assigned a pin?

**Comment by pizman** [comment]
Agree  100%
Not know how to perform this..... BUT  i ask the same years ago.
Thats why i always have a "FAKE Mega" on my desk....  A Empty Mega without devices..... Just to have a Board with a imaginary Button Input defined i can temporary set to "see" the Config Settings !

I hope this is not to difficult!   For OUTPUT Configs this workes....   Settings are visible ( and changeable) whatever no device is set.

**Comment by tigert** [comment]
I think it would be a good compromise disable (gray out) the input or output configuration part when the input or output device is not assigned or is orphaned.

Once you assign a control to a config item, it would then be activated and no longer grayed out.
