### ISSUE TITLE
Simvar list displays guid instead of name

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#478]
**Describe the bug**
The list of simvars to choose in Output configwizard displays just the guid of the simvar.  This makes it impossible to select a simvar from the list by its name, as before.  The only way now is to know beforehand what the variable name is, therefore, not very user friendly.

**Steps To Reproduce**
1. Create a new Output config
2. Choose Simconnect 
3. Choose any group
4. Preset menu appears as guid and not names

**Expected behavior**
Variables available by name should be displayed like before, not guid.

**Actual behavior**
Variables are listed by guid code.  Not human readable at all.

**Details**
 - MobiFlight Version: 9.0.0.1
 - FlightSim: MSFS2020
 - AddOn: Irrelevant

**Additional context**
Suspect that Hubhop is generating the msfs2020_simvars.cip file with the guid instead of the name.

**Comment by MobiFlight-Admin** [comment]
i noticed that too last night. It's already fixed. I have to commit to the repository which i will be doing later.
