### ISSUE TITLE
On button pressed error after several minutes of uptime

### ISSUE THREAD

**Issue by SamBobBarnes** [MobiFlight/MobiFlight-Connector#494]
I am using an arduino Mega 2560 as a controller for a radio stack I am building. I am using two rotary switches set up as buttons in mobiflight to change a mobiflight variable (though this was also an issue when I was using FUIPC free offsets). After a few minutes of running, when I try to use these switches, two or three of the positions will throw the error `mobiFlightCache_OnButtonPressed: tuple.Item2.DataBoundItem is NULL`
and the issue cant be resolved without stopping mobiflight and running it again, but then the issue starts again in a few minutes.
The affected pins that the buttons are plugged into are 22-27 if that may be relavent.

**Details**
 - MobiFlight Version: 9.0.0
 - FlightSim: MSFS2020

**Comment by MobiFlight-Admin** [comment]
thanks for reporting - do the switches stop to work or do you only see the messages? are you editing any settings while you are in "Run" mode?

**Comment by DocMoebiuz** [comment]
I will close this due to 

- inactivity and also because 
- we made a lot of updates, so this might be no issue anymore.
- there were no other general complaints by the community, so this might be an individual config problem too.

Feel free to reopen and provide instructions on how to reproduce.
