### ISSUE TITLE
Config References dropdown truncates the full config name

### ISSUE THREAD

**Issue by ssewell** [MobiFlight/MobiFlight-Connector#495]
**Describe the bug**
If a lengthy (approximately 20 characters) Config names are used, then attempting to select one within the ConfigWizard -> Sim Variable (tab) -> Config References, is difficult as you have to enumerate each option manually to see the full name.

**Steps To Reproduce**
 1. Enter a number of config items with long names
 2. Edit any one, and attempt to select another one in a Config References dropdown

**Expected behavior**
The dropdown is sufficiently wide to display longer names.

**Actual behavior**
The dropdown width is short and prevents easy selection:
![image](https://user-images.githubusercontent.com/2242776/134278759-1d00413a-b692-4a45-a4f1-ce9f2bc734ae.png)

**Details**
 - MobiFlight Version: 9.0.0

**Additional context**
Config names are often prefixed to ensure that they are grouped logically when sorting by name. This is also driven by the fact if you sort by any column you lose the original config order (as entered) and have no provision to return to the original sorting.

This could be addressed by increasing the width of the dropdown shown within the Configure References.

**Comment by pizman** [comment]
Agree !
Thats a point also in some other spots.....   ( I thought to report as Bug many times in the past myself)
I know these things will be much more better in a future full reworked GUI....  But maybe its also time NOW to temporary solve this also for now.
In upper example we  see there is still a lot of Space right of the Config Symbols.....   So it would be no big deal to increase  this whole field ( include Dropdown) by 100-200%  ....  No mater if the Symbols move fully to the right corner !
Additional we could also enlarge the whole MF Window up to HD 1920-1080 Full screen if we like this.
May its no longer "State of the Art" to work with these small Windows.

**************
@ssewell 
About temporary solution ( like i do) ....  Simply reduce name Length by cleanout all unless text!
In your case the whole Config File pretty sure is for a Airbus A320.....   So the Information "A32NX" is not needed. 
Also the Area "FCU" can be used as a simple Single Character....  A-Z means 26 individual Areas.

So in your example....  Current Name "A32NX FCU - 31-"  need 16 Chars (Including not needed Spaces).
If you use "A31-" You need 4 Chars instead ..... "A" represent e.g. FCU ....  Number remains the same .
You see.... 12 Chars more of the real Config name without a disadvantage . Better result in same GUI !

**Comment by ssewell** [comment]
@pizman Here's what it would look like if updated to take up more of the available realestate. Would definitely address the issue.
![image](https://user-images.githubusercontent.com/2242776/134374285-cd596ae0-4b9d-4f63-9b0e-76b9b62b585e.png)

**Comment by pizman** [comment]
Perfect!
Is this just a Photoshop Rework OR  Do you script this in a custom Version ??
If scripted.... Please give this data to Sebastian and contact him
This will be a nice new feature/rework for V9.1

**Comment by ssewell** [comment]
Closing this to submit a cleaner pull request without superfluous commit history.
