### ISSUE TITLE
Save button remains inactive after a merge

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#499]
**Describe the bug**
After merging a second config file into the main config file, the save button remains inactive.

**Steps To Reproduce**
1. Open MF Connector (last config is automatically loaded)
2. Merge a second config file into the loaded file

**Expected behavior**
Save button should be activated indicating there have been changes made to the config.

**Actual behavior**
Save button remains inactive, so merged config can be lost if user exits from MF without explicitly executing "Save as".

**Details**
 - MobiFlight Version: 9.0.0.4
 - FlightSim: irrelevant
 - AddOn: Irrelevant

**Additional context**
None

**Comment by danecreekphotography** [comment]
Looks like the fix goes here:

https://github.dev/MobiFlight/MobiFlight-Connector/blob/3df5cfe6123d9e74867433154e31498e9ecb8d47/UI/MainForm.cs#L1094-L1095
