### ISSUE TITLE
REMIND NET Framework 4.5.2, 4.6, 4.6.1 will reach End of Support on April 26, 2022

### ISSUE THREAD

**Issue by gyssels** [MobiFlight/MobiFlight-Connector#513]
**Is your feature request related to a problem? Please describe.**
A migration strategy should be in place before April

**Describe the solution you'd like**
the title states clearly

**Describe alternatives you've considered**
An intermediary migration to another framework like 4.8, as still supported may be a baby step and easier step

**Additional context**
Currently working with people of thijse/Arduino-CmdMessenger. Should have by then a fully translated project

May others work on the issue as well of others parts of mbflight

**Comment by gyssels** [comment]
related to  #484 and #508

**Comment by gyssels** [comment]
Any one else?

**Comment by DocMoebiuz** [comment]
I updated all projects to .NET4.8 - so far everything looks ok... only minor issues that need some attention (DataGridView)
