### ISSUE TITLE
Analog pot generates ncalc precondition errors

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#515]
**Describe the bug**
Analog potentiometer config generates in logging mode a lot of ncalc precondition error messages, only in Run mode. No preconditions are defined.  **EDIT... More testing led to outputs being one of the sources of errors... see comment below**

**Steps To Reproduce**
1. Create analog input config in board
2. Create input config 
3. Press Stop button
4. Enable offline mode
5. Enable logging mode
6. Move pot knob. Note steady normal operation events in the log. 
7. Press Run button
8. Note now lot of ncalc precondition errors are generated. 
9. Press Stop
10. Note errors stop, but a bunch of cache buffer pot triggers continue appearing until  buffer is consumed. 

**Expected behavior**
No ncalc errors. 

**Actual behavior**
Lots of ncalc precondition errors. 

**Details**
 - MobiFlight Version: 9.0.0.4 beta
 - FlightSim: irrelevant
 - AddOn: irrelevant 

**Additional context**
Ncalc exception errors continue to happen consistently...
10/4/2021 9:36:50 PM(743): checkPrecondition : Exception on NCalc evaluate
10/4/2021 9:36:50 PM(533): checkPrecondition : Exception on NCalc evaluate
10/4/2021 9:36:50 PM(324): checkPrecondition : Exception on NCalc evaluate
10/4/2021 9:36:50 PM(123): checkPrecondition : Exception on NCalc evaluate

**Comment by JaimeLeon2** [comment]
**SORRY, I WAS WRONG.**  The ncalc precondition errors are not generated by the analog input configs.  I have been able to track down these errors to those **output configs that use the compare tab to change the value to a string.**  I think these errors began appearing in Mobiflight at the time analog input was introduced, so I would suspect something changed in the way ncalc is used in this particular release.

**Comment by MobiFlight-Admin** [comment]
The reason this is happening was that we allow ncalc in the comparison fields also if no "$" is part of it (which was the old indicator for me to apply ncalc). We discovered that we would like to also apply ncalc if placeholders were used, etc. 

But since we also allow Strings which obviously can't be parsed by ncalc, the error now is happening alot.

**Comment by JaimeLeon2** [comment]
Still getting a lot of ncalc errors and I am not using any placeholders in the output configs assigning string values.  Just if value equal 1 do "*", else do "-".

**Comment by mikas225** [comment]
hey guys.
I hope everyone is well.
I would like to ask for your help.
I have a Logitech G940 and I would like to know if I can configure it using mobiflight.
Could you help me by telling me which driver or version of the program I should download?
I have the FS2020 and would like to use my joystick to simulate on it.
