### ISSUE TITLE
Pin0 is not marked as used for the proMicro

### ISSUE THREAD

**Issue by elral** [MobiFlight/MobiFlight-Connector#517]
**Describe the bug**
If a device is configured w/ Pin0 as input at the proMicro, this Pin is not marked as used and can be defined for further devices.

**Steps To Reproduce**
1. config a device with Pin 0 at the proMicro
2. config a second device, Pin0 can be choosen again

**Expected behavior**
Pin0 should not be available for futher devices if used once.

**Actual behavior**
See bug description

**Details**
 - MobiFlight Connector Version 9.xy

**Comment by pizman** [comment]
Pretty sure a "side effect" of the improvisional Solution you guys add for the Micro !

In the past we got clearly rule.... "Pin 0 and 1 NOT exist in the MF GUI" .....    In case you vote for Pin0 (at Micro) pretty sure Sebastian allow it temporary..... But forgot to also rework the "Pin suggestion for Devices" same way.

Right ?
