### ISSUE TITLE
Dialog box will pop under MSFS when connection to FSUIPC or SimConnect is briefly lost

### ISSUE THREAD

**Issue by jeffdamp-wave** [MobiFlight/MobiFlight-Connector#518]
**Describe the bug**
Please fix the dialog that pops under when connection is lost to fsiupc.  This would be MainForm.cs(742-745) fsuipcCache_ConnectionLost.  MF seems to intermittently lose connection to fsuipc and pops the dialog behind MSFS.  After clicking on the OK button MF normally reconnects right away.  The popped under dialog is super annoying in VR.  I've modified my local code to not pop the dialog then do a short sleep and reconnect.  I have yet to fail to reconnect so seems like it would be a good idea to stop popping the dialog.  Thanks.

**Steps To Reproduce**
1. Start MF and MSFS via FSUIPC
2. Play game
3. Look for popped under dialog for a disconnect.

**Expected behavior**
You should probably have some retry logic and do a few reconnects before popping the dialog.

**Actual behavior**
A clear and concise description of what you actually happens.

**Details**
 - MobiFlight Version: [9.0.0.6]
 - FlightSim: MSFS2020]

**Additional context**
I did this in the code and it didn't seem to have any negative impact:
            if (!execManager.SimAvailable())
            {
                _showError(i18n._tr("uiMessageFsHasBeenStopped"));
            } else {
                if (sender.GetType() == typeof(SimConnectCache))
                {
                    //_showError(i18n._tr("uiMessageSimConnectConnectionLost"));
                } else
                {
                    //_showError(i18n._tr("uiMessageFsuipcConnectionLost"));
                }
            } //if
            execManager.Stop();
            System.Threading.Thread.Sleep(1000);
            if (!execManager.IsStarted())
            {
                execManager.Start();
            }

**Comment by MobiFlight-Admin** [comment]
You don't have to put a sleep in there because MF will right away try again after 10 seconds.

I will think of a silent mode or VR mode to disable these popups... but I will not disable them for everyone at the moment, rather provide a settings option for that.

**Comment by DocMoebiuz** [comment]
Are you running minimized in the tray bar or is MobiFlight maximized in window mode?

**Comment by jeffdamp-wave** [comment]
Minimized to the sys-tray for the most part.  I believe the modeless dialog only pops under when MSFS is running in VR.  MSFS doesn't make tabbing around very easy either in VR.  The game likes to have the focus.
