### ISSUE TITLE
Smoothing function for potentiometer support

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#519]
**Is your feature request related to a problem? Please describe.**
I have encountered some electrical noise coming from 7 segment display modules, which cause jitter problems in a potentiometer. Suggestions received have reduced the problem but not eliminated it.  It would be good to have a way to smoothen potentiometer readings through software.

**Describe the solution you'd like**
Implement a 10 reading rolling average in the arduino firmware with a soft switch in MF Connector analog input configuration, that can be used to turn this feature on and off.  When on, the analog pot reading sent from the board will be the rolling average of the last 10 readings.  This will effectively smoothen the readings and eliminate jitter.   This technique has been successfully used to smoothen the operation of a yoke with three analog pots connected to a pro micro.

**Describe alternatives you've considered**
I have tried to isolate the noise problem in hardware and jitter has been successfully reduced, but not eliminated.

**Additional context**
Potentiometers can present jitter due to various reasons.  This will provide a solution in software to alleviate this problem.  
I suggest that instead of calculating a real rolling average, which can take too much computational power, adding 10 readings and dividing by 10 in each read cycle,  Start with an assumed average of zero and an array of ten readings (all zero).  In each cycle: increment the reading counter index (0 to 9), add the current reading divided by 10 and substract the counter indexed reading divided by 10.  Finally, store the current reading in the counter indexed position (replacing the value just substracted).  
Any error at start disappears within 10 cycles.

**Comment by elral** [comment]
Rolling average is easy and not computational if some things are considerd. Number of samples shhould be 2^n, e.g. 8 samples. Then the division is only a shifting of the sum. Store the readings in an array, then the average can be subtracted with the oldest value and the newest will be added. Shift the average and you get the smoothed value as return value.

I have used this severall times and it works really good. And I think it can be used all time, there is no real time delay which can be seen.

I have code for this I could supply it in an additional branch from Neiles Firmware storage.
