### ISSUE TITLE
Show COM port on the modules dropdown

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#522]
It would be useful to see the COM ports of connected modules in the status bar dropdown menu in addition to the serial numbers and module names. This would be good in case one wants to monitor serial traffic for example, and needs to know the port in situations when you have many modules plugged in.

**Comment by MobiFlight-Admin** [comment]
@tigert - oh ... you are talking about the status bar dropdown. I didnt catch that the last time. 
Maybe #541 is helping with this too.

Be aware that you cannot have MF connected and the Serial Monitor connect to the same board. it wout work because the port is already in usage.

**Comment by tigert** [comment]
I guess that #541 would help a little, and I guess this is not a very common case when you need to look up the com port.

Would the port change if you plug on a different usb hub / port btw, in case one wants to add the port to the name?

**Comment by tigert** [comment]
This works now!

We could discuss how to sort the list, but I'll think and will file a new issue about that.

**Comment by MobiFlight-Admin** [comment]
you don't have to open another issue. What should be the criteria for sorting? Board Name or COM Port?
