### ISSUE TITLE
Joystick Axis Support -  Device selection / Logging Optional ?

### ISSUE THREAD

**Issue by pizman** [MobiFlight/MobiFlight-Connector#524]
PLACEHOLDER

@ Seb.     Delete or insert your comments !

**Comment by MobiFlight-Admin** [comment]
Logging is now optional. Please check 9.0.0.7

I am thinking about listing Joysticks so I will break this up into two different stories.

**Comment by neilenns** [comment]
@MobiFlight-Admin this can be closed no correct?
