### ISSUE TITLE
Expand the number of analog inputs

### ISSUE THREAD

**Issue by Jay737** [MobiFlight/MobiFlight-Connector#526]
**Is your feature request related to a problem? Please describe.**
Apparently there's only five analog inputs available at the moment.

**Describe the solution you'd like**
Let's use the full potential of all 16 pins please.

**Comment by MobiFlight-Admin** [comment]
it was arbitray in deed. On the mega we don't have pressing memory restrictions (but we do on the UNO and ProMicro).

What is your use case for the 16 analog inputs?
