### ISSUE TITLE
Show Joysticks in List that are connected and supported by MobiFlight 

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#544]
**Is your feature request related to a problem? Please describe.**
As a user I can easily see whether my Joystick is detected by MobiFlight and can be used for assignments.

**Describe the solution you'd like**
Given My Joysticks are all connected to the PC
When MobiFlight has started
Then I can see a list of my connected Joysticks that are detected by MobiFlight and can be used without having to go into an input config where they are listed today as modules.

**Describe alternatives you've considered**
Not show a list at all. Simply show the list in input configs together with modules. User feedback is that they expect them to show similar to other modules, e.g. settings dialog, status bar 

**Additional context**
-

**Comment by DocMoebiuz** [comment]
no it's not done yet. there is no list anywhere besides the drop down on the input config.

**Comment by DocMoebiuz** [comment]
implemented by #1517
