### ISSUE TITLE
MobiFlight Board shows garbled Board information

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#546]
**Describe the bug**
Sometimes with longer device configs, a mobiflight module shows garbled board information where parts of the config information is displayed as type and the name contains wrong information or is empty.

**Steps To Reproduce**
1. Configure many devices
2. Configure 2 LCDs
3. Upload config
4. Restart MF
5. Go to settings and check the modules information

**Expected behavior**
It should show Name, Version and Type correctly

**Actual behavior**
Type shows config parts, name is empty.

**Details**
 - MobiFlight Version: [e.g. 8.2.0]
 - FlightSim: [e.g. MSFS2020]
 - AddOn: [e.g. Default Aircraft]

**Additional context**

**Comment by DocMoebiuz** [comment]
This is not happening with the current firmware (>1.12.2)
