### ISSUE TITLE
Com Port De-Selection  Idea.

### ISSUE THREAD

**Issue by pizman** [MobiFlight/MobiFlight-Connector#551]
In progress.....

[https://www.mobiflight.com/forum/topic/6824.html](url)

**Comment by okansacli** [comment]
ok thank you for this idea. I will follow it up here

**Comment by pizman** [comment]
Sorry.   not find time to specify this..... But the Topic also says what is needed......

In easy words.....
People have problems sometimes a new device is not found.....  And specialy people who need MEGAS for other things ( e.g. with own sketches to controll something) get stuck in case MF scans on every startup all Ports for compatible Boards ( to migrate for MF) .....  But may user not want this.

I don´t know how the whole ComPort Logic works.... and e.g, if we can define a clear ComPort ourself ( or if it is created by windows on every startup or so).

Pressumed Feature:   the user should be able to "de-select" special Com Ports.... So MF no longer check these Ports anymore.
Benefit:   Users can STILL use the Auto Firmware Update Tool..... In case the problematic Boards are now "unvisible" for MF.

**Comment by pizman** [comment]
Additional Note:

In case this is a verry rare usecase.....   We should not "blow up" our GUI.
Maybe this is another good point to think about a "INI File".
Not sure how Sebastian think about that....
Why not a TextFile *.cfg or *.ini  that can be edit with a ordinary Text Editor.
And the e.g. a area we could enter something like 
#ComPorts
ComPort_02, false

**Comment by okansacli** [comment]
Do not blow up the GUI.  an ini file as suggested which looks at which com ports to scan and which ones to bypass should be fantastic.

**Comment by tigert** [comment]
If this feature would otherwise be considered, I think a simple context menu entry for an arduino in the list might work?

![image](https://user-images.githubusercontent.com/2587818/143130010-cc9764ee-d83e-457e-a6d1-3d5b60530a84.png)

**Comment by MobiFlight-Admin** [comment]
cool idea

**Comment by pizman** [comment]
Hi
I must rework my comment!
I missunderstand the "AutoFirmware Update" Option all the time.
Seb explane this in the last release Vid.... So my initial Request is no longer a important request.

Till now i thought..... If i disable "AutoFirmwareUpdate" i thought MF fully no longer check or upload Firmware!
As Seb explaned....   With this Option only Board without Firmware are ignored, BUT   Board with a Firmware are still "checked".

So my request make no sense anymore! 
With current system we can "ignore" Boards if we want to do this..... And same time we have still the benefit, that "MF Boards" will be updated with newest Firmware..... Whatever Option is Disabled.

Only Disadvantage:
If a User have the Option Disabled.... But now connect a new Arduino he like to use for MF.... THEN it not work!
He must activate the Firmware Update toporary... BUT Then also all "permitted Boards" will get a MF Firmware Flash.
So he need to disconnect the problematic boards in this special situation!  But not on every Firmware Release.... Only if he add a New Board !

Summary:
I think we can life with the current system!

**Comment by tigert** [comment]
There are cases where even probing for MF firmware seems to disturb another devices. 

I remember someone saying the Class Echo desktop panel does get confused when MF Connector connects to the serial port - same with CPFlight MCP. The Class Echo is a desktop simulator panel, based on a regular Arduino Mega with a lcd screen. Thje CPFlight MCP has the same VID/PID as a Mega, and it seems to get confused by the connection attempt as well.

**Comment by pizman** [comment]
UPDATE :  - New behavour !
[https://www.mobiflight.com/forum/topic/6969.html](url)

A User report on every MF Startup his 3D Printer struggle !

**Comment by tigert** [comment]
We cannot control the rest of the world, and whether other devices get confused when being probed. 

Maybe a simple text file with ignored ports names, one per line, would work?

It would let those affected users list mark their problematic devices to be ignored, and could continue using them while enjoying Mobiflight as well.

**Comment by DocMoebiuz** [comment]
this issue is already planned for 9.3 - it is on the short list and will be worked on soon.

**Comment by tigert** [comment]
That is great news!

**Comment by DocMoebiuz** [comment]
Will be implemented by #845 - Thanks for everyone to provide input and feedback to this.
