### ISSUE TITLE
Increase number of allowed buttons, outputs and encoders on pro micro board

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#560]
**Is your feature request related to a problem? Please describe.**
The number of supported devices on a pro micro board seems to be arbitrarily low based on the number of available pins (18).  Why not allow the maximum number of devices that the board can take?  Current limits are:

#if MODULETYPE == MTYPE_MICRO
#define MAX_OUTPUTS       10
#define MAX_BUTTONS       16
#define MAX_LEDSEGMENTS   1
#define MAX_ENCODERS      4
#define MAX_STEPPERS      2
#define MAX_MFSERVOS      2
#define MAX_MFLCD_I2C     2
#define MAX_ANALOG_INPUTS 2
#define MAX_SHIFTERS      4

**Describe the solution you'd like**
Suggest to increase the limits to the following:

#if MODULETYPE == MTYPE_MICRO
#define MAX_OUTPUTS       18
#define MAX_BUTTONS       18
#define MAX_LEDSEGMENTS   2
#define MAX_ENCODERS      6
#define MAX_STEPPERS      4
#define MAX_MFSERVOS      4
#define MAX_MFLCD_I2C     2
#define MAX_ANALOG_INPUTS 9
#define MAX_SHIFTERS      4

**Describe alternatives you've considered**
Alternative is always to increase the number of boards.

**Additional context**
It seems like a terrible waste not to allow at least the LED outputs and buttons to fill a board's pin capacity. A pro micro is also great for throttle quadrant and yoke projects.  Analog inputs is another case requiring more capacity.  They only require one analog pin each, and throttle quadrants can easily have 6 to 8 axes.  The pro micro has 9 analog pins.

**Comment by pizman** [comment]
Basically agree..... Aslong we also check the critical Points before we allow this ..... else we get Bugs in the future again !

Does the Micro allow the usage of up to 18 "Device Names" in the current length ?
Also remember your Problem that Firmware is still near the limit of the Board  ( you guys fight for every single byte there).
Each additional Device have a "name" and need up to 16 Bytes to save this name in the EEPROM Right ?

Also think about Power...   On Mega we presume that a LED have 20mA .....  Means 25 LED reach the 500mA Limit of the USB..... And 40 LED reach the Overall Limit of the 800mA of the Mega.....    Thats why we limit the device number to these magical 40  ( IN THE PAST) .

*****
For me..... If this Points are cleared..... AND if you guys confirm your Boards work Stable in Laboratory Testing of the posible Setups..... Then do it.     
But please not increase this "in the dark" and then we get reports of problems later.  First Test, Then release !

**Comment by neilenns** [comment]
@MobiFlight-Admin I notice this is in ready for departure. It probably still needs work with the change to the new dynamic board loading config as I'm betting the values I used for the Pro Micro are not the new ones you might have set in this fix.

**Comment by MobiFlight-Admin** [comment]
in the current state it means it's gone be worked on - not that it is already done. This requires a change in the firmware and in the new dynamic board description.

**Comment by neilenns** [comment]
Ok thanks!

**Comment by MobiFlight-Admin** [comment]
@JaimeLeon2 it is not only about max current, every added device will also consume more memory which is really low already on the promicro. We will have to do some math to see how much headroom we have if we increase it to the suggested numbers.

Which one is the most limiting for you?

To me these numbers for the devices all seem reasonable to me. Outputs can be increased for the max 18/19 but who would actually really do one module without any inputs?

**Comment by MobiFlight-Admin** [comment]
Analog inputs are 10 bytes of memory each.

**Comment by MobiFlight-Admin** [comment]
#define MAX_OUTPUTS 16
#define MAX_BUTTONS 16
#define MAX_LEDSEGMENTS 1
#define MAX_ENCODERS 4
#define MAX_STEPPERS 2
#define MAX_MFSERVOS 2
#define MAX_MFLCD_I2C 2
#define MAX_ANALOG_INPUTS 5
#define MAX_SHIFTERS 2

**Comment by MobiFlight-Admin** [comment]
#define MODULE_MAX_PINS 21
#define MAX_OUTPUTS 18
#define MAX_BUTTONS 18
#define MAX_LEDSEGMENTS 1
#define MAX_ENCODERS 5
#define MAX_STEPPERS 3
#define MAX_MFSERVOS 3
#define MAX_MFLCD_I2C 2
#define MAX_ANALOG_INPUTS 5
#define MAX_SHIFTERS 2

RAM:   [=======   ]  74.0% (used 1895 bytes from 2560 bytes)
Flash: [========= ]  88.9% (used 25476 bytes from 28672 bytes)
