### ISSUE TITLE
None of the events from Group - Microsoft/Generic/Camera is working

### ISSUE THREAD

**Issue by simtcrom** [MobiFlight/MobiFlight-Connector#571]
**Describe the bug**
None of the events from Group - Microsoft/Generic/Camera is working.

**Steps To Reproduce**
1. Add a Button Device
2. Add an Input by selecting the previous step button
3. Select Action Type as MSFS2020 - Events and group as Microsoft/Generic/Camera and Event as VIEW_REAR (eg, none works)
4. Press the button and check if the set action is working or not

**Expected behavior**
Camera view changed

**Actual behavior**
Nothing happens

**Details**
 - MobiFlight Version: 9.1.0
 - FlightSim: MSFS2020
 - AddOn: None

**Additional context**
N/a

**Comment by DocMoebiuz** [comment]
@rofl-er - can you confirm this is a general problem with the events, rather than a problem with MobiFlight? Is there any way to around this?

**Comment by rofl-er** [comment]
> @rofl-er - can you confirm this is a general problem with the events, rather than a problem with MobiFlight? Is there any way to around this?

I have no information about this. I will ask Jaime and will report back.

**Comment by rofl-er** [comment]
@MobiFlight-Admin As per Jaimes findings, there seem to be an issue Sim-side:

```Jaime Leon
Hello, I confirm none of the camera view events work from Mobiflight with panel button, but  I see no problem from the MF side.  No errors in Mobiflight log.  It seems this is broken on the simulator side.  Tested both as presets and custom input with the same result.

https://forums.flightsimulator.com/t/fix-support-camera-api-in-simconnect/334102
Microsoft Flight Simulator Forums
Fix / Support Camera API in SimConnect
The current SimConnact camera API is non functional in MSFS 2020. This is preventing 3rd party developers of camera add-ons like ChasePlane, X-Camera, FSRealistic, etc. to proceed with their development. Mark Ellis Stick and Rudder Studios
Image
This problem is reported since one year ago, and has not been addressed, AFAIK.```
