### ISSUE TITLE
Provide a Video ( English) to show Precondition in case of a own Variable System 

### ISSUE THREAD

**Issue by pizman** [MobiFlight/MobiFlight-Connector#572]
**Is your feature request related to a problem? Please describe.**
Seb ask me multiple times what Problem we have to handle in the Forum over and over again....
So what is the most important Thing we should show in a detailed and perfect Video !
THATS it !

**Describe the solution you'd like**
Show....
1. How to create a INPUT Config to controll a Variable as a "Indicator" for later usage in Precon and Placeholder
This should show a "Latching System" ( Switch set to 1 or 0 whatever position it got)  and also related to Multiswitches with e.g. 4 Position.
This also should show a simple toggle by a momentary Button (if($=1,0,1) ..... AND also a more advanced Toggle trough e.g. 5 Modes (if($=5,0,$+1)

2. The logic to create another OUTPUT Config to read-back this Variable.... Cause else we can not use it as Config Item again !

3. How to use this Indication now in Configs for Precondition.....
One Example for a Output  ( E.g. a display that show COM1 or COM2 whatever the varibale is 1/0 )
One Example for a INPUT  ( E.g. a Button swap COM1 or COM2 whatever Variable us 1/0)

4. Short example that this can be used in Placeholders/Refferences, too    Instead to Preconditions.
Like: Placeholder A = Indicater Config ......  Placeholder B = COM1 Value ..... Placeholder C = COM2 Value.
Formula in Output Config.....  if(A=0,B,C)

**Describe alternatives you've considered**
Also a shorter Video would be helpfull..... But this is a really important element a lot of people need, but most not understand !

**Additional context**
If some users like to do..... We could make also a Version ( same Video, different Audio) for German and Spanish !

**Comment by DocMoebiuz** [comment]
The content is part of the transponder video: https://www.youtube.com/watch?v=DZuVu4qU9Uc
