### ISSUE TITLE
Support Arduino Nano

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#579]
**Is your feature request related to a problem? Please describe.**

It's basically an Uno. We should support the Nano :)

**Describe the solution you'd like**

Support the Nano

**Describe alternatives you've considered**

Don't support the Nano

**Additional context**

Once #553 is done this is trivial.

**Comment by DocMoebiuz** [comment]
@neilenns Would you like to add the board definition for the nano?

**Comment by neilenns** [comment]
Also I ran into trouble when I was doing this locally because my nano has the same vid and PID as the mega

**Comment by DocMoebiuz** [comment]
That's fine. You are right... we can wait with this one until after the release.
I have seen this problem before where VID/PID combos are used by mega and uno... which is even more disturbing. A user can now handle that locally by editing the info but maybe there is a better solution.

**Comment by neilenns** [comment]
The real way to solve it is to pop a dialogue and ask the user which of the matching boards should be used. That would only need to happen if the board doesn't have the mobile flight firmware already on it because once the firmware is on it the new board system knows what it is for real

**Comment by neilenns** [comment]
@DocMoebiuz so should we do this or nah? 😂

**Comment by DocMoebiuz** [comment]
i thought we have everything we need now

**Comment by neilenns** [comment]
With the changes you added to handle ambiguous boards we could. Requires:

1. Building and bundling a nano built firmware
2. Adding the nano board.json

**Comment by elral** [comment]
And old / new bootloader is considered?
I tried to use 2.json files which just differ in the bootloader parameter, but this was not the best idea.

**Comment by neilenns** [comment]
That would work but would mean every nano is ambiguous.


________________________________

**Comment by DocMoebiuz** [comment]
> And old / new bootloader is considered?
> I tried to use 2.json files which just differ in the bootloader parameter, but this was not the best idea.

that's how it is in the arduino IDE iirc. 
Arduino nano (old bootloader)

**Comment by elral** [comment]
@neilenns no board is recognized if 2 json files with the same type but different Baud rate are n the board folder.
I couldn't find another way as to use 2 environments in PlatformIO for new and old bootloader and different Mobiflight types with 2 json files accordingly.

**Comment by neilenns** [comment]
Ahhhh right. Would need to report two different MobiFlight type which is weird because they would be identical otherwise. Hmmmmm.

**Comment by elral** [comment]
Maybe we should move the type to the platformio.ini file so at least the board file can be double used.
Same would apply for the Leonardo (just a question on Discord)

**Comment by neilenns** [comment]
It just seems wrong to ship two firmwares that are identical other than MobiFlight type. This can probably be solved in the desktop side by grabbing all matching boards. I'll look later.


________________________________

**Comment by neilenns** [comment]
Thinking about this more on the drive home the Nano is a giant pain. Even if we had firmware that reported two different MobiFlight Type values we still wouldn't know what baud rate to use when connecting to the board in the first place. It's a circular loop: to connect to the board we need to know the baud rate, but we don't know the baud rate unless we connect to the board and ask its type.

Even after flashing the board in the first place this would be a problem on every launch of MobiFlight on the desktop.

Possible solutions would be:

1. Caching the working baud rate for each COM port
2. Trying each matching board file in order until one of them works every time we want to connect
3. Asking the user every time MobiFlight runs what kind of nano it is

All of these require real coding work beyond just shipping a .board.json and firmware.

**Comment by DocMoebiuz** [comment]
i was going with the assumption that the baudRate adjustment was only required for the bootload when uploading the sketch. Is it really every time that you would want to connect?

**Comment by DocMoebiuz** [comment]
I am right with my assumption. It is only required for uploading the sketch. So we could very well talk to it during normal MF operations regardless of the variant.

Only the avrdude settings are different for one or the other. That is already supported.

**Comment by elral** [comment]
I am using both types since month w/o problems, just the two different json files and 2 different environments in PlatformIO.

**Comment by neilenns** [comment]
Ah, I thought the baud rate mattered when talking to the board after flash as well. Ok, let me go investigate some stuff on the Mobiflight board.json side of things.
