### ISSUE TITLE
Provide an expand option for the Variable field of the Output config wizard

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#583]
**Is your feature request related to a problem? Please describe.**
The Variable field of the Output config wizard has only one line capability at present.  However, the string capacity of its buffer was increased to 1024 characters recently.  An option to expand the size of the window is much needed, in order to be able to confortably read the code, when more than one line of code is required.

**Describe the solution you'd like**
Provide a handle in the lower right corner of the box to pull the window down and expand its vertical size dynamically, or alternatively just provide a bigger box (like the Custom Input)

**Describe alternatives you've considered**
There are no good alternatives to putting RPN code in output configs.  MF Transforms can do just a fraction of what can be accomplished with RPN.

**Additional context**
None.  Thank you.

**Comment by tigert** [comment]
I would say the dialog should remember its size if you make the field larger

**Comment by JaimeLeon2** [comment]
Also, the output config Variable field does not tolerate multiple lines of code separated by CRLF.  This is in the same fashion as events.txt where all the code has to reside in one single line.  It would be much more readable to be able to have the expanded window, but with similar text editing functionality as the Custom Input box (which does handle CRLF).
