### ISSUE TITLE
Update the developer guide to reference new firmware repo

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#584]
https://github.com/MobiFlight/MobiFlight-Connector/wiki/Developer-Guide is out of date and still references the Arduino IDE. Update to point to the new firmware repo and readme there.

**Comment by DocMoebiuz** [comment]
@neilenns - updated the description. Any additional infos that you think we should mention?

**Comment by neilenns** [comment]
@DocMoebiuz I think it's sufficient just to get rid of all the old firmware details and say "see the other repo".
