### ISSUE TITLE
Improve procedure to write settings file in Appdata

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#589]
**Is your feature request related to a problem? Please describe.**
It has happened now twice that a PC crash results in a corrupt settings file in Appdata/Local/Mobiflight which causes Mobiflight to not start. I suspect the corruption is caused by mobiflight updating the file when the crash occurs. 

**Describe the solution you'd like**
I suggest that the writing procedure could be improved by first writing the file to a temp file and then renaming the original file as .old and the .tmp as .cfg. This would prevent overwriting the original until the last minute and creates a backup that can be used if the corruption still occurs. 

**Describe alternatives you've considered**
Use the cfg from a previous version which can be months old. 

**Additional context**

**Comment by neilenns** [comment]
MobiFlight relies on built in .NET Framework methods for handling settings, it has no control over how they get written.

I made a prior fix to catch exceptions when upgrading settings files. Are you seeing this crash between same versions of the MobiFlight desktop app @JaimeLeon2 where no settings upgrade is necessary?

**Comment by neilenns** [comment]
Next time you get this @JaimeLeon2 can you please copy and paste the exception details into this bug report?

**Comment by JaimeLeon2** [comment]
There is no exception error generated. The Mobiflight startup simply fails and exits to Windows. Upon examination of the cfg file, I found a bunch of null characters and a the file content is clearly truncated.

**Comment by JaimeLeon2** [comment]
If the writing procedure cannot be changed then maybe upon an error in reading the cfg, revert back to a default config settings and alert the user.

**Comment by neilenns** [comment]
Ugh, that's a problem :( All that settings load stuff happens automatically and I can't find where there would be a place to add exception handling to just load the default config. That's why I was hoping for an exception stack trace, to see where it was failing.

**Comment by JaimeLeon2** [comment]
> MobiFlight relies on built in .NET Framework methods for handling settings, it has no control over how they get written.
> 
> I made a prior fix to catch exceptions when upgrading settings files. Are you seeing this crash between same versions of the MobiFlight desktop app @JaimeLeon2 where no settings upgrade is necessary? 

Yes, no settings update was necessary as far as I know. Well, maybe update to the last file opened setting.

**Comment by neilenns** [comment]
A little bit of digging and I found a Stackoverflow thread about this very issue. It is indeed caused by sudden system shutdowns.

Someone also included a little class example to save a backup of the settings file. Worth exploring:

https://stackoverflow.com/questions/3071651/how-to-catch-exception-when-loading-net-winform-app-user-config-file

**Comment by neilenns** [comment]
And here's even more info on how this can be caught early to avoid the exception. Essentially verify the validity of the file before `Settings.Default` ever gets called.

https://stackoverflow.com/questions/2269489/c-sharp-user-settings-broken
