### ISSUE TITLE
Block editing modules if the firmware is out of date

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#590]
**Is your feature request related to a problem? Please describe.**
With the introduction of board definition files it's much easier to release new firmware versions that tweak available pins or number of supported modules. This means the board definition files will no longer work with older firmware versions.

**Describe the solution you'd like**
Prevent users from modifying their attached modules if the firmware version is out of date. The board will still work for flying but edits can't be made.

**Describe alternatives you've considered**
Versioned board definition files. We even had a PR for it and agreed it was painful.

**Additional context**
This same mechanism could be used to support a `CanUpdateModules` property on board definition files, allowing people to release fully custom boards where the user shouldn't ever be able to modify the attached modules (since they are all permanently affixed to a custom PCB).

**Comment by neilenns** [comment]
This likely involves adding a new property to the MobiFlightModule class (`FirmwareIsCurrent`?) and using that in the modules dialog to set whether things can be edited.

Note that this is about being able to *edit*. You should still be able to view all the module details so you can see what pins are attached etc.

**Comment by neilenns** [comment]
I don't mind working on this either, it aligns with other long-term things I want to do anyway for custom boards.

**Comment by pizman** [comment]
My personal thoughts.....

We should fully block this !

For sure.... If a User (whatever why) still using a older MF Connector Version ( e.g. 8.x) then he must be able to work with the Firmware on the Arduino that was designed for THAT MF Connector Version!.
BUT
There should be NEVER a posibility to mixup a Firmware and a Connector Version that is not on "same Level".

My opinion.

E.g. With MF Connecotr 9.2.0  the correct Firmware is 2.0   (right ??)
So....
Every Arduino that have NOT Firmware 2.0 should be fully not available and useable within MF 9.2 Connector Version.

May i missunderstand your intention.... Why should we allow a user to work with a older Firmware? 
We not need to avoid him from Change in Settings.... We must "block" him to do this !

**Comment by DocMoebiuz** [comment]
@neilenns Do you still plan to do this any time soon so that it could make it into the next release, in 7 days.

**Comment by neilenns** [comment]
No, unlikely

**Comment by neilenns** [comment]
@DocMoebiuz This is stale, we should just close it as "never gonna do". Heck, I'd even forgotten I opened it.

**Comment by MobiFlight-Admin** [comment]
why would we not wanna do this? i think it's a cool feature that makes sense

**Comment by neilenns** [comment]
Because there are 78 other github issues 😂 I don't think there was ever any user-facing reason to open this, it was just an idea I had, and it's been sitting for more than a year. That's a sure sign it isn't important and we can/should use our dev time elsewhere.

**Comment by neilenns** [comment]
@DocMoebiuz This has been open for two years now, we're never gonna do it and should just close it to help tidy the bug list.
