### ISSUE TITLE
Add option / config file setting to disable update checks

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#592]
In situations when you are administrating a simulator for others, it makes sense to not check and display the update available -dialog at every startup. 

You likely want to install the updates yourself when you have some time reserved for testing after the upgrade.

**Comment by neilenns** [comment]
@MobiFlight-Admin Per discussions in Discord this can be closed, correct?

**Comment by MobiFlight-Admin** [comment]
Correct. Update dialog is now with auto-timeout.
