### ISSUE TITLE
clicking links on release note fixes results in broken page

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#617]
When I click the  "new features" or bugs fixed links on the release notes popup:

![image](https://user-images.githubusercontent.com/2587818/146679263-2d993a74-7a2f-4658-8f2a-bebeb41a332f.png)

It opened the link in the popup window but it had a broken stylesheet and basically stuff looked broken (cannot reproduce it now, as it now seems to load those in *Internet Explorer* even though I do have Chrome set as my default browser.

**Comment by tigert** [comment]
No wait, I realized I accidentally clicked on the older entries down the list, thats why the "move to github" is first - but the point is still the same: it opens the links in MSIE. Not even Edge, but MSIE.

**Comment by MobiFlight-Admin** [comment]
Solution idea: Change to WebViewer2

**Comment by MobiFlight-Admin** [comment]
Ok, I looked into this and the best thing would be to use the new WebView2 chromium based control that has to be installed via nuget. I will give it a try. But it would also not use the preferred Browser on your PC.

Another totally different approach could be to launch an actual browser with the regular release notes page as soon as the user clicks into the release notes. This might actually be the best compromise and short term solution.
