### ISSUE TITLE
VJoy buttons don't work anymore

### ISSUE THREAD

**Issue by pizman** [MobiFlight/MobiFlight-Connector#618]
**Describe the bug**
When using vJoy as a InputAction, button events will throw an exception and potentiometers will not work with axis.

**Steps To Reproduce**
1. Create a Input Config
2. Select a button
3. Assign a vJoy Joystick Input Action, including Button
4. Save
5. Run MobiFlight
6. Open Game Controller Settings
7. Open properties of the virtual Joystick
8. Press the button

** Expected result**
Button will show active in settings

** Actual result**
Exception is raised.

**Additional context**
Similar is true for the potentiometer.

**Comment by tigert** [comment]
I noticed VJoy button presses work for me now.

Assigning a pot @ to a vjoy axis does not seem to work.

**Comment by DocMoebiuz** [comment]
Encoders are linked with #208
