### ISSUE TITLE
New visual selector for board pin assignment

### ISSUE THREAD

**Issue by GioCC** [MobiFlight/MobiFlight-Connector#629]
**Is your feature request related to a problem? Please describe.**
When building/entering a configuration, the user does not have a clear and immediate overview of what pins are already assigned (and therefore notice possible errors), or how many pins are still available.

**Describe the solution you'd like**
I was thinking about having a sort of clickable "map" (like a checkerboard) replacing the combo boxes for pin assignment inputs.
Beside being more visible, clicking on a checkbox (not necessarily of the usual Windows style) would also make input quicker.

**Describe alternatives you've considered**
The current arrangement works fine, since all information is available, but I think the users could benefit from a reassuring visual overview.

**Comment by DocMoebiuz** [comment]
I had experimented with this too.
I will change this when I re-work the UI completely. But for now I will leave it the way it is.

**Comment by tigert** [comment]
Somewhat related to this, would perhaps be auto-sensing of input? But that would require some support in the firmware to listen to all non-assigned pins for activity.

**Comment by DocMoebiuz** [comment]
in the current UI i don't see a way to do this. I will close it but label it with UI-redesign and then i won't forget it.
