### ISSUE TITLE
Elegoo uno r3

### ISSUE THREAD

**Issue by gabfus** [MobiFlight/MobiFlight-Connector#630]
Hello is possible to use elegoo uno r3 with mobiflight? It mount atmega428p chip?

Thanks

**Comment by JaimeLeon2** [comment]
> Hello is possible to use elegoo uno r3 with mobiflight? It mount atmega428p chip?
> 
> Thanks

Yes, it is functionally identical to the arduino uno r3.

**Comment by DocMoebiuz** [comment]
@neilenns @JaimeLeon2 Closing this because I assume the Uno is recognized by MobiFlight already and no VID/PID change needed?
