### ISSUE TITLE
Settings Config Execution Speed box wording is confusing

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#634]
**Describe the bug**
In the Settings Menu, the Config Execution Speed box has a message indicating lower values gives more updates.  The wording is confusing because the scale for the slider is indicated as "Speed", therefore lower values would be expected to be less updates, not more.

**Steps To Reproduce**
1. Go to Extras, Settings, Config Execution Speed box 
2. Read wording in the lower portion below the slider

**Expected behavior**
Should say something like higher speed results in more updates.

**Actual behavior**
lower values results in more updates

**Details**
 - MobiFlight Version: 9.2.0.0
 - FlightSim: irrelevat
 - AddOn: irrelevant

**Additional context**
none

**Comment by pizman** [comment]
Agree.   
Thats pretty sure a relict of the past where we have a Polling Rate (milliseconds)
And here a lower Value ( e.g. 100ms) represent a higher rate of updates , and a higher value ( e.g. 500ms) result in slower updates.
Without see the Millisecond Value, the Text is missleading !

**Comment by DocMoebiuz** [comment]
Yes, it was not changed when I moved it from the FSUIPC page to the General Settings page.
I think at this point we could probably simply remove it completely and always set it to the fastest setting.
