### ISSUE TITLE
Precondition deletion is saved when Cancel is pressed

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#637]
**Describe the bug**
In output config wizard, preconditions tab, deleting a precondition is remembered when cancel button is pressed.

**Steps To Reproduce**
1. Go to a Precondition previously defined
2. Select the precondition
3. Remove this precondition
4. Press Cancel
5. Reenter the config wizard
6. Note the precondition was deleted

**Expected behavior**
Cancel should just exit without changing anything.

**Actual behavior**
Deleted precondition remained deleted.

**Details**
 - MobiFlight Version: 9.2.0
 - FlightSim: irrelevant
 - AddOn: irrelevant

**Additional context**
none

**Comment by pizman** [comment]
Confirm ... 9.2.0

Maybe also rethink the "Apply"  Button
Why do we need to "apply" here and not like everywhere else confirm by the OK button.
Not a big deal but pretty sure i miss over the years 50+ Preconditions in case i forget to press Apply and just click OK

**Comment by JaimeLeon2** [comment]
I don't have a problem with the Apply button, as I may want to enter more than one precondition.  I do agree that pressing Ok, should apply the current precondition entered before exiting.  Pressing Ok without pressing Apply has happened to me multiple times too.

**Comment by DocMoebiuz** [comment]
I find the apply button also not ideal.
And the behavior with cancel should definitely not happen.

**Comment by DocMoebiuz** [comment]
@JaimeLeon2 can you please confirm that this is resolved in the latest beta 9.2.0.3?

**Comment by JaimeLeon2** [comment]
Confirming the issue is fixed.
