### ISSUE TITLE
MF Connector can incorrectly show MF WASM module is installed (when it is not)

### ISSUE THREAD

**Issue by ssewell** [MobiFlight/MobiFlight-Connector#640]
**Describe the bug**
If the MF WASM module isn't installed but the sim is running, MF Connector will indicate it the WASM module is installed, but communication with MSFS will be broken.

**Steps To Reproduce**
1. Remove mobiflight-event-module from the MSFS Community folder
2. Launch MSFS and confirm the mobiflight-event-module isn't present in the DevMode packages
![image](https://user-images.githubusercontent.com/2242776/148014820-50401ac2-97f0-4881-931c-9590a3795174.png)
3. Launch MobiFlight and observe that it indicates that WASM module is present even though it's not installed
![image](https://user-images.githubusercontent.com/2242776/148014888-dc5291a5-2412-47df-94b0-4f078e84ec82.png)

**Expected behavior**
Sim Status at the bottom of the MF window would indicate the WASM module is missing.

**Actual behavior**
Sim Status at the bottom of the MF indicate the WASM module is installed.

**Details**
 - MobiFlight Version: 9.2.0
 - FlightSim: 1.21.13.0

**Comment by neilenns** [comment]
I took a quick look at this and it's more complicated than I thought it would be. The "WASM Module (MSFS2020)" text isn't actually an indication of the WASM module being installed. It's simply the text shown to indicate that SimConnect is used to communicate with FS2020:

https://github.com/MobiFlight/MobiFlight-Connector/blob/3792b5630b08aca62e206d80aea2c1731f170113/UI/MainForm.cs#L700-L705

I'm not sure there's any property anywhere that actually indicates whether the WASM module is installed.

**Comment by JaimeLeon2** [comment]
That is very weird.  In my mind, I thought that the "MSFS2020 detected" flag was for SimConnect and the "WASM Module (MSFS2020)" flag was to indicate that the wasm module was installed and alive.

**Comment by ssewell** [comment]
Was a misunderstanding on my part as well. I'll keep this in the back of my mind, will investigate possibilities for detection. A few that come to mind:
 - Check for the presence of the file based on the installation location (not ideal, but would better than nothing)
 - Try a round trip test when the SimConnect connection is first established (e.g. write the current ticks to L:MF_Connector_Active then attempt to read it via SimConnect to ensure the value can be written and subsequently read)

**Comment by DocMoebiuz** [comment]
No, no - the green check mark should be the indication and I find it awkward too if the green check mark indicates that the WASM module is OK when it is not
