### ISSUE TITLE
Incorrect update of pin selection combo boxes

### ISSUE THREAD

**Issue by GioCC** [MobiFlight/MobiFlight-Connector#643]
**Bug Description**
When changing values of assigned pins, selection lists of other pins of the same device do not update correctly.

Example below (using an InputShifter for convenience, but the behaviour is the same regardless of the device - not tested on ALL devices but on several ones).

**Steps To Reproduce (example)**
1. Initial configuration: used pins 19, 20, 21
![Screen Shot 01-05-22 at 09 32 PM](https://user-images.githubusercontent.com/25667790/148287502-d5fa44f7-d1c9-46a1-b910-ff6dd562f01b.PNG)

2. "Latch" pin is changed to 31.
![Screen Shot 01-05-22 at 09 33 PM 001](https://user-images.githubusercontent.com/25667790/148287524-b9516406-25f3-4596-b73c-badffc7e83b8.PNG)

3. Reopening the combo box for a check, 21 appears as free pin [OK].
  (Pin 31 appears as "free"="assignable", because currently assigned [OK])
![Screen Shot 01-05-22 at 09 34 PM](https://user-images.githubusercontent.com/25667790/148287548-46d74892-6e85-4609-9a7c-c6ec16eb7464.PNG)

4. Opening the box for "Clock" pin, 21 does not appear as free but 31 does [EXPECTED: the reverse]  
And so on for other selectors.
![Screen Shot 01-05-22 at 09 34 PM 001](https://user-images.githubusercontent.com/25667790/148287559-bd5e0472-8610-4a66-9517-277d2fdf1b35.PNG)

**Details**
 - MobiFlight Version: 9.2.0

***==>Working on a fix, will submit PR shortly.***

**Comment by DocMoebiuz** [comment]
Super cool to see the screen shots!

Yeah the pins don't update on the fly. Only on changing the module.
