### ISSUE TITLE
Native X-plane support

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#648]
**Is your feature request related to a problem? Please describe.**

FSUIPC API has historical reasons for existing and why it is like it is. While it works, it is cumbersome and it should not be that difficult to set up your cockpit controls.

MSFS2020 "native" support has shown things can be much easier for the end user.

We have discussed about implementing X-Plane connection using the X-plane API for a while, but I did not see an actual feature request. I also recognize this is a larger issue that needs proper planning and discussion and perhaps has dependencies on other ideas down the roadmap, thus this issue serves more like a pointer to the Github Discussion Topic about X-plane and what it takes to get this done. [So if you are interested in helping, or have thoughts or ideas, please join the discussion](https://github.com/MobiFlight/MobiFlight-Connector/discussions/647).

**Comment by pizman** [comment]
Basically i agree....
But like always i ask myself " Whats the Usecase"
Simple question.....
What user will need this ?

Xplane Users will no longer grow up.   For sure those guys who love it will remain there and not swap to FS2020.
But new user pretty sure not choose for a old Sim with poor technique when they be able to order FS2020 already.
Same time we need to accept.   Xplane Homecockpits are done 90%+ by SimVim.... Simply cause they still support the Xplane API.

**********
4 Years ago i would say this feature is a Milestone and a Must Have!  There we had the chance to gain 1000+ new MF USers.  
Now after FS2020 Release i will say this is just a low priority Point for some rare users who not can say good bye to the still dying Xplane !

So our "target" group is pretty small.....   Only People who like to use FS2020 and Xplane same time parallel.
All others will remain in SimVim OR not need Xplane cause they fully swap to FS2020!

**Comment by tigert** [comment]
I think x-plane is not a dying sim. 

The reason Mobiflight is not that popular with x-plane could also be because you are forced to work with FSUIPC API and offsets.

**Comment by ChrisInUT** [comment]
@DocMoebiuz, it appears that there are two ways to call commands in X-Plane.  When you use the DataRefTool plug-in, you are given two options 'Command press' and 'Command once'.  While the 'Command once' does activate the command, in the sim the affected control's visible state does not change. 
![image](https://user-images.githubusercontent.com/104312293/172018291-134a1727-5b26-4854-b21f-e04fe8b3d02b.png)
I would propose that the user be given the option of which method of firing the command is used.

**Comment by DocMoebiuz** [comment]
i am aware of that and the library i found to connect to xplane does kind of support it.

For mobiflight however it's a bit more of a challenge. It would require "repeat" or onPressed or something.
