### ISSUE TITLE
Trigger Stop() on all device types when stopping MobiFlight

### ISSUE THREAD

**Issue by DocMoebiuz** [MobiFlight/MobiFlight-Connector#657]
**Is your feature request related to a problem? Please describe.**
Outputs, LED 7 Segment Displays and stepper are set to Stop() on MobiFlightCache.Stop()

**Describe the solution you'd like**
All device should have a Stop method which should be called. Currently the Servos don't go back to 0 position. I am not sure about OutputShiftRegister.

**Describe alternatives you've considered**
not call it.

**Additional context**
none.

**Comment by neilenns** [comment]
Output shifters also don't get stopped, confirmed today. I was going to write the code to take care of all of this but got sidetracked because my output LEDs on my de-ice panel (that use output shifters) don't seem to be working anymore. Sigh. Gonna have to get out the logic analyzer.
