### ISSUE TITLE
Duplicate Hubhop Events

### ISSUE THREAD

**Issue by sojatay** [MobiFlight/MobiFlight-Connector#659]
**Describe the bug**
The Hubhop file "msfs2020_eventids.cip" and also the   "events.txt" in the Community\mobiflight-event-module\modules folder both contain duplicate entries (currently 25 as at 15 January) as follows:
(my strings below for ease of reading are "Group :: Event")

Aerosoft/CRJ 550-700-1000/Avionics :: ASCRJ_ECAM_AICE
    Aerosoft/CRJ 550-700-1000/Avionics :: ASCRJ_ECAM_CAS
    Aerosoft/CRJ 550-700-1000/Avionics :: ASCRJ_ECAM_DOORS
    Aerosoft/CRJ 550-700-1000/Avionics :: ASCRJ_ECAM_DOWN
    Aerosoft/CRJ 550-700-1000/Avionics :: ASCRJ_ECAM_ELEC
    Aerosoft/CRJ 550-700-1000/Avionics :: ASCRJ_ECAM_FCTL
    Aerosoft/CRJ 550-700-1000/Avionics :: ASCRJ_ECAM_FUEL
    Aerosoft/CRJ 550-700-1000/Avionics :: ASCRJ_ECAM_HYD
    Aerosoft/CRJ 550-700-1000/Avionics :: ASCRJ_ECAM_MENU
    Aerosoft/CRJ 550-700-1000/Avionics :: ASCRJ_ECAM_SEL
    Aerosoft/CRJ 550-700-1000/Avionics :: ASCRJ_ECAM_STAT
    Aerosoft/CRJ 550-700-1000/Avionics :: ASCRJ_ECAM_UP
    Aerosoft/CRJ 550-700-1000/Flight Instrumentation :: ASCRJ_LSP_BRG1
    Aerosoft/CRJ 550-700-1000/Flight Instrumentation :: ASCRJ_LSP_BRG2
    Aerosoft/CRJ 550-700-1000/Flight Instrumentation :: ASCRJ_LSP_RDR
    Aerosoft/CRJ 550-700-1000/Flight Instrumentation :: ASCRJ_LSP_SEL
    Aerosoft/CRJ 550-700-1000/Flight Instrumentation :: ASCRJ_LSP_SPEED_MODE
    Aerosoft/CRJ 550-700-1000/Flight Instrumentation :: ASCRJ_LSP_SPEED_SEL
    Aerosoft/CRJ 550-700-1000/Flight Instrumentation :: ASCRJ_LSP_SPEED_SEL
    Aerosoft/CRJ 550-700-1000/Flight Instrumentation :: ASCRJ_LSP_SPEED_SEL
    Fly By Wire/A320/Lights :: ANN_LT_BRT
    Fly By Wire/A320/Lights :: ANN_LT_DIM
    Fly By Wire/A320/Lights :: ANN_LT_TEST
    Microsoft/Generic/Unsorted :: ATC_MENU_8
    PMDG/DC-6/Autopilot :: PMDGDC6_AP_ALT_HOLD_TOGGLE

 loadEventPresets() in SimConnectCache.cs does not check for duplicates, so the Events dictionary carries these duplicate entries.

**Steps To Reproduce**
 Download the files!

**Expected behavior**
No duplicates

**Actual behavior**
Duplicates exist

**Details**

**Additional context**

Suggested fix (easy):

Wrap a check for duplicates in the 2 lines in SimConnectCache.cs which currently read:

        Events[GroupKey].Add(new Tuple<string, uint>(cols[0], EventIdx++));

    .....  to read as follows:

     if (!Events[GroupKey].Exists((tup) => tup.Item1 == cols[0]))
            {
                Events[GroupKey].Add(new Tuple<string, uint>(cols[0], EventIdx++));
            }

**Comment by DocMoebiuz** [comment]
This is now deprecated with Release 9.3 because we dont care about label names anymore.
