### ISSUE TITLE
Version 9.2.0.2 does not recognize Joystick commands

### ISSUE THREAD

**Issue by MARCELOHIDALGOMARTINS** [MobiFlight/MobiFlight-Connector#664]
**Describe the bug**
In the beta update, the two-button commands I use on my joystick (Logitch Extreme 3D) by MobiFlight stopped working, despite appearing in the InputConfigWizard, when I activate DEBUG the error message appears.
I downgraded to the stable version (9.2.0) and it started working again.

![debug joy](https://user-images.githubusercontent.com/84933031/150020105-8fb94979-2a01-47f0-b40b-843947b35912.jpg)

**Comment by DocMoebiuz** [comment]
Hi Marcelo, I checked on my end and I can say that for my joystick the input events are detected correctly and also the according config is detected correctly.
I reviewed the changes and i cannot find anything.

Can you please post the log from 9.2.0 where it is able to execute the event.

And can you please attch your config

**Comment by MARCELOHIDALGOMARTINS** [comment]
The image below shows the DEBUG reports of the two buttons I use on my Joystick, working with the stable version of MobiFlight 9.2.
![debub_ok](https://user-images.githubusercontent.com/84933031/150605684-1f10cd1b-3e1f-410f-8845-8e0c08936ca1.jpg)
0

**Comment by DocMoebiuz** [comment]
I cannot reproduce it yet.

**Comment by DocMoebiuz** [comment]
I was able to reproduce it and it is fixed.

**Comment by MARCELOHIDALGOMARTINS** [comment]
Thanks!!!
