### ISSUE TITLE
XPUIPC manual refresh needed in X-plane to get Mobi modules to synch

### ISSUE THREAD

**Issue by teropart** [MobiFlight/MobiFlight-Connector#673]
Upon loading an airplane in X-Plane 11 (e.g. Zibo 737), and running set of Mobi based Arduino modules (Com, Nav, with backlight), the X-Plane interface for Mobi, XPUIPC, needs manual "refresh" for the units to be fully in synch with backlighting and frequencies.

In XPUIPC performance settings menu there is "refresh datarefs" button that needs to be pressed for the HW to synch fully. Without doing this the backlight adjustment for example via Mobi is not working at all.

MF Connector 9.2.0
Mobi Arduino FW 2.0.0

**Comment by pizman** [comment]
Is this a MF Related Problem ?

Sounds to me "XPUIPC" simply not get updated when you swap your Aircraft.
How should MF change this ?  We only use the XPUIPC interface.... Not controll XPUIPC itself or its PlugIn in the Sim!

may i missunderstand ?

**Comment by DocMoebiuz** [comment]
With the new native xplane interface (#826, #648) this has become obsolete.
