### ISSUE TITLE
Allow copying content from the new logging window

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#702]
The new logging output window is super fast (yay!) but doesn't support copying. It would be really handy for debugging purposes if people could copy the text from the output window so it can be pasted in places like Discord chat. Right now the only option is to take a screenshot which is a pain if you want to get a VID/PID out of the logs.

**Comment by DocMoebiuz** [comment]
what about the log.txt file?

**Comment by DocMoebiuz** [comment]
pausing the log window would be cool - and maybe even filtering by debug level or text - and then it would make sense to have a copy option - yeah...

**Comment by neilenns** [comment]
Then I have to explain to users how to go find the log.txt file. Much easier to just tell them to copy the line out of the debug window.

Yes, pause would be spectacular.

**Comment by tigert** [comment]
It could inhibit autoscrolling if you either select something or scroll manually away from the end?

Also, repeating log messages could be grouped together (so if the log is the same but only the timestamp is changing)

![image](https://user-images.githubusercontent.com/2587818/155221328-8b078d69-31c3-4f18-b0ae-0c0a5e8ccd83.png)

So these could be :
![image](https://user-images.githubusercontent.com/2587818/155222874-e39a61a7-5dfe-4174-98f6-af3fe88ec68e.png)

**Comment by neilenns** [comment]
All cool ideas. Go open other wishlist items for them 😂 I just want copy support!

**Comment by DocMoebiuz** [comment]
@neilenns - hey, look at that - #good-first-issue - give it a shot! 😂

**Comment by neilenns** [comment]
Wait, now it's assigned to me @DocMoebiuz how did that happen? l🤔
