### ISSUE TITLE
Show progress bar while updating events from Hubhop 

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#720]
**Is your feature request related to a problem? Please describe.**
Updating events in MFConnector from Hubhop takes about 20 seconds, depending on network conditions.  After pressing the update option in the menu, no indication of action is given until after the update is complete.  The user has no idea if Mobiflight is executing the update or not.

**Describe the solution you'd like**
I propose to display a simple progress bar that reassures the user that his command is being executed and how fast this task is moving to completion.  The progress % can be shown over the moving bar.

**Describe alternatives you've considered**
Display a simple box saying "Update in Progress" while the action takes place is better than nothing, but is not as cool as a moving bar and %. 

**Additional context**
I have no idea what happens if the update fails for any reason.  Is the events database intact in Mobiflight until after the download is completed and the new event files then replace the previous files?  Is there an error message telling the user the action failed and he should try later?

**Comment by DocMoebiuz** [comment]
Yeah nice! I had the same idea the other day when it took a couple of seconds.
