### ISSUE TITLE
First character in Event Description Field comes in Lower Case

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#730]
**Describe the bug**
When entering a new event in MF with Caps Lock on, the first letter comes out in lower case.

**Steps To Reproduce**
1. Go to the bottom of MF main list view
2. Have your keyboard with Caps Lock on.
3. Single click on the last line to add a new event (I know it says to double click, but the same occurs with an existing config)
4. Begin typing the name of the config... for example BATTERY MASTER ON
5. Note that the first letter is in lower case for no apparent reason.

![image](https://user-images.githubusercontent.com/86563553/157703794-72df82da-b3bc-4106-a7cb-46bbd587131f.png)

**Expected behavior**
Caps lock is on, so all letters should be entered as upper case.

**Actual behavior**
The first letter comes up as lower case wit the rest of the text in upper case.

**Details**
 - MobiFlight Version: 9.3.0
 - FlightSim: irrelevant
 - AddOn: irrelevant

**Additional context**
The issue happens only when entering the description without having double clicked first and with Caps lock on.

**Comment by neilenns** [comment]
That's crazy! You're right, it only happens if you single click on the row first and have caps lock on. If you double click on the row the problem doesn't happen.

**Comment by DocMoebiuz** [comment]
i don't recall that i am doing anything special - this must be default behavior of the control. I plan to replace it soon anyways. It's the last control that prevents me from having proper high dpi support.

**Comment by neilenns** [comment]
> i don't recall that i am doing anything special - this must be default behavior of the control. I plan to replace it soon anyways. It's the last control that prevents me from having proper high dpi support.

That was my thought too @DocMoebiuz but it turns out you were doing something special. I opened a PR to fix it, easy fix.

**Comment by DocMoebiuz** [comment]
it's funny when i saw it - Obviously i had noticed this already and only had implemented the Shift case but not Caps Lock
