### ISSUE TITLE
Output config does not remember state of "Show Preset Code"

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#731]
**Describe the bug**
The output config wizard does not remember the state of the "Show Preset Code" checkbox.

**Steps To Reproduce**
1. Create an Output config
2. Select variable from dropdowns, e.g. Microsoft/Generic/Miscellaneous ELECTRICAL MASTER BATTERY
3. Put checkmark in the Show Preset Code box
4. Press Ok.
5. Reenter the same configuration.
6. Note that the Show Preset Code box is unchecked.

**Expected behavior**
Config wizard should remember the state of the checkbox.

**Actual behavior**
The state of the checkbox is reset back to unchecked.

**Details**
 - MobiFlight Version: 9.3.0
 - FlightSim: irrelevant
 - AddOn: irrelevant

**Additional context**
This issue appears only when the Preset code is not modified.

**Comment by DocMoebiuz** [comment]
This is not currently implemented like this. I don't think it is necessary. As soon as it is a customized preset, the Show Code will be activated. But if you use a preset and don't change it, there is no need to show it the next time you load the preset. You will still see the correct preset name. If you want to inspect it for reviewing purpose then you have to click "show preset code".

This is not like with the expansion box of the custom code textfield. for the textfield it makes sense that MF remembers your decision.
