### ISSUE TITLE
Wrong board type used if duplicated entries in registry

### ISSUE THREAD

**Issue by DocMoebiuz** [MobiFlight/MobiFlight-Connector#733]
**Describe the bug**
My Arduino Pro Micro could not be flashed because MF thought it was a Mega. The issue is that I have two valid module entries in the registry and they both point to COM3 which was the port that my Pro Micro was connected to.

**Steps To Reproduce**
1. Connect a Mega
2. Connect a Pro Micro
3. Disconnect the Mega
4. Open Registry Editor
5. Search for the Mega entry in HKEY_LOCAL_SYSTEM/CurrentControlSet/Enum/USB/{CORRECT VID PID}/{INSTANCE ID}/Description
6. Change the Port value to the same Port value that your ProMicro is using
7. Flash ProMicro with EEPROM clear sketch
8. Start MF

**Expected behavior**
ProMicro is detected as ProMicro Module based on the VID/PID.

**Actual behavior**
ProMicro is detected as Mega Module because MF finds two entries for the Port and takes the first one it finds.

**Comment by neilenns** [comment]
Hmmmmm. I'm not sure how we should handle this. It's kind of a variation of multiple matching VID/PIDs: in the end there will be two possible configs that could be flashed and we won't know which one to use.

**Comment by DocMoebiuz** [comment]
this is actually a different problem. in my case i have two distinguishable VId/PID combos and still the current way of trying to determine the boards VID PID connected to a COM port doesn't always yield the correct information.

So apparently i had a mega connected to COM3 in the past, but now only the pro micro is connected to COM3 - yet the enumerations finds both entries in the registry, returns both and MF uses the first one which is the wrong one.

MF should really try to get access to the device information as displayed in the Device Manager for the device that is connected at COM3 at the moment.

**Comment by neilenns** [comment]
I agree it's a different problem but the outcome is the same: there's more than one possibility and MobiFlight doesn't know which one to use.

At any rate, looking at the code, this issue has been around for a long time. Even the old pre-board code simply threw its hands up and logged an error about a duplicate COM port being detected.

**Comment by DocMoebiuz** [comment]
i am not saying it was any different before but it's a bug that I stumbled over yesterday when Ralf and I were looking into a firmware flashing problem.

**Comment by neilenns** [comment]
Doc suggested WMI in Discord. Am digging into that, looks quite promising.
