### ISSUE TITLE
Led display number dropdown doesn't populate correctly

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#755]
**Describe the bug**

When configuring an LED module with multiple connected displays (in my case 8), the dropdown to select the specific display when configuring an output doesn't correctly populate with the number of connected displays.

**Steps To Reproduce**
1. Configure an LED module with more than one display (e.g. 8)
2. Configure an output and try to select the 8th module

**Expected behavior**
The dropdown has 8 values in it.

**Actual behavior**
The dropdown only has 2 values in it.

![image](https://user-images.githubusercontent.com/9524118/161771344-2e1ed6df-42a8-49e3-80a0-1f781fe22e79.png)

**Additional context**
If you re-select the module in the addr / connector dropdown then the number dropdown re-populates correctly.

**Comment by DocMoebiuz** [comment]
**WORKAROUND FOR NOW:**
If you re-select the module in the addr / connector dropdown then the number dropdown re-populates correctly.
