### ISSUE TITLE
Return list of valid boards instead of a single board

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#756]
This is the first step towards dealing with different Arduinos sharing the same USB chip. Instead of only returning a single matching board from the list of matching boards return the list of all valid boards, but only use the first one (to keep current detection behaviour the same).

In later work Sebastian will use this to put up UI to prompt the user to confirm the board type.

**Comment by tigert** [comment]
I am attaching these here so we can keep track of the board icons better than dropping files on discord.

Uno:
![board-uno](https://user-images.githubusercontent.com/2587818/161902658-959229cf-09b7-4fbb-babb-bfccd42c2c2f.svg)

Mega:
![board-mega](https://user-images.githubusercontent.com/2587818/161902661-ca3f5906-731a-4782-9729-47c04e041441.svg)

Mega Mini (we can still show it in a list even though it is just a "mega" technically)
![board-mega-mini](https://user-images.githubusercontent.com/2587818/161902664-3c07d7fc-51a1-468e-a47a-121b6883fe18.svg)

Pro Micro:
![board-pro-micro](https://user-images.githubusercontent.com/2587818/161902665-6f8fa341-26ac-4fc2-bafd-4a387896b091.svg)

**Comment by tigert** [comment]
I have now slightly adjusted images for mega, uno, nano, pro micro and mega pro (mini):

![image](https://user-images.githubusercontent.com/2587818/168025691-baea51d2-e55c-46ce-b926-9f0d9600f419.png)

@DocMoebiuz I can make a pull request to Connector, should these live next to the board json files so they are logically together? PNG I guess is easier to show in the UI, but I think we should have the SVG around too in case we need to edit these later.
