### ISSUE TITLE
Log when execution time for configs exceeds timer interval

### ISSUE THREAD

**Issue by DocMoebiuz** [MobiFlight/MobiFlight-Connector#762]
**Is your feature request related to a problem? Please describe.**
I am interested in knowing if people actually have so many config entries so that they skip a execution cycle.

**Describe the solution you'd like**
Log and add to telemetry if that happens.

**Comment by pizman** [comment]
Nice Idea.
Again here our friend Karl can be a good indicator.
Pretty sure there exist more complex configs like his file.
But if there is no problem for him then there is no problem for 99% of Users!
