### ISSUE TITLE
Rethink of the "Sim Status" Indicator for Dual Connections.

### ISSUE THREAD

**Issue by pizman** [MobiFlight/MobiFlight-Connector#764]
**Is your feature request related to a problem? Please describe.**

Badly the Sim Status is Green and indicate a perfect running system whatever just ONE System is currently working.
For FSX/P3D/XP users this is nice.... they only use FSUIPC.
For WASM Only Users this is also Nice.
But what about people who use FSUIPC7  **and** WASM ?
Here we have still reports from users who have a lot of Red "!" on there Configs  ( e.g. in case of missing simconnect)
but same time the Sim Status was green cause FSUIPC is still active that time. 
Same if they use FSUIPC for some Configs and it is not loaded.  System not work whatever the Status is green.

**Describe the solution you'd like**
I don´t know
In case there are users who only need one system the current logic is correct.
For those who use both.... Its Confusing if only one is lost connection only
Maybe a Duplicated Field next by would be a idea.  So there is no Dropdown and we have a own field for each Typ.

![grafik](https://user-images.githubusercontent.com/26087116/162623695-69d921fe-af81-4bc1-98df-2ac583f37477.png)

**Comment by JaimeLeon2** [comment]
Maybe check at start if any config uses Fsuipc, if so, green mark only if Fsuipc connection is established. Same for Msfs2020.

**Comment by DocMoebiuz** [comment]
I will think about it. I think Jaime's idea is helpful. Showing more information in the status bar next to each other.. I don't know.

**Comment by DocMoebiuz** [comment]
> Maybe check at start if any config uses Fsuipc, if so, green mark only if Fsuipc connection is established. Same for Msfs2020.

I was thinking about it again, and I have to say that is what the red icons are indicating at the moment.
I was thinking to combine the icon, half warning, half green.

**Comment by DocMoebiuz** [comment]
Solution:
* When a config item is detected that requires a sim connection and the config item is marked with the errortext, we can fire an event "OnSimRunningRequiredError"
* MainForm can subscribe to this event and set the status to a warning icon.
