### ISSUE TITLE
XPUIPC Config file user-defined language for Notepad++

### ISSUE THREAD

**Issue by ChrisInUT** [MobiFlight/MobiFlight-Connector#768]
I have created a user-defined language for Notepad++. For those using Notepad++ to edit their XPUIPC config file may find this useful.  Just import it under the Language menu.  The colors scheme is set up for DarkModeDefault, but feel free to change the colors to your liking once you have imported it.

The attached zip file contains a single .xml file that defines the language.

[XPUIPC.zip](https://github.com/MobiFlight/MobiFlight-Connector/files/8550016/XPUIPC.zip)

Sebastian suggested I submit this via an issue on GitHub....

**Comment by MobiFlight-Admin** [comment]
can you please create a short explanation here: https://github.com/MobiFlight/MobiFlight-Connector/wiki/XPUIPCOffsets.cfg-Notepad---plugin

You can link to the file here, or attach it also to the page directly.

**Comment by MobiFlight-Admin** [comment]
please se

**Comment by ChrisInUT** [comment]
@MobiFlight-Admin 
I have created a page with screenshots of the installation steps using the link that you provided.  Let me know if there is anything that you would like changed.

**Comment by MobiFlight-Admin** [comment]
Cool! We can leave it like this and based on user feedback add or change anything later.

Thanks!
