### ISSUE TITLE
Filter reset does not deselect current event

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#769]
**Describe the bug**
In the Input config wizard, with a preselected event, pressing the filter reset button blanks the filter selection, but does not deselect the current event. 

**Steps To Reproduce**
1. Go to an existing Input config
2. Click on 'filter reset' 
3. Note filter selection changed to Show All
4. Clicking on any filter shows only the category of the current event. 
5. User has to manually change the current event to Show All. 

**Expected behavior**
Reset filter should also reset the selected event so that the filter drop downs show all options. 

**Actual behavior**
Current selected event is not reset. Drop down filters cannot be used. 

**Details**
 - MobiFlight Version: 9.3.2
 - FlightSim: irrelevant 
 - AddOn: irrelevant 

**Additional context**

**Comment by DocMoebiuz** [comment]
cannot be reporduced.
