### ISSUE TITLE
Exception when trying to select a stepper during output mapping

### ISSUE THREAD

**Issue by GioCC** [MobiFlight/MobiFlight-Connector#774]
**Describe the bug**
When trying to select a stepper unit in the ConfigWizard, an exception is raised.

**Steps To Reproduce**
1. Define a new module containing 2 steppers.
2. Go to the "Output" config tab and start the definition of a new entry; open the Config wizard with the "Edit..." button.
3. Go to the "Display" tab.
4. Choose -> "Output device", Module -> the newly defined module, "Use type of" -> select "Stepper"
5. Try and select any item in the "Stepper" combo box; an unhandled exception occurs.

**Details**
MobiFlight Version: Commit 2022-04-24

**Comment by GioCC** [comment]
I found the issue below and potentially fixed it; the fix seems sensible and working, however there are a few points that make me wonder whether the configuration is handled correctly.

See code below (my comments are marked with ">>>"):

File: `DisplayPanel.cs`

```
    private void StepperPanel_OnStepperSelected(object sender, StepperConfigChangedEventArgs e)
    {
        String stepperAddress = e.StepperAddress;
 //>>> Current offending line:
        //String serial = SerialNumber.ExtractSerial(config.DisplaySerial);
 //>>> Reason: 'config' contains null values! 
 //>>> Where is it set, and how should it be correctly set?
 //>>> This correction seems to work (after all the serial No. can be found there):
        String serial = SerialNumber.ExtractSerial(displayModuleNameComboBox.SelectedItem.ToString());

        MobiFlightStepper stepper = _execManager.getMobiFlightModuleCache()
                                        .GetModuleBySerial(serial)
                                        .GetStepper(stepperAddress);
        
 //>>> Data from just retrieved 'stepper' object are apparently not used (i.e. copied in the form controls): ???
 //>>> except for this one:
        stepperPanel.ShowManualCalibation(!stepper.HasAutoZero);
 //>>> consequently they appear not to be saved either...?
        
 //>>> BTW there's this comment also:
        // sorry for this hack...
    }
```

I'm not very familiar with steppers (almost never used them except for testing), so I could really do with a check from someone who is.

**Comment by DocMoebiuz** [comment]
thanks for trying to fix it - i already had fixed it locally on my branch. Sorry!

**Comment by GioCC** [comment]
No worries, it wasn't a difficult one.
However, any indication on the other questions (where are the other parameters saved)?
