### ISSUE TITLE
Boards with FTDI chips are not recongnized anymore

### ISSUE THREAD

**Issue by elral** [MobiFlight/MobiFlight-Connector#780]
**Describe the bug**
With the new USB detection boards with FTDI chip gets not detected.

**Steps To Reproduce**
1. Connect a board with FTDI chip (e.g. Mega2560 clone)

**Expected behavior**
Board should get recognized.

**Actual behavior**
This board does only show up as unknown board.

**Details**
- latest version of MF

**Additional context**
See also attached log file.

As per @neilenns advice, with adding `^COMPORT&VID_0403&PID_6001` as a VID/PID entry to arduino_mega.board.json the board gets detected and changes/additions/deletions are possible.

**Comment by neilenns** [comment]
The easy fix is to just add this entry to the `.board.json` file.

A more complete fix would be to add some code to clean up the `COMPORT&` that's at the front and have a vid/pid that matches how everything else works.
