### ISSUE TITLE
Input device change not correctly registered in the .mcc file

### ISSUE THREAD

**Issue by zorzini** [MobiFlight/MobiFlight-Connector#782]
**Describe the bug**
If in an existing Input line a switch belonging to a Shift Register is replaced with a switch connected directly to the Arduino, it is not correctly registered in the configuration file xx.mcc.

**Steps To Reproduce**
- Create an empty configuration
- Add an Input for a switch belonging to a Shift Register
- Save and run
- Correct operation
- Replace the previously added switch with one connected directly to the Arduino
- Save and run
- The switch is not detected
- In the Debug Log "No Config Found"

**Expected behavior**
- The switch should be detected and the configuration applied

**Actual behavior**
The code starting from - inputShiftRegister ExtPin="6" - remains in the xx.mcc file
```
 <inputs>
    <config guid="03e0011f-ae84-4a9a-a244-0e5327708236">
      <active>true</active>
      <description>AP SWITCH</description>
      <settings msdata:InstanceType="MobiFlight.InputConfigItem, MFConnector, Version=9.3.2.1, Culture=neutral, PublicKeyToken=null" serial="MF2022-Mega-01/ SN-c55-9c1" name="LIGHTS-SW-1" type="Button" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
        <button>
          <onPress type="MSFS2020CustomInputAction" command="(L:AUTOPILOT_onoff,bool) ! (&gt;L:AUTOPILOT_onoff,bool)" presetId="09e39c86-2375-4c78-9f83-c2a02224b11f" />
          <onRelease />
        </button>
        <inputShiftRegister ExtPin="6">
          <onPress type="MSFS2020CustomInputAction" command="(L:AUTOPILOT_onoff,bool) ! (&gt;L:AUTOPILOT_onoff,bool)" presetId="09e39c86-2375-4c78-9f83-c2a02224b11f" />
          <onRelease />
        </inputShiftRegister>
        <preconditions />
        <configrefs />
      </settings>
    </config>
  </inputs> (modificato)
```
By manually removing the **Bold** part the new switch works correctly

**Details**
 - MobiFlight Version: 9.3.2.1

**Comment by DocMoebiuz** [comment]
@neilenns have you had the chance to work on this?

**Comment by neilenns** [comment]
Not yet sorry. If you want to take it go ahead, I likely can't touch it until Sunday.

**Comment by DocMoebiuz** [comment]
@neilenns I am in a flow at the moment... I am trying to fix the saving portion of it first.

**Comment by DocMoebiuz** [comment]
I actually found the problem. It really had something to do with the inputshiftregister logic in the event execution.
