### ISSUE TITLE
Max Encoder Devices wrong on MicroPro

### ISSUE THREAD

**Issue by pizman** [MobiFlight/MobiFlight-Connector#784]
**Is your feature request related to a problem? Please describe.**
Max Encoders on Micros are limited to 5

**Describe the solution you'd like**
Buttons are 18 possible in Firmware
So its logical to allow 9 Encoders ( instead of 5 a.t.m.)  ( Cause there must be 18 Pins already)

**Describe alternatives you've considered**
None

**Additional context**
I don´t know if this limit have a other reason.
If its just cosmetical.... i vote for a fix in next Full release .

**Comment by elral** [comment]
The limitation of 5 encoders came from the limites RAM space before all optimzations were implemented. Meanwhile with all these optimazations the max. number of encoders could be increased to 9 as proposed. The required RAM size will increase just by 8 Bytes (2 Bytes for each encoder).
I will open an issue also on the firmware repo and refer to this issue.
