### ISSUE TITLE
Analog input event data not being saved in 9.3.2.2

### ISSUE THREAD

**Issue by peterholt533** [MobiFlight/MobiFlight-Connector#797]
Saving a config file in 9.3.2.2 beta results in input settings for any analog configs being lost.  Examining the .mcc file shows that all data between the analog tags, and the tags themselves are not written to the file.

**Comment by tigert** [comment]
Oh, I also noticed this but forgot to file an issue yesterday, thanks for the reminder. 

Reproduceable always, and it happens during file save it seems.

I can load an existing file with potentiometer configs, and it works fine, and I can also create a new potentiometer config and it works fine in the current Mobiflight session, but it is just not saved.

Also, if I load a working file with analog configuration items, it loads correctly, but if I save it to a new file without editing anything, the analog config data is also then lost, so maybe it is not related to the configuration dialog but rather in the file saving functionality.

**Comment by MobiFlight-Admin** [comment]
i did a modification to only write the device that really is used in the config - so maybe that it. What a strange thing that the Unit Tests didn't catch it
