### ISSUE TITLE
Disabling a Precondition using Apply reverts to Enable

### ISSUE THREAD

**Issue by morrie-morrie** [MobiFlight/MobiFlight-Connector#804]
**Describe the bug**
When Disabling a Precondition for both Outputs and Inputs, using Apply reverts change back to Enable.

**Steps To Reproduce**
1. Go to a Configuration
2. Click on Precondition 
3. Create a Precondition and tick the Enable Tick box and Apply. This works OK.
4. Now Remove the tick box from the Precondition and click on Apply.
5. After clicking Apply, the Tick box is reinstated next to the Precondition reenabling the Precondition.
6.  Only way to disable is to remove tick and to click on OK.

**Expected behavior**
Changing the Status of the Precondition to Disable and clicking apply should disable the Precondition.

**Actual behavior**
Changing the Status of the Precondition to Disable and clicking apply, enables the Precondition.

**Details**
 - MobiFlight Version: [e.g. 9.3.2.3]
 - FlightSim: [MSFS2020] (But doesn't matter)
 - AddOn: [FBW A32x] (But doesn't matter)
 - 
**Additional context**

None.

**Comment by DocMoebiuz** [comment]
True. The checkbox is saved independently. And with apply the checkbox is always enabled.

**Comment by DocMoebiuz** [comment]
The precondition dialog requires more rework (add / remove a precondtion is only possible via left/right)
