### ISSUE TITLE
Wiki images

### ISSUE THREAD

**Issue by simontrhodes** [MobiFlight/MobiFlight-Connector#808]
Wiki images

![GNS530 Config](https://user-images.githubusercontent.com/24565002/169653535-fd79a120-f2fd-40a5-a7ac-746b9f8b9f76.PNG)
![GNS530-All inputs](https://user-images.githubusercontent.com/24565002/169653537-1056b910-a1e3-4536-84d5-26b93fce6e2d.PNG)
![GNS530-Debug Button](https://user-images.githubusercontent.com/24565002/169653538-3dcebde8-f82d-4e64-bf87-f9ba80e06b0c.PNG)
![GNS530-Debug530](https://user-images.githubusercontent.com/24565002/169653539-0d153255-1641-44ab-b4ce-4b750076785f.PNG)
![GNS530-Encoder](https://user-images.githubusercontent.com/24565002/169653540-89e47508-9364-43c8-9a7b-4994857e4d6b.PNG)
![GNS530-Firmware not recognised](https://user-images.githubusercontent.com/24565002/169653541-68fd4644-6fa0-4ba9-96f3-7c544eeb14fc.PNG)
![GNS530-Firmware recognised](https://user-images.githubusercontent.com/24565002/169653542-770078a7-bf7e-49e7-82b2-3bc3c6b86ba2.PNG)
![GNS530-flash](https://user-images.githubusercontent.com/24565002/169653543-e92dd674-39b2-44cc-bc88-407f16394cf6.PNG)
![GNS530-Input Config](https://user-images.githubusercontent.com/24565002/169653544-47f0ff0c-c623-40ab-9f8a-fe6cd5aa955a.PNG)
![GNS530-MF Settings](https://user-images.githubusercontent.com/24565002/169653545-6a80fcb7-6371-440b-9110-ae387abd55f0.PNG)
![GNS530-Module with factory firmware](https://user-images.githubusercontent.com/24565002/169653546-6fbd5a42-b154-4598-8dee-e6ccaa96ef54.PNG)
[All Inputs.mfmc.txt](https://github.com/MobiFlight/MobiFlight-Connector/files/8747701/All.Inputs.mfmc.txt)

**Comment by DocMoebiuz** [comment]
Thanks! I will close this
