### ISSUE TITLE
Max device limits are not enforced for output shifters

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#821]
Looks like the maximum limits of devices like shift registers are not enforced.

Like for Pro Micro, there is defined MAX_OUTPUT_SHIFTERS 2 for Pro Micro and 4 for Mega in boards definition file on the firmware. But it appears I can just add as many as I like on MF Connector side, until I generally run out of pins.

The flashing seems to work too, but I dont have enough shift registers to prototype if they all actually work.

![image](https://user-images.githubusercontent.com/2587818/170977372-5f1f970e-caea-452d-bca9-2a9ef84eb2b0.png)

**Comment by tigert** [comment]
Additionally when I tried to flash my old .mfmc backup back to the pro micro that had 6 shift registers configured, it failed, until I manually deleted them from the list, and flashed the board with an empty config first. After that I could load up my .mfmc file from disk and flash it back to my original device configuration.

**Comment by neilenns** [comment]
Looks like this is just an issue with output shift registers, there's no check being done against max supported.
