### ISSUE TITLE
MobiFlight hanging during startup

### ISSUE THREAD

**Issue by jeffdamp-wave** [MobiFlight/MobiFlight-Connector#847]
**Describe the bug**
as of 7:50pst MobiFlight is failing to load and hangs.  Looks like the issue is the update checker A;utoUpdateChecker.cs(46). When calling into the MobiFlight-Installer.exe.  I have not looked into the installer code.

**Steps To Reproduce**
1. Launch MobiFlight
2. Wait

**Expected behavior**
App should load and work as expected

**Actual behavior**
App hangs during startup.

**Details**
 - MobiFlight Version: 9.4.0.x
 - FlightSim: MSFS2020
 - AddOn: Default Aircraft

**Additional context**
Bypassing the AutoUpdatechecker allows for mobiflight to run normally. Just renaming the MobiFlight-Installer.exe to something else will also bypass the check.

**Comment by DocMoebiuz** [comment]
Auto renewal of TLS cert failed, renewal was done manually at about 05:45UTC.
