### ISSUE TITLE
Option to disable automatic update dialog on program startup

### ISSUE THREAD

**Issue by JeffL-Fathom5** [MobiFlight/MobiFlight-Connector#849]
**Is your feature request related to a problem? Please describe.**
Being asked to update every time the program is launched (especially if the user wants to remain on their current version) is annoying.

**Describe the solution you'd like**
The user should have the option to enable or disable automatic update checks.

**Describe alternatives you've considered**
A "do not ask me again" check box if the user declines the update.

**Comment by JeffLatham** [comment]
Fair enough. Thanks for the explanation. I do admit that I've never had any issues after updating. Thanks for the hard work!
