### ISSUE TITLE
Shift Register Names are not displayed on the mappings screen

### ISSUE THREAD

**Issue by simontrhodes** [MobiFlight/MobiFlight-Connector#850]
**Describe the bug**
On the mappings screen, the names of Shift Registers are not displayed in the Output column.

**Steps To Reproduce**

1. Add a Shift Register to an Arduino.
2. At an Output using the added Shift Register
3. The Shift Register name is not displayed on the grid.

**Expected behavior**
The name of the Shift Register should be displayed.

**Actual behavior**
The name is shown as -

**Details**
 - MobiFlight Version: 9.4.0 and above

**Additional context**

**Comment by DocMoebiuz** [comment]
Did not auto close.
Please use fixes #myissuenumber in the PR next time. Thanks!
