### ISSUE TITLE
User always have to select which Arduino board they are using, even if there is only one.

### ISSUE THREAD

**Issue by simontrhodes** [MobiFlight/MobiFlight-Connector#857]
**Is your feature request related to a problem? Please describe.**
In the display tab of the output config wizard, you can select which Arduino board you want to select.
This field is named as the module.
If you only have one Arduino board, you still have to select it from the list.

**Describe the solution you'd like**
If there is only one module, it is pre-selected for you.

**Describe alternatives you've considered**
None

**Additional context**
Code already modified for the output tab.
I couldn't work out where the code is for the input tab.

**Comment by DocMoebiuz** [comment]
fixed by https://github.com/MobiFlight/MobiFlight-Connector/pull/858
