### ISSUE TITLE
creating a fake input shifter makes makes memory footprint grow

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#864]
When I create a new input shifter without actual input shifter chip in place (so the pins are floating) the firmware generates a lot of phantom events for the pins when data pin is pin 2 on Pro Micro or Uno firmware (I have a Nano to test with).

There are two things I noticed:

  * This only happens with Pro Micro and Uno firmwares (tested with Pro Micro and Nano that runs Uno fw)
  * This only happens when DATA is set to pin 2.
  * It doesnt seem to happen on Mega

The random events are kinda understandable since the pin is floating, but it only happens when the data pin is 2, and they happen  

Is there something else going on that pin? 

Also these fake events seem to bloat the memory footprint, but this could be a separate issue.

**Comment by DocMoebiuz** [comment]
why bother? what motivates you to add a fake input shifter and then worry about weird side effects? If this happens with an actual shifter attached, then I'd say that is worth investigating. 

"Nano" is also not supported at the moment.

**Comment by DocMoebiuz** [comment]
I hope you don't mind if i close this. Maybe the recent fixes have actually solved it, because pins get properly intialized. Feel free to post feedback if you can test.
