### ISSUE TITLE
^VID_1A86&PID_7523 wrongly recognized as Arduino Mega

### ISSUE THREAD

**Issue by Little-Plum** [MobiFlight/MobiFlight-Connector#871]
**Describe the bug**
My Arduino UNO  (hardwareids is: ^VID_1A86&PID_7523) was wrongly recognized as Mega and caused a firmware upload error. I tried to swaped them into JSON file and it works fine.
**Steps To Reproduce**
Uno board reported by a user with this vid/pid is recognized as Mega.

**Expected behavior**
Uno board reported by a user with this vid/pid is recognized as Mega.

**Details**
 - MobiFlight Version: 9.4.0
 - FlightSim: MSFS2020

**Comment by Little-Plum** [comment]
![0UAK_8TSC}UQ16$S QS{AIY](https://user-images.githubusercontent.com/22552915/179404832-8ef56993-4284-4672-86f2-7e8eb289187c.jpg)
![1LW$2N$%T KWQQVEPK50Q33](https://user-images.githubusercontent.com/22552915/179404837-eb0fd165-094d-4fb9-a098-5c1654a819b2.png)
![$KY41H1 K3XFUZQY3I9V{S9](https://user-images.githubusercontent.com/22552915/179404843-0b390d5e-21ad-428f-8ede-b52e7eac20b8.png)

**Comment by neilenns** [comment]
This is another example of an Uno using the CH340 chip for USB communication. There's no way to tell it apart from a Mega based on VID/PID.

**Comment by JaimeLeon2** [comment]
@Little-Plum yeah, this is a known issue with clone Uno boards using the CH340 chip.  There is just no way to tell them apart from a Mega board using the same chip, but you successfully did the workaround.  The good news is your Uno board will be recognized correctly on all subsequent firmware updates, as long as the Mobiflight firmware is loaded.

**Comment by DocMoebiuz** [comment]
I will close this then, and I will add a special dialog in the future to select the type for these kind of boards.
