### ISSUE TITLE
BSOD when FSUIPC is closed while MF Connector is running

### ISSUE THREAD

**Issue by DaGinYus** [MobiFlight/MobiFlight-Connector#882]
**Describe the bug**
Windows shows blue screen with error UNEXPECTED_KERNEL_MODE_TRAP when FSUIPC stops running while MF Connector is running. There is an infinite loop of messages that FSUIPC has disconnected, then the computer crashes.

**Steps To Reproduce**
1. Have MF Connector with FSUIPC7 running.
2. Close FSUIPC7

**Expected behavior**
Error message shows and MF Connector stops running.

**Actual behavior**
MF Connector opens infinitely many notification windows that FSUIPC is disconnected, then the computer crashes.

**Details**
 - MobiFlight Version: 9.4.0
 - FlightSim: MSFS2020
 - FSUIPC7 Version: 7.3.7

**Comment by pizman** [comment]
Can **not** reproduce.
MF 9.4.0.4 BETA
FS2020  1.26.5.0
FSUIPC 7.2.16

**Comment by DocMoebiuz** [comment]
@DaGinYus - Can you still reproduce this with the 9.5 version and a newer FSUIPC?

**Comment by DaGinYus** [comment]
The issue seems to have been resolved
