### ISSUE TITLE
LED Xplane dataref decimal number

### ISSUE THREAD

**Issue by liudreak** [MobiFlight/MobiFlight-Connector#884]
Hello, we are using the beta version 9.4.0.4 for programming our arduino mega 2560 r3 boards, the xplane dataref/command feature are perfect, they are much stable/easier than using xpuipc offset cfg file. But we have problem with decimal number for LED,  if you can include support decimal number into next update: 

we have:
X-plane 11 64bit
mobiflight connector 9.4.0.4
xpuipc
arduino mega 2560 r3

when we tried to set LED output, the data output can only use 1 or 0, if dataref value/Flight Sim Value is like 0.7, then it cannot set output Value to 1 to turn LED on, because it recongnize as 0. The support decimal number would be perfect.

thank you

**Comment by DocMoebiuz** [comment]
MobiFlight currently supports only Integers when sending the values to displays.
The trick is to multiply the value prior to further processing, e.g. by
```
$*10
```

So you convert 0.7 to 7 and then you can use the value for the 7 segment display. where you can use 2 digits and set the "." decimal on the first.

I will close this issue since there is a workaround and it is a current general philosophy.

**Comment by DocMoebiuz** [comment]
Btw, you can send decimal values back to xplane. that is actually possible.

**Comment by liudreak** [comment]
we tried $ * 10 in transform and it work. What we are programming is for LED diod, not display, so the positive value for 1 or big than 1 is enough to turn LED on. 

I would like to ask if there is any posibility to use only part of the flightsim valve number, for example: landing gear indication, that turn one LED on (green LED in sim) for flightsim value 1, and turn another LED on (red LED in sim) for flightsim value between 0.99 - 0.01, is there any possibility to use symbol <; >; <= etc in transform? and how to set it? I tried $ > 0.7 and it came with error: Transform error, An error occurred on parsing your valve formula. thank you

**Comment by liudreak** [comment]
also for dataref command in mobiflight, is possible to set command press? because some of the command are using for double function, command once for one function and command press for another.

**Comment by DocMoebiuz** [comment]
This is a current limitation by the XPlane UDP API. I will have to create a proper XPlane plugin to enable Hold-commands

**Comment by DocMoebiuz** [comment]
> we tried $ * 10 in transform and it work. What we are programming is for LED diod, not display, so the positive value for 1 or big than 1 is enough to turn LED on.
> 
> I would like to ask if there is any posibility to use only part of the flightsim valve number, for example: landing gear indication, that turn one LED on (green LED in sim) for flightsim value 1, and turn another LED on (red LED in sim) for flightsim value between 0.99 - 0.01, is there any possibility to use symbol <; >; <= etc in transform? and how to set it? I tried $ > 0.7 and it came with error: Transform error, An error occurred on parsing your valve formula. thank you

Well there is a landing gear tutorial on youtube. I use the compare function for it.
https://youtu.be/98sx64YF4h0
