### ISSUE TITLE
Group rows

### ISSUE THREAD

**Issue by gabfus** [MobiFlight/MobiFlight-Connector#887]
Hello, I understood that MF is not multi-instance, I can't start more instance one for any my mcc.
I try to merge all in one mcc. Is possible to add a group element for separate the input and output? and also enable or disable all inner content?

For example

Input
**AP**
!-ENC ALT
!-ENC HDG
**COM1**
!- ENC 
**COM2**
!- ENC
**NAV1**
!- ENC  
**NAV2**
!- ENC  

Output
**AP**
!- 7 LED ALT
!- 7 LED HDG
!- etc..
**COM1**
!- 7 LED ACTIVE
!- 7 LED STB
**COM2**
!- 7 LED ACTIVE
!- 7 LED STB
**NAV1**
!- 7 LED ACTIVE
!- 7 LED STB
**NAV2**
!- 7 LED ACTIVE
!- 7 LED STB

**Comment by DocMoebiuz** [comment]
Hi @gabfus - there is already a feature request on the backlog. https://github.com/MobiFlight/MobiFlight-Connector/issues/176

In the meantime you can try using a group prefix in your names, e.g.

AP - Encoder ALT
AP - Encoder HDG
COM1 - Encoder 

etc.

I will close this issue as a duplicate.

**Comment by gabfus** [comment]
Hello, sorry for duplicate request. I already use a prefix on each row, but a group is more useful.

Thanks

**Comment by DocMoebiuz** [comment]
No worries. I agree, it would be convenient!
