### ISSUE TITLE
Multiple instance and start by command

### ISSUE THREAD

**Issue by gabfus** [MobiFlight/MobiFlight-Connector#893]
Hello, Is possible to make no single instance of mf? If it is possible, start an instance with parameters: file mcc, usb/com etc.
I make two projects (autopilot and radio) with two Arduino mega and I want to use one or other or all two.
I dont want merge all in one project but separate into two hardware and two mcc and firmware (i/o config).
Thanks for your job

**Comment by DocMoebiuz** [comment]
@gabfus - this is not possible. You can only launch one MF instance at a time and I don't see a compelling reason to change that.

I don't understand your use case completely, so please explain it a little bit more in detail.

What you can do today:
* Create one config for the radio - e.g. radio.mfc
* Create one config for the autopilot, e.g. autopilot.mfc
* Create one config, where you merge radio and autopilot, e.g. cockpit.mfc

You can create three shortcuts and provide a cmd line argument `/cfg filepath-to-config`

So depending on which short cut you use the appropriate config can be loaded.

**Comment by gabfus** [comment]
Thanks for info.

**Comment by gabfus** [comment]
> @gabfus - this is not possible. You can only launch one MF instance at a time and I don't see a compelling reason to change that.
> 
> I don't understand your use case completely, so please explain it a little bit more in detail.
> 
> What you can do today:
> 
> * Create one config for the radio - e.g. radio.mfc
> * Create one config for the autopilot, e.g. autopilot.mfc
> * Create one config, where you merge radio and autopilot, e.g. cockpit.mfc
> 
> You can create three shortcuts and provide a cmd line argument `/cfg filepath-to-config`
> 
> So depending on which short cut you use the appropriate config can be loaded.



> @gabfus - this is not possible. You can only launch one MF instance at a time and I don't see a compelling reason to change that.
> 
> I don't understand your use case completely, so please explain it a little bit more in detail.
> 
> What you can do today:
> 
> * Create one config for the radio - e.g. radio.mfc
> * Create one config for the autopilot, e.g. autopilot.mfc
> * Create one config, where you merge radio and autopilot, e.g. cockpit.mfc
> 
> You can create three shortcuts and provide a cmd line argument `/cfg filepath-to-config`
> 
> So depending on which short cut you use the appropriate config can be loaded.

Hello, I have a cockpit project AP + RADIO and now I want to add panel switch for light but with a single board I don't have other pins to use. Is not possible in the future to use multiple boards into a single project mcc?

Thanks for jour job
