### ISSUE TITLE
When adding 2nd multiplexer the base pins are not displayed correctly

### ISSUE THREAD

**Issue by DocMoebiuz** [MobiFlight/MobiFlight-Connector#894]
**Describe the bug**
When adding 2nd multiplexer the base pins are not displayed correctly

**Steps To Reproduce**
1. Go to Mobiflight Settings
2. Click on a board
3. Add a first multiplexer
4. Upload the config
5. Close the Wizard
6. Open MobiFlight Board Settings again
7. Add another input multiplexer to the same board
8. Check the base settings

**Expected behavior**
Base settings show same pins for the multiplexer as first multiplexer

**Actual behavior**
Base settings show different pins for the multiplexer than first multiplexer

**Details**
 - MobiFlight Version: [e.g. 8.2.0]
 - FlightSim: [e.g. MSFS2020]
 - AddOn: [e.g. Default Aircraft]

**Additional context**
First Input Multiplexer
<img width="433" alt="image" src="https://user-images.githubusercontent.com/86157512/185745942-7eb13fb3-ca81-40b6-8265-89bd06c1d939.png">

Second Input Multiplexer
<img width="429" alt="image" src="https://user-images.githubusercontent.com/86157512/185745954-fdb78abb-ca4e-4115-9bfc-58ad249d349a.png">

Exception raised when accessing the Board Settings again.

**Comment by ddt154** [comment]
Although its a bug, a work around is to manually modify the saved config file and then load it.  It'll then have the correct config and work properly.  You can then upload config to device and works fine.
