### ISSUE TITLE
Retrigger function does not initialize current value of analog potentiometers

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#898]
**Describe the bug**
The retrigger function does not initialize the current value of analog potentiometers position.

**Steps To Reproduce**
1. Start Mobiflight with a potentiometer config assigned to a light dimmer in the sim and pot in mid position.
2. Press the retrigger button
3. Note lights in the sim did not sync to the pot position.

**Expected behavior**
Retrigger should synchronize the pot position in the sim.

**Actual behavior**
Potentiometer is ignored in the retrigger.  Nothing happens.

**Details**
 - MobiFlight Version: 9.4.0.4
 - FlightSim: irrelevant
 - AddOn: irrelevant

**Additional context**
Workaround is to move the pot, which defeats the purpose of the retrigger function.

**Comment by neilenns** [comment]
Firmware bug: https://github.com/MobiFlight/MobiFlight-FirmwareSource/issues/202

**Comment by DocMoebiuz** [comment]
@neilenns - I updated your comment because I was confused for a moment.

Firmware was updated https://github.com/MobiFlight/MobiFlight-FirmwareSource/pull/199
Still requires firmware release and PR for updating the firmware.

**Comment by neilenns** [comment]
Yeah I thought it was fixed, but without the bug on the other side it wouldnt auto appear in the firmware release notes
