### ISSUE TITLE
Add missing VID/PID

### ISSUE THREAD

**Issue by hakan42** [MobiFlight/MobiFlight-Connector#902]
I have a board that is not detected, please add it to MobiFlight with this information

**Provide the VID / PID combination**
Check the device manager for this information
VID: 2341
PID: 0058

**Provide type of board**
- [ ] Arduino Mega 2560
- [X] Arduino Pro Micro
- [ ] Arduino Uno

Board bought at Amazon: 

https://smile.amazon.de/-/en/gp/product/B08ZMMNLZ8

**Comment by DocMoebiuz** [comment]
@hakan42 thanks for reporting! Have already added it to your local board config json file and could you confirm it works?

**Comment by hakan42** [comment]
I have updated my arduino_micro.board.json file, and the module is found on startup.

I could not flash the firmware though, getting an error from avrdude:

`
Debug	07.09.2022 14:34:04	RunAvrDude : "Arduino\hardware\tools\avr\bin\avrdude"
Debug	07.09.2022 14:34:04	RunAvrDude : -C"Arduino\hardware\tools\avr\etc\avrdude.conf"  -patmega32u4 -cavr109 -P\\.\COM3 -b57600 -D -Uflash:w:"D:\Flight\Mobiflight\firmware\mobiflight_micro_2_2_0.hex":i
Info	07.09.2022 14:34:18	MobiflightModule.connect: Connected to Default at COM3 of type MobiFlight Micro (DTR=>True)
Debug	07.09.2022 14:34:22	MobiflightModule.Config: Timeout. !InfoCommand.Ok. Retrying...
Debug	07.09.2022 14:34:24	MobiflightModule.Config: !InfoCommand.Ok. Init with empty config.
Debug	07.09.2022 14:34:27	MobiFlightModule.GetInfo: Arduino Micro Pro, Default, , 
Error	07.09.2022 14:34:27	avrdude timed out! Something went wrong when flashing with command 
 "Arduino\hardware\tools\avr\bin\avrdude" -C"Arduino\hardware\tools\avr\etc\avrdude.conf"  -patmega32u4 -cavr109 -P\\.\COM3 -b57600 -D -Uflash:w:"D:\Flight\Mobiflight\firmware\mobiflight_micro_2_2_0.hex":i
Debug	07.09.2022 14:34:34	Fsuipc2Cache::connect() - No FSUIPC found.
`

**Comment by DocMoebiuz** [comment]
have you installed the required drivers?

**Comment by hakan42** [comment]
@DocMoebiuz is there anything else to be installed beside CH340 ? After installing the same, I rebooted fifty times until the module could be detected both by platformio and MFConnector in debug mode. I cannot get the image to be flashed, though, always seeing the error message above.

I'll try to flash a demo sketch from platformio later tonight to see if somehow the module itself is at fault.

**Comment by DocMoebiuz** [comment]
the pro micro typically doesn't use CH340 chips. Maybe you have to install the driver, check this tutorial: https://learn.sparkfun.com/tutorials/pro-micro--fio-v3-hookup-guide/installing-windows

**Comment by DocMoebiuz** [comment]
@hakan42, please confirm that the VID/PID is working for you correctly.

**Comment by DocMoebiuz** [comment]
@hakan42 please get back to me with feedback. I will close this issue otherwise.

**Comment by hakan42** [comment]
I'm not sure whether this specific MC is flasable but this might be totally a problem on my computer.

Let's close this for now, whenever I get around to actually confirm working I will open up a new one.

Thank you for your patience.

**Comment by DocMoebiuz** [comment]
ok. no worries!
