### ISSUE TITLE
Add message to debug log when run isn't on

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#903]
**Is your feature request related to a problem? Please describe.**
We semi-regularly have people coming into Discord wondering why their input events aren't resulting in stuff happening in the sim. Usually this is because they forgot to hit the "Run" button, but the only way to figure this out is to notice it in a screenshot of the main MobiFlight screen.

**Describe the solution you'd like**
Add a little message to the debug log for input events getting triggered that indicates run isn't enabled. That way when we're asking for log messages we'll quickly see what the issue is.

**Comment by pizman** [comment]
Basically a interesting idea.
But this is a special situation.

For sure.  In MF we could do this to help users....
But then we would need a Pupup!

Cause i will say 99% of users who not understand they miss to press RUN also not have Logging Enabled !
Those "Noobs" (sorry for the wording) definitly not know what loggin mode is or use it.

On the other side.... People who have Logging Active will maybe forgot to press run from time to time.... But they realize there issue after press the butten 2 times without react and NOT need a Warning for this !
