### ISSUE TITLE
Input config events are shown even if board is not present

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#913]
**Is your feature request related to a problem? Please describe.**
Currently Mobiflight will not show any selected preset or code information when the assigned board is not connected.  This makes it almost impossible to share mcc files and at least be able to see what the other person did in Mobiflight.

**Describe the solution you'd like**
Input config wizard could show the board and device empty, but still show the preset and RPN code used in the config, 

**Describe alternatives you've considered**
No alternatives exist to share and easily review mcc files within Mobiflight, that I am aware of.
Sure, the mcc file can be opened in Notepad++ but not as convenient and requires the user to know how to read xml.

**Additional context**
None

**Comment by DocMoebiuz** [comment]
related to https://github.com/MobiFlight/MobiFlight-Connector/issues/468

**Comment by DocMoebiuz** [comment]
duplicate, see #468
