### ISSUE TITLE
Display goes to sleep after 15 minutes if 7 segment display is only configured device

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#917]
**Describe the bug**
Display goes to sleep after 15 minutes if 7 segment display is only configured device

**Steps To Reproduce**
1. Configure a 7 segment display module on an arduino
2. Ensure that's the only device type configured
3. Configure an output to the display
4. Run mobiflight and wait 15 minutes without doing anything to change the values shown on the 7 segment display

**Expected behavior**
The display is still showing the values after 15 minutes

**Actual behavior**
The display goes to sleep

Reported by a couple of users in the forums.

Workaround to resolve the issue for now is to add a basic LED output and configure it to output something. That'll cause the keep-alive to get sent to the display.

**Comment by JaimeLeon2** [comment]
My Transponder panel is showing these symptoms as well, but the 7 segment display is not the only output connected to this board.  This board also has connected Master Warning, Master Caution, AOA indicator, and Wet Compass.  None of those states I would expect to change while in "unattended" Run mode.

COPY OF MY COMMENTS IN THE DISCORD BETA CHANNEL

I can confirm now that the 7-segment display in my Transponder panel turned off after about 15 minutes of "unattended" Run mode.  Flight sim running, PMDG 737 loaded and sitting on the runway, Mobiflight in normal Run mode (all green checkmarks at the bottom), while I was doing something else, so focus was away from MSFS or Mobiflight.
I pressed Stop and Run in MF and the display turned back on.

Also noted that any input event occurring in the same board where the sleeping display is connected, caused the display to turn back on.  So I would suspect the keep alive code is not working for 7 segment displays
