### ISSUE TITLE
For New Configs - Change default of Active checkbox to "checked"

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#939]
**Is your feature request related to a problem? Please describe.**
Too many new users can't figure why their config does not work, and too many times we find that the config active checkbox is unchecked.  This is the default behavior when creating new configs.

**Describe the solution you'd like**
Have Mobiflight create new configs with status of "Active".

**Describe alternatives you've considered**
Sticky yellow note with "Don't forget to check the Active checkbox" stuck to your monitor

**Additional context**
Very many users clearly forget to activate new configs, even experienced users.  
I see no good reason for the default to be "Not Active".

**Comment by DocMoebiuz** [comment]
Thanks for creating this one. I was thinking about doing that just the other day.
