### ISSUE TITLE
Crash when attempting to save an output config for a module that has no outputs configured

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#949]
**Describe the bug**
Mobiflight crashes if you save an output config using a connected Arduino that has no configured output devices.

Found by Kayleigh in Discord.

**Steps To Reproduce**
1. Connect a single Arduino to your PC and don't configure any output devices.
2. Create a new output row, set it to point to something (SimConnect, xplane data ref, doesn't matter)
3. Don't click the Display tab
4. Hit OK

**Expected behavior**
Saves no problem

**Actual behavior**
Null reference exception in DisplayPanel.cs:246:

```C#
config.DisplayType = (displayTypeComboBox.SelectedItem as ListItem).Value;
```

**Details**
 - MobiFlight Version: 9.5.0.2

**Additional context**

This happens because there are no output devices configured for the Arduino but the Display panel is auto-selecting the connected Arduino without populating the DisplayType dropdown (since there are no output devices on the board).

You can reproduce the same issue by manually selecting a board with no output devices, hitting "no" to the dialog that warns you about it, and then hitting ok anyway. That's how I reproduced it, using my CJ4 Electrical Panel board that only has input devices on it.

Workaround is to configure at least one output device on the board.

**Comment by DocMoebiuz** [comment]
![949](https://user-images.githubusercontent.com/86157512/194773955-b27e5280-815d-44dd-b76b-e87ac3236fce.gif)

I have trouble reproducing it.
