### ISSUE TITLE
Math Symbols in Compare as Text  occure in a  Log Warning

### ISSUE THREAD

**Issue by pizman** [MobiFlight/MobiFlight-Connector#960]
**Describe the bug**
If we use Symbols that are also operators within a THEN/ELSE in Compare  as pure text then we get a warning.
For example    Then:   -   or Then: -abc123  
Here the "-" is the problem.
Then:   Abc123 .... will work.
(Same issue for +-*/% and so on)

**Steps To Reproduce**
Create Compare
Say If Value = 1     THEN   -   else -    (NOT use Quotes)

**Expected behavior**
In case normal Text like HELLO  can be used also without single Quotes ' ' i would expect also a Minus-  should be seen as Text without need to use Single Quotes   '-'

**Actual behavior**
Display work.... MF not crash but occur in a endless Issue warning.
If we enter the text within quotes '-' it work fine

**Additional context**
We should official define that Text in Compare MUST be used within Quotes  OR we need a definition that say "all what is not a correct Ncalc Math Syntax is automatically Text ....
E.g.  3+4  occur in 7  Cause its math ....   3+ is no correct math.... so its automatically text !

![grafik](https://user-images.githubusercontent.com/26087116/195646432-46097fc9-0002-4c4e-b490-1060a5c306ff.png)

**Comment by DocMoebiuz** [comment]
@pizman This is in my opinion OK. If you want a standalone string you have to use a single quotes around it.

I won't fix this.
