### ISSUE TITLE
Compare converts quoted strings to numeric values

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#969]
**Describe the bug**
The Compare function is converting quoted numbers into numeric values.  This is undesired.

**Steps To Reproduce**
1. Create an output config
2. Put 0 in Transform
3. Go to Compare and set if = to 0, then set it to '0000'
4. Press OK
5. Note the value of the config is not '0000' but only '0'

**Expected behavior**
Compare respects the quoted string and does not convert quoted numbers to numeric value.

**Actual behavior**
Compare converts the quoted numbers into a numeric value.

**Details**
 - MobiFlight Version: 9.5.0.2
 - FlightSim: irrelevant
 - AddOn: irrelevant

**Additional context**
only happens with quoted numbers.

**Comment by tigert** [comment]
While we have used Compare to set special things like "blank when value is -1" and other things, maybe it would be better to have a proper way to format numbers into strings for output? 

Would the "transform" stuff @DocMoebiuz is working on be usable for this? 

I mean, internally it could be just a formatting string for printf like "%04d" from 0 would give you the desired "0000". It probably could use a sensible user interface than just a text field (or maybe a dropdown with some common examples (padded result length + fill character, and maybe a raw format string for the special cases)

**Comment by DocMoebiuz** [comment]
yes, i was thinking about that for the modifiers. For the moment I made it behave like before. There is a PR that I will merge in a bit.
