### ISSUE TITLE
(Beta) Autofill needs to (re)click LED/Output for select pins dropdown

### ISSUE THREAD

**Issue by CaptainBobSim** [MobiFlight/MobiFlight-Connector#977]
**Describe the bug**
If you jump over to display everything autofills but you have to select LED/Output from the list for it to work correctly

![image](https://user-images.githubusercontent.com/76851401/196338866-1a28bdee-b35c-4c4b-8181-553ab94f4604.png)

**Steps To Reproduce**
1. I made a configuration that uses LEDs
2.  they autofilled output device, module, and "use type of",
3. The devices didn't show what device it was affecting until I selected LED/Output from the list

![image](https://user-images.githubusercontent.com/76851401/196339141-5e73a084-64d6-44c1-b5bd-71da225cad0c.png)

Selecting already selected LED from list shows this ^^

**Expected behavior**
Select pins shows automatically

**Actual behavior**
Select pins is hidden until you select LED/Output

**Details**
- Beta  9.5.0.3

**Additional context**
Sorry for doing this in GitHub - I think you prefer discord for beta bugs?

**Comment by DocMoebiuz** [comment]
this is fixed in #971
