### ISSUE TITLE
Rename and reorder input action types in drop down

### ISSUE THREAD

**Issue by DocMoebiuz** [MobiFlight/MobiFlight-Connector#979]
**Is your feature request related to a problem? Please describe.**
Since we have the new native integration with XPlane, this item could be a bit higher up in the list.
Additionally, the naming of MSFS2020 Custom presets is also out-dated.

**Describe the solution you'd like**
Have simple names that make clear what the types are good for:
* Simulator
* AddOn
* Plugin (optional)

**Describe alternatives you've considered**
Leave it as is.

**Additional context**

<img width="508" alt="image" src="https://user-images.githubusercontent.com/86157512/197420142-add567d3-e40a-4627-8486-3721c324e03a.png">

**Comment by neilenns** [comment]
For stuff like this I find it helpful to look back at how users ask questions in the MobiFlight discord. It gives a good view as to how they think about the task at hand and what they are looking for in the app.

The vast majority of the time new users come to discord and lead with the simulator they're using. "How do I make the parking brake work in MSFS2020?" "How do I change the altitude in xplane"? "I'm using FSX and can't get the taxi light to work, can anyone assist?". Unless the user already has experience using MobiFlight or is following an older tutorial they don't typically mention things like "FSUIPC" or "SimConnect" or "WASM".

If I were re-doing this dialog from scratch I would have one dropdown with this in it:

* FSX, Prepare3D, MSFS2020 (legacy)
* Microsoft Flight Simulator 2020
* MobiFlight 
* xplane

It's a short, simple, list that guides the user directly to the right option without having to show the under-the-covers protocol details.

This is clearly missing many of the entries in the current dropdown. I would add a second dropdown to provide the second level of selection that is currently handled by multiple entries. If someone selects the _FSX, Prepare3D, MSFS2020 (legacy)_ dropdown the second dropdown would show:

* EventId
* Jeehall events
* LUA macro
* Offset
* PMDG EventId

If someone selects MobiFlight it would show:

* Keyboard input
* Retrigger switches
* Variable
* Virtual joystick input (vJoy)

**Comment by pizman** [comment]
I agree with Neils idea...

But i would not Put MSFS2020 legacy  within the FSX/P3D Tab....
instead i would offer "Offset", PMDG Events, EventID and so on 2 times...
In the FSX/P3D  ... AND.... Also in the FS2020 Tab.
Maybe there with the additional Namepart ....  Like   EventID (FSUIPC needed)  or so.

If we split the Types by Simulators it make no sense to use FS2020 in two taps..... better to duplicate the Typs !

**Comment by DocMoebiuz** [comment]
I kind of like the grouping but the MSFS(legacy) sounds weird, since there is no real legacy in MSFS2020. It is FSUIPC.
Also the downside multiple drop downs, is hiding keyb, retrigger, variables, vJoy inside of MobiFlight - people will have to first choose to learn what is in there, same with the FSX group.

Maybe another option would be:
* First start: Hi user, what sims are you using?
  * Options: MSFS2020, X-Plane, P3D, FSX
  * When clicking MSFS2020: do you use FSUIPC for MSFS2020? (Yes, No, Don't know)

Then this also can become a project setting in the future. I really want to introduce that some time soon. When you create a new project, you select which aircraft. and maybe the project could contain multiple cfg files (no clue how they get executed :D - but a thought)

In the mean time as simple approach, one drop down:
* Microsoft Flight Simulator 2020
* X-Plane
* MobiFlight - Retrigger switches
* MobiFlight - Variable
* MobiFlight - Virtual joystick input (vJoy)
* Microsoft Flight Simulator 2020 (FSUIPC Offsets)
* FSX, P3D - FSUIPC Offsets
* FSX, P3D - FSUIPC EventId PMDG
* FSX, P3D - FSUIPC EventId
* FSX, P3D - FSUIPC LUA Macro
* FSX, P3D - FSUIPC Jeehell
* FSX, P3D - Keyboard input

**Comment by DocMoebiuz** [comment]
isn't it that only PMDG requires FSUIPC at the moment for MSFS2020 and a few functions only?

**Comment by neilenns** [comment]
That list looks nice @DocMoebiuz. PMDG is the oddball for MSFS2020 as far as I'm aware.

**Comment by DocMoebiuz** [comment]
I don't think  `Microsoft Flight Simulator 2020 (FSUIPC Offsets)` makes sense, because basically all FSUIPC events are compatible with MSFS2020 too

**Comment by DocMoebiuz** [comment]
Microsoft Flight Simulator 2020
X-Plane
MobiFlight - Variable
MobiFlight - Virtual joystick input (vJoy)
MobiFlight - Retrigger switches
FSX, P3D, MSFS2020 - FSUIPC Offsets
FSX, P3D, MSFS2020 - FSUIPC EventId PMDG
FSX, P3D, MSFS2020 - FSUIPC EventId
FSX, P3D, MSFS2020 - FSUIPC LUA Macro
FSX, P3D, MSFS2020 - FSUIPC Jeehell
FSX, P3D - Keyboard input

**Comment by DocMoebiuz** [comment]
ok there is no Jeehell

**Comment by DocMoebiuz** [comment]
We have to leave FSUIPC instead of FSX, P3D - it simply works via FSUIPC.

**Comment by DocMoebiuz** [comment]
<img width="508" alt="image" src="https://user-images.githubusercontent.com/86157512/198657480-6aec6ec7-3a00-4021-a20d-45b01a2833c3.png">

I am not even thrilled btw it looks like :D
