### ISSUE TITLE
Show  Configname of a Input config in the Logging when a Button is pressed.

### ISSUE THREAD

**Issue by pizman** [MobiFlight/MobiFlight-Connector#984]
**Is your feature request related to a problem? Please describe.**
In Building Process we use the Logging and press a Button e.g. to find out if its connected and if its working and also whats the name of it.   But we can currently not see in Log WHAT Config is using it.

**Describe the solution you'd like**
Include the NAME of the Config, who executed the Command when a Button is used.

**Additional context**
![grafik](https://user-images.githubusercontent.com/26087116/197332476-6e3c42bc-2477-4516-88ef-9215cd72efd5.png)

Thats the current Log.
I think in Execute log line the "Serial" is pretty unsless....
Why not replace it with the usefull information of the Config Name who trigger that Execute initially.
Like :  "Execute On Press B1 > Configname"

**Comment by neilenns** [comment]
I think I looked into this once and it wasn't as straightforward as I hoped :( The config name wasn't available at the point where the log message gets written.
