### ISSUE TITLE
Support defining joysticks via json files

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#992]
**Is your feature request related to a problem? Please describe.**
Right now joysticks get detected but with generic input names. We're about to add support for specific input names for the Honeycomb Bravo, but what about all the other joysticks?

**Describe the solution you'd like**
Provide a way to specify joystick information via json files that are loaded at startup so additional joysticks can be defined with friendly names for inputs/outputs without having to recompile Mobiflight.

**Describe alternatives you've considered**
This is too cool to consider alternatives.

**Additional context**
This would be similar to how Boards are handled. Make sure to support joysticks that don't have a customized definition file too.

**Comment by DocMoebiuz** [comment]
are you gonna work on this soon?

**Comment by neilenns** [comment]
I was waiting for you to check in the honeycomb bravo stuff and then I was going to generalize that

**Comment by neilenns** [comment]
I don't know, is it? I don't see every commit automatically 😂


________________________________

**Comment by neilenns** [comment]
Manufacturer-specific joystick support added: https://github.com/MobiFlight/MobiFlight-Connector/pull/1027. Now to generalize it?
